/*** Autogenerated by WIDL <undefined version> from C:/proj/reactos/sdk/include/reactos/idl/netdfs.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __netdfs_c_h__
#define __netdfs_c_h__

/* Forward declarations */

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

#ifndef _DTYP_IDL
#define _DTYP_IDL
#ifndef _WINDEF_H
typedef int BOOL;
typedef int *PBOOL;
typedef int *LPBOOL;
typedef unsigned char BYTE;
typedef unsigned char *PBYTE;
typedef unsigned char *LPBYTE;
typedef ULONG DWORD;
typedef ULONG *PDWORD;
typedef ULONG *LPDWORD;
#endif
#ifndef _BASETSD_H_
typedef unsigned int DWORD32;
typedef UINT64 DWORD64;
#endif
#ifndef _WINDEF_H
typedef int INT;
typedef int *LPINT;
#endif
#ifndef _BASETSD_H_
typedef signed char INT8;
typedef signed short INT16;
typedef signed int INT32;
typedef INT64 INT64;
#endif
#ifndef _BASETSD_H_
typedef signed int LONG32;
typedef INT64 LONG64;
#endif
typedef UINT64 QWORD;
#ifndef _WINNT_
typedef short SHORT;
#endif
typedef INT64 TIME;
#ifndef _WINNT_
typedef char CHAR;
typedef char *PCHAR;
typedef unsigned char UCHAR;
typedef unsigned char *PUCHAR;
#endif
#ifndef _WINDEF_H
typedef unsigned int UINT;
#endif
#ifndef _BASETSD_H_
typedef unsigned char UINT8;
typedef unsigned short UINT16;
typedef unsigned int UINT32;
typedef UINT64 UINT64;
#endif
#ifndef _WINNT_
typedef ULONG ULONG;
typedef ULONG *PULONG;
#endif
#ifndef _BASETSD_H_
typedef unsigned int ULONG32;
typedef UINT64 ULONG64;
#endif
#ifndef _WINNT_
typedef UINT64 ULONGLONG;
typedef unsigned short USHORT;
#endif
#ifndef _WINDEF_H
typedef unsigned short WORD;
typedef unsigned short *PWORD;
typedef unsigned short *LPWORD;
#endif
#ifndef _WINNT_
typedef LONG LONG;
typedef LONG *PLONG;
#endif
#ifndef _WINDEF_H
typedef LONG *LPLONG;
#endif
#ifndef _WINNT_
typedef INT64 LONGLONG;
#endif
#ifndef _WINDEF_H
typedef float FLOAT;
#endif
#ifndef __wtypes_h__
typedef double DOUBLE;
#endif
#ifndef _WINNT_
typedef BYTE BOOLEAN;
typedef BYTE *PBOOLEAN;
#endif
#ifndef _BASETSD_H_
typedef LONG LONG_PTR;
typedef ULONG ULONG_PTR;
typedef ULONG_PTR SIZE_T;
typedef ULONG_PTR DWORD_PTR;
#endif
typedef DWORD NET_API_STATUS;
#ifndef _WINNT_
typedef ULONGLONG DWORDLONG;
typedef ULONGLONG *PDWORDLONG;
#endif
typedef DWORD HCALL;
#ifndef _WINNT_
typedef void *HANDLE;
typedef void *PVOID;
#endif
#ifndef __WINE_RPCDCE_H
typedef void *RPC_BINDING_HANDLE;
#endif
typedef void *PCONTEXT_HANDLE;
typedef PCONTEXT_HANDLE *PPCONTEXT_HANDLE;
#ifndef _WINNT_
typedef wchar_t WCHAR;
typedef wchar_t *PWCHAR;
#if 0
typedef wchar_t UNICODE;
#endif
typedef const char *LPCSTR;
typedef const wchar_t *LPCWSTR;
typedef char *PSTR;
typedef char *LPSTR;
typedef wchar_t *LPWSTR;
typedef wchar_t *PWSTR;
#endif
typedef const wchar_t *LMCSTR;
typedef WCHAR *LMSTR;
#ifndef __wtypes_h__
typedef WCHAR *BSTR;
#endif
#if 0
typedef LPCSTR LPCTSTR;
typedef LPSTR LPTSTR;
typedef CHAR TCHAR;
#endif
#if 0
typedef struct _FILETIME {
    DWORD dwLowDateTime;
    DWORD dwHighDateTime;
} FILETIME;
typedef struct _FILETIME *PFILETIME;
typedef struct _FILETIME *LPFILETIME;
typedef struct _GUID {
    DWORD Data1;
    WORD Data2;
    WORD Data3;
    BYTE Data4[8];
} GUID;
typedef struct _GUID UUID;
typedef struct _GUID *PGUID;
typedef struct _LARGE_INTEGER {
    LONGLONG QuadPart;
} LARGE_INTEGER;
typedef struct _LARGE_INTEGER *PLARGE_INTEGER;
typedef DWORD LCID;
#endif
typedef struct _RPC_UNICODE_STRING {
    USHORT Length;
    USHORT MaximumLength;
    LPWSTR Buffer;
} RPC_UNICODE_STRING;
typedef struct _RPC_UNICODE_STRING *PRPC_UNICODE_STRING;
#if 0
typedef struct _SYSTEMTIME {
    WORD wYear;
    WORD wMonth;
    WORD wDayOfWeek;
    WORD wDay;
    WORD wHour;
    WORD wMinute;
    WORD wSecond;
    WORD wMilliseconds;
} SYSTEMTIME;
typedef struct _SYSTEMTIME *PSYSTEMTIME;
typedef struct _UINT128 {
    UINT64 lower;
    UINT64 upper;
} UINT128;
typedef struct _UINT128 *PUINT128;
typedef struct _ULARGE_INTEGER {
    ULONGLONG QuadPart;
} ULARGE_INTEGER;
typedef struct _ULARGE_INTEGER *PULARGE_INTEGER;
#endif
#if 0
typedef struct _SID_IDENTIFIER_AUTHORITY {
    BYTE Value[6];
} SID_IDENTIFIER_AUTHORITY;
typedef struct _SID {
    BYTE Revision;
    BYTE SubAuthorityCount;
    SID_IDENTIFIER_AUTHORITY IdentifierAuthority;
    DWORD SubAuthority[1];
} SID;
typedef struct _SID *PSID;
typedef struct _ACCESS_MASK {
    DWORD ACCESS_MASK;
} ACCESS_MASK;
typedef struct _ACCESS_MASK *PACCESS_MASK;
typedef struct _ACE_HEADER {
    UCHAR AceType;
    UCHAR AceFlags;
    USHORT AceSize;
} ACE_HEADER;
typedef struct _ACE_HEADER *PACE_HEADER;
typedef struct _ACCESS_ALLOWED_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} ACCESS_ALLOWED_ACE;
typedef struct _ACCESS_ALLOWED_ACE *PACCESS_ALLOWED_ACE;
typedef struct _ACCESS_ALLOWED_OBJECT_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD Flags;
    GUID ObjectType;
    GUID InheritedObjectType;
    DWORD SidStart;
} ACCESS_ALLOWED_OBJECT_ACE;
typedef struct _ACCESS_ALLOWED_OBJECT_ACE *PACCESS_ALLOWED_OBJECT_ACE;
typedef struct _ACCESS_DENIED_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} ACCESS_DENIED_ACE;
typedef struct _ACCESS_DENIED_ACE *PACCESS_DENIED_ACE;
typedef struct _ACCESS_ALLOWED_CALLBACK_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} ACCESS_ALLOWED_CALLBACK_ACE;
typedef struct _ACCESS_ALLOWED_CALLBACK_ACE *PACCESS_ALLOWED_CALLBACK_ACE;
typedef struct _ACCESS_DENIED_CALLBACK_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} ACCESS_DENIED_CALLBACK_ACE;
typedef struct _ACCESS_DENIED_CALLBACK_ACE *PACCESS_DENIED_CALLBACK_ACE;
typedef struct _ACCESS_ALLOWED_CALLBACK_OBJECT_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD Flags;
    GUID ObjectType;
    GUID InheritedObjectType;
    DWORD SidStart;
} ACCESS_ALLOWED_CALLBACK_OBJECT_ACE;
typedef struct _ACCESS_ALLOWED_CALLBACK_OBJECT_ACE *PACCESS_ALLOWED_CALLBACK_OBJECT_ACE;
typedef struct _ACCESS_DENIED_CALLBACK_OBJECT_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD Flags;
    GUID ObjectType;
    GUID InheritedObjectType;
    DWORD SidStart;
} ACCESS_DENIED_CALLBACK_OBJECT_ACE;
typedef struct _ACCESS_DENIED_CALLBACK_OBJECT_ACE *PACCESS_DENIED_CALLBACK_OBJECT_ACE;
typedef struct _SYSTEM_AUDIT_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} SYSTEM_AUDIT_ACE;
typedef struct _SYSTEM_AUDIT_ACE *PSYSTEM_AUDIT_ACE;
typedef struct _SYSTEM_AUDIT_CALLBACK_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} SYSTEM_AUDIT_CALLBACK_ACE;
typedef struct _SYSTEM_AUDIT_CALLBACK_ACE *PSYSTEM_AUDIT_CALLBACK_ACE;
typedef struct _SYSTEM_MANDATORY_LABEL_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} SYSTEM_MANDATORY_LABEL_ACE;
typedef struct _SYSTEM_MANDATORY_LABEL_ACE *PSYSTEM_MANDATORY_LABEL_ACE;
typedef struct _SYSTEM_AUDIT_CALLBACK_OBJECT_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD Flags;
    GUID ObjectType;
    GUID InheritedObjectType;
    DWORD SidStart;
} SYSTEM_AUDIT_CALLBACK_OBJECT_ACE;
typedef struct _SYSTEM_AUDIT_CALLBACK_OBJECT_ACE *PSYSTEM_AUDIT_CALLBACK_OBJECT_ACE;
typedef struct _ACL {
    UCHAR AclRevision;
    UCHAR Sbz1;
    USHORT AclSize;
    USHORT AceCount;
    USHORT Sbz2;
} ACL;
typedef struct _ACL *PACL;
typedef struct _SECURITY_DESCRIPTOR {
    UCHAR Revision;
    UCHAR Sbz1;
    USHORT Control;
    ULONG Owner;
    ULONG Group;
    ULONG Sacl;
    ULONG Dacl;
} SECURITY_DESCRIPTOR;
typedef struct _SECURITY_DESCRIPTOR *PSECURITY_DESCRIPTOR;
typedef DWORD SECURITY_INFORMATION;
typedef DWORD *PSECURITY_INFORMATION;
#endif
typedef struct _RPC_SID {
    UCHAR Revision;
    UCHAR SubAuthorityCount;
    SID_IDENTIFIER_AUTHORITY IdentifierAuthority;
    DWORD SubAuthority[1];
} RPC_SID;
typedef struct _RPC_SID *PRPC_SID;
#endif /* _DTYP_IDL */
typedef DWORD NET_API_STATUS;
typedef WCHAR *NETDFS_SERVER_OR_DOMAIN_HANDLE;
typedef enum _DFS_TARGET_PRIORITY_CLASS {
    DfsInvalidPriorityClass = -1,
    DfsSiteCostNormalPriorityClass = 0,
    DfsGlobalHighPriorityClass = 1,
    DfsSiteCostHighPriorityClass = 2,
    DfsSiteCostLowPriorityClass = 3,
    DfsGlobalLowPriorityClass = 4
} DFS_TARGET_PRIORITY_CLASS;
typedef struct _DFS_TARGET_PRIORITY {
    DFS_TARGET_PRIORITY_CLASS TargetPriorityClass;
    unsigned short TargetPriorityRank;
    unsigned short Reserved;
} DFS_TARGET_PRIORITY;
typedef struct _DFS_STORAGE_INFO {
    ULONG State;
    WCHAR *ServerName;
    WCHAR *ShareName;
} DFS_STORAGE_INFO;
typedef struct _DFS_STORAGE_INFO_1 {
    ULONG State;
    WCHAR *ServerName;
    WCHAR *ShareName;
    DFS_TARGET_PRIORITY TargetPriority;
} DFS_STORAGE_INFO_1;
typedef struct _DFS_STORAGE_INFO_1 *PDFS_STORAGE_INFO_1;
typedef struct _DFS_STORAGE_INFO_1 *LPDFS_STORAGE_INFO_1;
typedef struct _DFSM_ROOT_LIST_ENTRY {
    WCHAR *ServerShare;
} DFSM_ROOT_LIST_ENTRY;
typedef struct _DFSM_ROOT_LIST {
    DWORD cEntries;
    DFSM_ROOT_LIST_ENTRY Entry[1];
} DFSM_ROOT_LIST;
typedef enum __WIDL_netdfs_generated_name_00000000 {
    DFS_NAMESPACE_VERSION_ORIGIN_COMBINED = 0,
    DFS_NAMESPACE_VERSION_ORIGIN_SERVER = 1ul,
    DFS_NAMESPACE_VERSION_ORIGIN_DOMAIN = 2ul
} DFS_NAMESPACE_VERSION_ORIGIN;
typedef struct _DFS_SUPPORTED_NAMESPACE_VERSION_INFO {
    ULONG DomainDfsMajorVersion;
    ULONG DomainDfsMinorVersion;
    ULONGLONG DomainDfsCapabilities;
    ULONG StandaloneDfsMajorVersion;
    ULONG StandaloneDfsMinorVersion;
    ULONGLONG StandaloneDfsCapabilities;
} DFS_SUPPORTED_NAMESPACE_VERSION_INFO;
typedef struct _DFS_SUPPORTED_NAMESPACE_VERSION_INFO *PDFS_SUPPORTED_NAMESPACE_VERSION_INFO;
typedef struct _DFS_INFO_1 {
    WCHAR *EntryPath;
} DFS_INFO_1;
typedef struct _DFS_INFO_2 {
    WCHAR *EntryPath;
    WCHAR *Comment;
    DWORD State;
    DWORD NumberOfStorages;
} DFS_INFO_2;
typedef struct _DFS_INFO_3 {
    WCHAR *EntryPath;
    WCHAR *Comment;
    DWORD State;
    DWORD NumberOfStorages;
    DFS_STORAGE_INFO *Storage;
} DFS_INFO_3;
typedef struct _DFS_INFO_4 {
    WCHAR *EntryPath;
    WCHAR *Comment;
    DWORD State;
    ULONG Timeout;
    GUID Guid;
    DWORD NumberOfStorages;
    DFS_STORAGE_INFO *Storage;
} DFS_INFO_4;
typedef struct _DFS_INFO_5 {
    WCHAR *EntryPath;
    WCHAR *Comment;
    DWORD State;
    ULONG Timeout;
    GUID Guid;
    ULONG PropertyFlags;
    ULONG MetadataSize;
    DWORD NumberOfStorages;
} DFS_INFO_5;
typedef struct _DFS_INFO_6 {
    WCHAR *EntryPath;
    WCHAR *Comment;
    DWORD State;
    ULONG Timeout;
    GUID Guid;
    ULONG PropertyFlags;
    ULONG MetadataSize;
    DWORD NumberOfStorages;
    DFS_STORAGE_INFO_1 *Storage;
} DFS_INFO_6;
typedef struct _DFS_INFO_7 {
    GUID GenerationGuid;
} DFS_INFO_7;
typedef struct _DFS_INFO_8 {
    WCHAR *EntryPath;
    WCHAR *Comment;
    DWORD State;
    ULONG Timeout;
    GUID Guid;
    ULONG PropertyFlags;
    ULONG MetadataSize;
    ULONG SecurityDescriptorLength;
    PUCHAR pSecurityDescriptor;
    DWORD NumberOfStorages;
} DFS_INFO_8;
typedef struct _DFS_INFO_8 *LPDFS_INFO_8;
typedef struct _DFS_INFO_9 {
    WCHAR *EntryPath;
    WCHAR *Comment;
    DWORD State;
    ULONG Timeout;
    GUID Guid;
    ULONG PropertyFlags;
    ULONG MetadataSize;
    ULONG SecurityDescriptorLength;
    PUCHAR pSecurityDescriptor;
    DWORD NumberOfStorages;
    LPDFS_STORAGE_INFO_1 Storage;
} DFS_INFO_9;
typedef struct _DFS_INFO_9 *LPDFS_INFO_9;
typedef struct _DFS_INFO_50 {
    ULONG NamespaceMajorVersion;
    ULONG NamespaceMinorVersion;
    UINT64 NamespaceCapabilities;
} DFS_INFO_50;
typedef struct _DFS_INFO_100 {
    WCHAR *Comment;
} DFS_INFO_100;
typedef struct _DFS_INFO_101 {
    ULONG State;
} DFS_INFO_101;
typedef struct _DFS_INFO_102 {
    ULONG Timeout;
} DFS_INFO_102;
typedef struct _DFS_INFO_103 {
    ULONG PropertyFlagMask;
    ULONG PropertyFlags;
} DFS_INFO_103;
typedef struct _DFS_INFO_104 {
    DFS_TARGET_PRIORITY TargetPriority;
} DFS_INFO_104;
typedef struct _DFS_INFO_105 {
    WCHAR *Comment;
    DWORD State;
    ULONG Timeout;
    ULONG PropertyFlagMask;
    ULONG PropertyFlags;
} DFS_INFO_105;
typedef struct _DFS_INFO_106 {
    DWORD State;
    DFS_TARGET_PRIORITY TargetPriority;
} DFS_INFO_106;
typedef struct _DFS_INFO_107 {
    WCHAR *Comment;
    DWORD State;
    ULONG Timeout;
    ULONG PropertyFlagMask;
    ULONG PropertyFlags;
    ULONG SecurityDescriptorLength;
    PUCHAR pSecurityDescriptor;
} DFS_INFO_107;
typedef struct _DFS_INFO_150 {
    ULONG SecurityDescriptorLength;
    PUCHAR pSecurityDescriptor;
} DFS_INFO_150;
typedef struct _DFS_INFO_200 {
    WCHAR *FtDfsName;
} DFS_INFO_200;
typedef struct _DFS_INFO_300 {
    DWORD Flags;
    WCHAR *DfsName;
} DFS_INFO_300;
typedef union _DFS_INFO_STRUCT {
    DFS_INFO_1 *DfsInfo1;
    DFS_INFO_2 *DfsInfo2;
    DFS_INFO_3 *DfsInfo3;
    DFS_INFO_4 *DfsInfo4;
    DFS_INFO_5 *DfsInfo5;
    DFS_INFO_6 *DfsInfo6;
    DFS_INFO_7 *DfsInfo7;
    DFS_INFO_8 *DfsInfo8;
    DFS_INFO_9 *DfsInfo9;
    DFS_INFO_50 *DfsInfo50;
    DFS_INFO_100 *DfsInfo100;
    DFS_INFO_101 *DfsInfo101;
    DFS_INFO_102 *DfsInfo102;
    DFS_INFO_103 *DfsInfo103;
    DFS_INFO_104 *DfsInfo104;
    DFS_INFO_105 *DfsInfo105;
    DFS_INFO_106 *DfsInfo106;
    DFS_INFO_107 *DfsInfo107;
    DFS_INFO_150 *DfsInfo150;
} DFS_INFO_STRUCT;
typedef struct _DFS_INFO_1_CONTAINER {
    DWORD EntriesRead;
    DFS_INFO_1 *Buffer;
} DFS_INFO_1_CONTAINER;
typedef struct _DFS_INFO_2_CONTAINER {
    DWORD EntriesRead;
    DFS_INFO_2 *Buffer;
} DFS_INFO_2_CONTAINER;
typedef struct _DFS_INFO_3_CONTAINER {
    DWORD EntriesRead;
    DFS_INFO_3 *Buffer;
} DFS_INFO_3_CONTAINER;
typedef struct _DFS_INFO_4_CONTAINER {
    DWORD EntriesRead;
    DFS_INFO_4 *Buffer;
} DFS_INFO_4_CONTAINER;
typedef struct _DFS_INFO_5_CONTAINER {
    DWORD EntriesRead;
    DFS_INFO_5 *Buffer;
} DFS_INFO_5_CONTAINER;
typedef struct _DFS_INFO_6_CONTAINER {
    DWORD EntriesRead;
    DFS_INFO_6 *Buffer;
} DFS_INFO_6_CONTAINER;
typedef struct _DFS_INFO_8_CONTAINER {
    DWORD EntriesRead;
    LPDFS_INFO_8 Buffer;
} DFS_INFO_8_CONTAINER;
typedef struct _DFS_INFO_8_CONTAINER *LPDFS_INFO_8_CONTAINER;
typedef struct _DFS_INFO_9_CONTAINER {
    DWORD EntriesRead;
    LPDFS_INFO_9 Buffer;
} DFS_INFO_9_CONTAINER;
typedef struct _DFS_INFO_9_CONTAINER *LPDFS_INFO_9_CONTAINER;
typedef struct _DFS_INFO_200_CONTAINER {
    DWORD EntriesRead;
    DFS_INFO_200 *Buffer;
} DFS_INFO_200_CONTAINER;
typedef struct _DFS_INFO_300_CONTAINER {
    DWORD EntriesRead;
    DFS_INFO_300 *Buffer;
} DFS_INFO_300_CONTAINER;
typedef struct _DFS_INFO_ENUM_STRUCT {
    DWORD Level;
    union {
        DFS_INFO_1_CONTAINER *DfsInfo1Container;
        DFS_INFO_2_CONTAINER *DfsInfo2Container;
        DFS_INFO_3_CONTAINER *DfsInfo3Container;
        DFS_INFO_4_CONTAINER *DfsInfo4Container;
        DFS_INFO_5_CONTAINER *DfsInfo5Container;
        DFS_INFO_6_CONTAINER *DfsInfo6Container;
        DFS_INFO_8_CONTAINER *DfsInfo8Container;
        DFS_INFO_9_CONTAINER *DfsInfo9Container;
        DFS_INFO_200_CONTAINER *DfsInfo200Container;
        DFS_INFO_300_CONTAINER *DfsInfo300Container;
    } DfsInfoContainer;
} DFS_INFO_ENUM_STRUCT;
/*****************************************************************************
 * netdfs interface (v3.0)
 */
#ifndef __netdfs_INTERFACE_DEFINED__
#define __netdfs_INTERFACE_DEFINED__

extern handle_t netdfs_hBinding;
extern RPC_IF_HANDLE netdfs_v3_0_c_ifspec;
extern RPC_IF_HANDLE netdfs_v3_0_s_ifspec;
DWORD __stdcall NetrDfsManagerGetVersion(
    void);

NET_API_STATUS __stdcall NetrDfsAdd(
    WCHAR *DfsEntryPath,
    WCHAR *ServerName,
    WCHAR *ShareName,
    WCHAR *Comment,
    DWORD Flags);

NET_API_STATUS __stdcall NetrDfsRemove(
    WCHAR *DfsEntryPath,
    WCHAR *ServerName,
    WCHAR *ShareName);

NET_API_STATUS __stdcall NetrDfsSetInfo(
    WCHAR *DfsEntryPath,
    WCHAR *ServerName,
    WCHAR *ShareName,
    DWORD Level,
    DFS_INFO_STRUCT *DfsInfo);

NET_API_STATUS __stdcall NetrDfsGetInfo(
    WCHAR *DfsEntryPath,
    WCHAR *ServerName,
    WCHAR *ShareName,
    DWORD Level,
    DFS_INFO_STRUCT *DfsInfo);

NET_API_STATUS __stdcall NetrDfsEnum(
    DWORD Level,
    DWORD PrefMaxLen,
    DFS_INFO_ENUM_STRUCT *DfsEnum,
    DWORD *ResumeHandle);

NET_API_STATUS __stdcall NetrDfsRename(
    WCHAR *DfsEntryPath,
    WCHAR *NewDfsEntryPath,
    ULONG Flags);

void __stdcall NetrDfsMove(
    void);

void __stdcall NetrDfsManagerGetConfigInfo(
    void);

void __stdcall NetrDfsManagerSendSiteInfo(
    void);

NET_API_STATUS __stdcall NetrDfsAddFtRoot(
    WCHAR *ServerName,
    WCHAR *DcName,
    WCHAR *RootShare,
    WCHAR *FtDfsName,
    WCHAR *Comment,
    WCHAR *ConfigDN,
    BOOLEAN NewFtDfs,
    DWORD ApiFlags,
    DFSM_ROOT_LIST **ppRootList);

NET_API_STATUS __stdcall NetrDfsRemoveFtRoot(
    WCHAR *ServerName,
    WCHAR *DcName,
    WCHAR *RootShare,
    WCHAR *FtDfsName,
    DWORD ApiFlags,
    DFSM_ROOT_LIST **ppRootList);

NET_API_STATUS __stdcall NetrDfsAddStdRoot(
    WCHAR *ServerName,
    WCHAR *RootShare,
    WCHAR *Comment,
    DWORD ApiFlags);

NET_API_STATUS __stdcall NetrDfsRemoveStdRoot(
    WCHAR *ServerName,
    WCHAR *RootShare,
    DWORD ApiFlags);

NET_API_STATUS __stdcall NetrDfsManagerInitialize(
    WCHAR *ServerName,
    DWORD Flags);

NET_API_STATUS __stdcall NetrDfsAddStdRootForced(
    WCHAR *ServerName,
    WCHAR *RootShare,
    WCHAR *Comment,
    WCHAR *Share);

NET_API_STATUS __stdcall NetrDfsGetDcAddress(
    WCHAR *ServerName,
    WCHAR **DcName,
    BOOLEAN *IsRoot,
    ULONG *Timeout);

NET_API_STATUS __stdcall NetrDfsSetDcAddress(
    WCHAR *ServerName,
    WCHAR *DcName,
    DWORD Timeout,
    DWORD Flags);

NET_API_STATUS __stdcall NetrDfsFlushFtTable(
    WCHAR *DcName,
    WCHAR *wszFtDfsName);

NET_API_STATUS __stdcall NetrDfsAdd2(
    WCHAR *DfsEntryPath,
    WCHAR *DcName,
    WCHAR *ServerName,
    WCHAR *ShareName,
    WCHAR *Comment,
    DWORD Flags,
    DFSM_ROOT_LIST **ppRootList);

NET_API_STATUS __stdcall NetrDfsRemove2(
    WCHAR *DfsEntryPath,
    WCHAR *DcName,
    WCHAR *ServerName,
    WCHAR *ShareName,
    DFSM_ROOT_LIST **ppRootList);

NET_API_STATUS __stdcall NetrDfsEnumEx(
    WCHAR *DfsEntryPath,
    DWORD Level,
    DWORD PrefMaxLen,
    DFS_INFO_ENUM_STRUCT *DfsEnum,
    DWORD *ResumeHandle);

NET_API_STATUS __stdcall NetrDfsSetInfo2(
    WCHAR *DfsEntryPath,
    WCHAR *DcName,
    WCHAR *ServerName,
    WCHAR *ShareName,
    DWORD Level,
    DFS_INFO_STRUCT *pDfsInfo,
    DFSM_ROOT_LIST **ppRootList);

NET_API_STATUS __stdcall NetrDfsAddRootTarget(
    LPWSTR pDfsPath,
    LPWSTR pTargetPath,
    ULONG MajorVersion,
    LPWSTR pComment,
    BOOLEAN NewNamespace,
    ULONG Flags);

NET_API_STATUS __stdcall NetrDfsRemoveRootTarget(
    LPWSTR pDfsPath,
    LPWSTR pTargetPath,
    ULONG Flags);

NET_API_STATUS __stdcall NetrDfsGetSupportedNamespaceVersion(
    DFS_NAMESPACE_VERSION_ORIGIN Origin,
    NETDFS_SERVER_OR_DOMAIN_HANDLE pName,
    PDFS_SUPPORTED_NAMESPACE_VERSION_INFO pVersionInfo);


#endif  /* __netdfs_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __netdfs_c_h__ */
