/*** Autogenerated by WIDL <undefined version> from C:/proj/reactos/sdk/include/reactos/idl/dnsrslvr.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __dnsrslvr_c_h__
#define __dnsrslvr_c_h__

/* Forward declarations */

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

#ifndef _DTYP_IDL
#define _DTYP_IDL
#ifndef _WINDEF_H
typedef int BOOL;
typedef int *PBOOL;
typedef int *LPBOOL;
typedef unsigned char BYTE;
typedef unsigned char *PBYTE;
typedef unsigned char *LPBYTE;
typedef ULONG DWORD;
typedef ULONG *PDWORD;
typedef ULONG *LPDWORD;
#endif
#ifndef _BASETSD_H_
typedef unsigned int DWORD32;
typedef UINT64 DWORD64;
#endif
#ifndef _WINDEF_H
typedef int INT;
typedef int *LPINT;
#endif
#ifndef _BASETSD_H_
typedef signed char INT8;
typedef signed short INT16;
typedef signed int INT32;
typedef INT64 INT64;
#endif
#ifndef _BASETSD_H_
typedef signed int LONG32;
typedef INT64 LONG64;
#endif
typedef UINT64 QWORD;
#ifndef _WINNT_
typedef short SHORT;
#endif
typedef INT64 TIME;
#ifndef _WINNT_
typedef char CHAR;
typedef char *PCHAR;
typedef unsigned char UCHAR;
typedef unsigned char *PUCHAR;
#endif
#ifndef _WINDEF_H
typedef unsigned int UINT;
#endif
#ifndef _BASETSD_H_
typedef unsigned char UINT8;
typedef unsigned short UINT16;
typedef unsigned int UINT32;
typedef UINT64 UINT64;
#endif
#ifndef _WINNT_
typedef ULONG ULONG;
typedef ULONG *PULONG;
#endif
#ifndef _BASETSD_H_
typedef unsigned int ULONG32;
typedef UINT64 ULONG64;
#endif
#ifndef _WINNT_
typedef UINT64 ULONGLONG;
typedef unsigned short USHORT;
#endif
#ifndef _WINDEF_H
typedef unsigned short WORD;
typedef unsigned short *PWORD;
typedef unsigned short *LPWORD;
#endif
#ifndef _WINNT_
typedef LONG LONG;
typedef LONG *PLONG;
#endif
#ifndef _WINDEF_H
typedef LONG *LPLONG;
#endif
#ifndef _WINNT_
typedef INT64 LONGLONG;
#endif
#ifndef _WINDEF_H
typedef float FLOAT;
#endif
#ifndef __wtypes_h__
typedef double DOUBLE;
#endif
#ifndef _WINNT_
typedef BYTE BOOLEAN;
typedef BYTE *PBOOLEAN;
#endif
#ifndef _BASETSD_H_
typedef LONG LONG_PTR;
typedef ULONG ULONG_PTR;
typedef ULONG_PTR SIZE_T;
typedef ULONG_PTR DWORD_PTR;
#endif
typedef DWORD NET_API_STATUS;
#ifndef _WINNT_
typedef ULONGLONG DWORDLONG;
typedef ULONGLONG *PDWORDLONG;
#endif
typedef DWORD HCALL;
#ifndef _WINNT_
typedef void *HANDLE;
typedef void *PVOID;
#endif
#ifndef __WINE_RPCDCE_H
typedef void *RPC_BINDING_HANDLE;
#endif
typedef void *PCONTEXT_HANDLE;
typedef PCONTEXT_HANDLE *PPCONTEXT_HANDLE;
#ifndef _WINNT_
typedef wchar_t WCHAR;
typedef wchar_t *PWCHAR;
#if 0
typedef wchar_t UNICODE;
#endif
typedef const char *LPCSTR;
typedef const wchar_t *LPCWSTR;
typedef char *PSTR;
typedef char *LPSTR;
typedef wchar_t *LPWSTR;
typedef wchar_t *PWSTR;
#endif
typedef const wchar_t *LMCSTR;
typedef WCHAR *LMSTR;
#ifndef __wtypes_h__
typedef WCHAR *BSTR;
#endif
#if 0
typedef LPCSTR LPCTSTR;
typedef LPSTR LPTSTR;
typedef CHAR TCHAR;
#endif
#if 0
typedef struct _FILETIME {
    DWORD dwLowDateTime;
    DWORD dwHighDateTime;
} FILETIME;
typedef struct _FILETIME *PFILETIME;
typedef struct _FILETIME *LPFILETIME;
typedef struct _GUID {
    DWORD Data1;
    WORD Data2;
    WORD Data3;
    BYTE Data4[8];
} GUID;
typedef struct _GUID UUID;
typedef struct _GUID *PGUID;
typedef struct _LARGE_INTEGER {
    LONGLONG QuadPart;
} LARGE_INTEGER;
typedef struct _LARGE_INTEGER *PLARGE_INTEGER;
typedef DWORD LCID;
#endif
typedef struct _RPC_UNICODE_STRING {
    USHORT Length;
    USHORT MaximumLength;
    LPWSTR Buffer;
} RPC_UNICODE_STRING;
typedef struct _RPC_UNICODE_STRING *PRPC_UNICODE_STRING;
#if 0
typedef struct _SYSTEMTIME {
    WORD wYear;
    WORD wMonth;
    WORD wDayOfWeek;
    WORD wDay;
    WORD wHour;
    WORD wMinute;
    WORD wSecond;
    WORD wMilliseconds;
} SYSTEMTIME;
typedef struct _SYSTEMTIME *PSYSTEMTIME;
typedef struct _UINT128 {
    UINT64 lower;
    UINT64 upper;
} UINT128;
typedef struct _UINT128 *PUINT128;
typedef struct _ULARGE_INTEGER {
    ULONGLONG QuadPart;
} ULARGE_INTEGER;
typedef struct _ULARGE_INTEGER *PULARGE_INTEGER;
#endif
#if 0
typedef struct _SID_IDENTIFIER_AUTHORITY {
    BYTE Value[6];
} SID_IDENTIFIER_AUTHORITY;
typedef struct _SID {
    BYTE Revision;
    BYTE SubAuthorityCount;
    SID_IDENTIFIER_AUTHORITY IdentifierAuthority;
    DWORD SubAuthority[1];
} SID;
typedef struct _SID *PSID;
typedef struct _ACCESS_MASK {
    DWORD ACCESS_MASK;
} ACCESS_MASK;
typedef struct _ACCESS_MASK *PACCESS_MASK;
typedef struct _ACE_HEADER {
    UCHAR AceType;
    UCHAR AceFlags;
    USHORT AceSize;
} ACE_HEADER;
typedef struct _ACE_HEADER *PACE_HEADER;
typedef struct _ACCESS_ALLOWED_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} ACCESS_ALLOWED_ACE;
typedef struct _ACCESS_ALLOWED_ACE *PACCESS_ALLOWED_ACE;
typedef struct _ACCESS_ALLOWED_OBJECT_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD Flags;
    GUID ObjectType;
    GUID InheritedObjectType;
    DWORD SidStart;
} ACCESS_ALLOWED_OBJECT_ACE;
typedef struct _ACCESS_ALLOWED_OBJECT_ACE *PACCESS_ALLOWED_OBJECT_ACE;
typedef struct _ACCESS_DENIED_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} ACCESS_DENIED_ACE;
typedef struct _ACCESS_DENIED_ACE *PACCESS_DENIED_ACE;
typedef struct _ACCESS_ALLOWED_CALLBACK_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} ACCESS_ALLOWED_CALLBACK_ACE;
typedef struct _ACCESS_ALLOWED_CALLBACK_ACE *PACCESS_ALLOWED_CALLBACK_ACE;
typedef struct _ACCESS_DENIED_CALLBACK_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} ACCESS_DENIED_CALLBACK_ACE;
typedef struct _ACCESS_DENIED_CALLBACK_ACE *PACCESS_DENIED_CALLBACK_ACE;
typedef struct _ACCESS_ALLOWED_CALLBACK_OBJECT_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD Flags;
    GUID ObjectType;
    GUID InheritedObjectType;
    DWORD SidStart;
} ACCESS_ALLOWED_CALLBACK_OBJECT_ACE;
typedef struct _ACCESS_ALLOWED_CALLBACK_OBJECT_ACE *PACCESS_ALLOWED_CALLBACK_OBJECT_ACE;
typedef struct _ACCESS_DENIED_CALLBACK_OBJECT_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD Flags;
    GUID ObjectType;
    GUID InheritedObjectType;
    DWORD SidStart;
} ACCESS_DENIED_CALLBACK_OBJECT_ACE;
typedef struct _ACCESS_DENIED_CALLBACK_OBJECT_ACE *PACCESS_DENIED_CALLBACK_OBJECT_ACE;
typedef struct _SYSTEM_AUDIT_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} SYSTEM_AUDIT_ACE;
typedef struct _SYSTEM_AUDIT_ACE *PSYSTEM_AUDIT_ACE;
typedef struct _SYSTEM_AUDIT_CALLBACK_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} SYSTEM_AUDIT_CALLBACK_ACE;
typedef struct _SYSTEM_AUDIT_CALLBACK_ACE *PSYSTEM_AUDIT_CALLBACK_ACE;
typedef struct _SYSTEM_MANDATORY_LABEL_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} SYSTEM_MANDATORY_LABEL_ACE;
typedef struct _SYSTEM_MANDATORY_LABEL_ACE *PSYSTEM_MANDATORY_LABEL_ACE;
typedef struct _SYSTEM_AUDIT_CALLBACK_OBJECT_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD Flags;
    GUID ObjectType;
    GUID InheritedObjectType;
    DWORD SidStart;
} SYSTEM_AUDIT_CALLBACK_OBJECT_ACE;
typedef struct _SYSTEM_AUDIT_CALLBACK_OBJECT_ACE *PSYSTEM_AUDIT_CALLBACK_OBJECT_ACE;
typedef struct _ACL {
    UCHAR AclRevision;
    UCHAR Sbz1;
    USHORT AclSize;
    USHORT AceCount;
    USHORT Sbz2;
} ACL;
typedef struct _ACL *PACL;
typedef struct _SECURITY_DESCRIPTOR {
    UCHAR Revision;
    UCHAR Sbz1;
    USHORT Control;
    ULONG Owner;
    ULONG Group;
    ULONG Sacl;
    ULONG Dacl;
} SECURITY_DESCRIPTOR;
typedef struct _SECURITY_DESCRIPTOR *PSECURITY_DESCRIPTOR;
typedef DWORD SECURITY_INFORMATION;
typedef DWORD *PSECURITY_INFORMATION;
#endif
typedef struct _RPC_SID {
    UCHAR Revision;
    UCHAR SubAuthorityCount;
    SID_IDENTIFIER_AUTHORITY IdentifierAuthority;
    DWORD SubAuthority[1];
} RPC_SID;
typedef struct _RPC_SID *PRPC_SID;
#endif /* _DTYP_IDL */
#ifndef _WINDNS_INCLUDED_
typedef DWORD IP4_ADDRESS;
typedef DWORD DNS_STATUS;
typedef enum _DNS_CHARSET {
    DnsCharSetUnknown = 0,
    DnsCharSetUnicode = 1ul,
    DnsCharSetUtf8 = 2ul,
    DnsCharSetAnsi = 3ul
} DNS_CHARSET;
typedef enum __WIDL_dnsrslvr_generated_name_00000000 {
    DnsConfigPrimaryDomainName_W = 0,
    DnsConfigPrimaryDomainName_A = 1ul,
    DnsConfigPrimaryDomainName_UTF8 = 2ul,
    DnsConfigAdapterDomainName_W = 3ul,
    DnsConfigAdapterDomainName_A = 4ul,
    DnsConfigAdapterDomainName_UTF8 = 5ul,
    DnsConfigDnsServerList = 6ul,
    DnsConfigSearchList = 7ul,
    DnsConfigAdapterInfo = 8ul,
    DnsConfigPrimaryHostNameRegistrationEnabled = 9ul,
    DnsConfigAdapterHostNameRegistrationEnabled = 10ul,
    DnsConfigAddressRegistrationMaxCount = 11ul,
    DnsConfigHostName_W = 12ul,
    DnsConfigHostName_A = 13ul,
    DnsConfigHostName_UTF8 = 14ul,
    DnsConfigFullHostName_W = 15ul,
    DnsConfigFullHostName_A = 16ul,
    DnsConfigFullHostName_UTF8 = 17ul
} DNS_CONFIG_TYPE;
typedef enum __WIDL_dnsrslvr_generated_name_00000001 {
    DnsFreeFlat = 0,
    DnsFreeRecordList = 1ul,
    DnsFreeParsedMessageFields = 2ul
} DNS_FREE_TYPE;
typedef enum _DNS_NAME_FORMAT {
    DnsNameDomain = 0,
    DnsNameDomainLabel = 1ul,
    DnsNameHostnameFull = 2ul,
    DnsNameHostnameLabel = 3ul,
    DnsNameWildcard = 4ul,
    DnsNameSrvRecord = 5ul
} DNS_NAME_FORMAT;
typedef enum __WIDL_dnsrslvr_generated_name_00000002 {
    DnsSectionQuestion = 0,
    DnsSectionAnswer = 1ul,
    DnsSectionAuthority = 2ul,
    DnsSectionAdditional = 3ul
} DNS_SECTION;
typedef struct _IP4_ARRAY {
    DWORD AddrCount;
    IP4_ADDRESS AddrArray[1];
} IP4_ARRAY;
typedef struct _IP4_ARRAY *PIP4_ARRAY;
typedef struct __WIDL_dnsrslvr_generated_name_00000003 {
    DWORD IP6Dword[4];
} IP6_ADDRESS;
typedef struct __WIDL_dnsrslvr_generated_name_00000003 *PIP6_ADDRESS;
typedef struct __WIDL_dnsrslvr_generated_name_00000003 DNS_IP6_ADDRESS;
typedef struct __WIDL_dnsrslvr_generated_name_00000003 *PDNS_IP6_ADDRESS;
typedef struct _DnsAddr {
    CHAR MaxSa[32];
    DWORD DnsAddrUserDword[8];
} DNS_ADDR;
typedef struct _DnsAddr *PDNS_ADDR;
typedef struct _DnsAddrArray {
    DWORD MaxCount;
    DWORD AddrCount;
    DWORD Tag;
    WORD Family;
    WORD WordReserved;
    DWORD Flags;
    DWORD MatchFlag;
    DWORD Reserved1;
    DWORD Reserved2;
    DNS_ADDR AddrArray[1];
} DNS_ADDR_ARRAY;
typedef struct _DnsAddrArray *PDNS_ADDR_ARRAY;
typedef struct _DNS_HEADER {
    WORD Xid;
    BYTE RecursionDesired : 1;
    BYTE Truncation : 1;
    BYTE Authoritative : 1;
    BYTE Opcode : 4;
    BYTE IsResponse : 1;
    BYTE ResponseCode : 4;
    BYTE CheckingDisabled : 1;
    BYTE AuthenticatedData : 1;
    BYTE Reserved : 1;
    BYTE RecursionAvailable : 1;
    WORD QuestionCount;
    WORD AnswerCount;
    WORD NameServerCount;
    WORD AdditionalCount;
} DNS_HEADER;
typedef struct _DNS_HEADER *PDNS_HEADER;
typedef struct _DNS_WIRE_QUESTION {
    WORD QuestionType;
    WORD QuestionClass;
} DNS_WIRE_QUESTION;
typedef struct _DNS_WIRE_QUESTION *PDNS_WIRE_QUESTION;
typedef struct _DNS_WIRE_RECORD {
    WORD RecordType;
    WORD RecordClass;
    DWORD TimeToLive;
    WORD DataLength;
} DNS_WIRE_RECORD;
typedef struct _DNS_WIRE_RECORD *PDNS_WIRE_RECORD;
typedef struct _DNS_MESSAGE_BUFFER {
    DNS_HEADER MessageHead;
    CHAR MessageBody[1];
} DNS_MESSAGE_BUFFER;
typedef struct _DNS_MESSAGE_BUFFER *PDNS_MESSAGE_BUFFER;
typedef struct _DnsRecordFlags {
    DWORD Section : 2;
    DWORD Delete : 1;
    DWORD CharSet : 2;
    DWORD Unused : 3;
    DWORD Reserved : 24;
} DNS_RECORD_FLAGS;
typedef struct __WIDL_dnsrslvr_generated_name_00000004 {
    IP4_ADDRESS IpAddress;
} DNS_A_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000004 *PDNS_A_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000005 {
    DNS_IP6_ADDRESS Ip6Address;
} DNS_AAAA_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000005 *PDNS_AAAA_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000006 {
    BYTE AddressType;
    BYTE Address[20];
} DNS_ATMA_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000006 *PDNS_ATMA_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000007 {
    WORD wFlags;
    BYTE chProtocol;
    BYTE chAlgorithm;
    BYTE Key[1];
} DNS_KEY_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000007 *PDNS_KEY_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000008 {
    WORD wVersion;
    WORD wSize;
    WORD wHorPrec;
    WORD wVerPrec;
    DWORD dwLatitude;
    DWORD dwLongitude;
    DWORD dwAltitude;
} DNS_LOC_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000008 *PDNS_LOC_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000009 {
    LPSTR pNameMailbox;
    LPSTR pNameErrorsMailbox;
} DNS_MINFO_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000009 *PDNS_MINFO_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_0000000A {
    LPWSTR pNameMailbox;
    LPWSTR pNameErrorsMailbox;
} DNS_MINFO_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_0000000A *PDNS_MINFO_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_0000000B {
    LPSTR pNameExchange;
    WORD wPreference;
    WORD Pad;
} DNS_MX_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_0000000B *PDNS_MX_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_0000000C {
    LPWSTR pNameExchange;
    WORD wPreference;
    WORD Pad;
} DNS_MX_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_0000000C *PDNS_MX_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_0000000D {
    DWORD dwByteCount;
    BYTE Data[1];
} DNS_NULL_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_0000000D *PDNS_NULL_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_0000000E {
    LPSTR pNameNext;
    WORD wNumTypes;
    WORD wTypes[1];
} DNS_NXT_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_0000000E *PDNS_NXT_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_0000000F {
    LPWSTR pNameNext;
    WORD wNumTypes;
    WORD wTypes[1];
} DNS_NXT_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_0000000F *PDNS_NXT_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000010 {
    LPSTR pNameHost;
} DNS_PTR_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000010 *PDNS_PTR_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000011 {
    LPWSTR pNameHost;
} DNS_PTR_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000011 *PDNS_PTR_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000012 {
    LPSTR pNameSigner;
    WORD wTypeCovered;
    BYTE chAlgorithm;
    BYTE chLabelCount;
    DWORD dwOriginalTtl;
    DWORD dwExpiration;
    DWORD dwTimeSigned;
    WORD wKeyTag;
    WORD Pad;
    BYTE Signature[1];
} DNS_SIG_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000012 *PDNS_SIG_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000013 {
    LPWSTR pNameSigner;
    WORD wTypeCovered;
    BYTE chAlgorithm;
    BYTE chLabelCount;
    DWORD dwOriginalTtl;
    DWORD dwExpiration;
    DWORD dwTimeSigned;
    WORD wKeyTag;
    WORD Pad;
    BYTE Signature[1];
} DNS_SIG_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000013 *PDNS_SIG_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000014 {
    LPSTR pNamePrimaryServer;
    LPSTR pNameAdministrator;
    DWORD dwSerialNo;
    DWORD dwRefresh;
    DWORD dwRetry;
    DWORD dwExpire;
    DWORD dwDefaultTtl;
} DNS_SOA_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000014 *PDNS_SOA_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000015 {
    LPWSTR pNamePrimaryServer;
    LPWSTR pNameAdministrator;
    DWORD dwSerialNo;
    DWORD dwRefresh;
    DWORD dwRetry;
    DWORD dwExpire;
    DWORD dwDefaultTtl;
} DNS_SOA_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000015 *PDNS_SOA_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000016 {
    LPSTR pNameTarget;
    WORD wPriority;
    WORD wWeight;
    WORD wPort;
    WORD Pad;
} DNS_SRV_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000016 *PDNS_SRV_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000017 {
    LPWSTR pNameTarget;
    WORD wPriority;
    WORD wWeight;
    WORD wPort;
    WORD Pad;
} DNS_SRV_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000017 *PDNS_SRV_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000018 {
    DWORD dwStringCount;
    LPSTR pStringArray[1];
} DNS_TXT_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000018 *PDNS_TXT_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000019 {
    DWORD dwStringCount;
    LPWSTR pStringArray[1];
} DNS_TXT_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000019 *PDNS_TXT_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_0000001A {
    LPSTR pNameAlgorithm;
    PBYTE pAlgorithmPacket;
    PBYTE pKey;
    PBYTE pOtherData;
    DWORD dwCreateTime;
    DWORD dwExpireTime;
    WORD wMode;
    WORD wError;
    WORD wKeyLength;
    WORD wOtherLength;
    UCHAR cAlgNameLength;
    BOOL bPacketPointers;
} DNS_TKEY_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_0000001A *PDNS_TKEY_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_0000001B {
    LPWSTR pNameAlgorithm;
    PBYTE pAlgorithmPacket;
    PBYTE pKey;
    PBYTE pOtherData;
    DWORD dwCreateTime;
    DWORD dwExpireTime;
    WORD wMode;
    WORD wError;
    WORD wKeyLength;
    WORD wOtherLength;
    UCHAR cAlgNameLength;
    BOOL bPacketPointers;
} DNS_TKEY_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_0000001B *PDNS_TKEY_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_0000001C {
    LPSTR pNameAlgorithm;
    PBYTE pAlgorithmPacket;
    PBYTE pSignature;
    PBYTE pOtherData;
    LONGLONG i64CreateTime;
    WORD wFudgeTime;
    WORD wOriginalXid;
    WORD wError;
    WORD wSigLength;
    WORD wOtherLength;
    UCHAR cAlgNameLength;
    BOOL bPacketPointers;
} DNS_TSIG_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_0000001C *PDNS_TSIG_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_0000001D {
    LPWSTR pNameAlgorithm;
    PBYTE pAlgorithmPacket;
    PBYTE pSignature;
    PBYTE pOtherData;
    LONGLONG i64CreateTime;
    WORD wFudgeTime;
    WORD wOriginalXid;
    WORD wError;
    WORD wSigLength;
    WORD wOtherLength;
    UCHAR cAlgNameLength;
    BOOL bPacketPointers;
} DNS_TSIG_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_0000001D *PDNS_TSIG_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_0000001E {
    DWORD dwMappingFlag;
    DWORD dwLookupTimeout;
    DWORD dwCacheTimeout;
    DWORD cWinsServerCount;
    IP4_ADDRESS WinsServers[1];
} DNS_WINS_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_0000001E *PDNS_WINS_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_0000001F {
    DWORD dwMappingFlag;
    DWORD dwLookupTimeout;
    DWORD dwCacheTimeout;
    LPSTR pNameResultDomain;
} DNS_WINSR_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_0000001F *PDNS_WINSR_DATAA;
typedef struct __WIDL_dnsrslvr_generated_name_00000020 {
    DWORD dwMappingFlag;
    DWORD dwLookupTimeout;
    DWORD dwCacheTimeout;
    LPWSTR pNameResultDomain;
} DNS_WINSR_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000020 *PDNS_WINSR_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000021 {
    IP4_ADDRESS IpAddress;
    UCHAR chProtocol;
    BYTE BitMask[1];
} DNS_WKS_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000021 *PDNS_WKS_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000022 {
    WORD wKeyTag;
    BYTE chAlgorithm;
    BYTE chDigestType;
    WORD wDigestLength;
    WORD wPad;
    BYTE Digest[1];
} DNS_DS_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000023 {
    LPWSTR pNextDomainName;
    WORD wTypeBitMapsLength;
    WORD wPad;
    BYTE TypeBitMaps[1];
} DNS_NSEC_DATAW;
typedef struct __WIDL_dnsrslvr_generated_name_00000024 {
    WORD wFlags;
    BYTE chProtocol;
    BYTE chAlgorithm;
    WORD wKeyLength;
    WORD wPad;
    BYTE Key[1];
} DNS_DNSKEY_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000025 {
    WORD wDataLength;
    WORD wPad;
    BYTE Data[1];
} DNS_OPT_DATA;
typedef struct __WIDL_dnsrslvr_generated_name_00000026 {
    WORD wTypeCovered;
    BYTE chAlgorithm;
    BYTE chLabelCount;
    DWORD dwOriginalTtl;
    DWORD dwExpiration;
    DWORD dwTimeSigned;
    WORD wKeyTag;
    WORD Pad;
    LPWSTR pNameSigner;
    BYTE Signature[1];
} DNS_RRSIG_DATAW;
typedef union DNS_DATAW {
    DNS_A_DATA A;
    DNS_SOA_DATAW SOA;
    DNS_PTR_DATAW PTR;
    DNS_PTR_DATAW NS;
    DNS_PTR_DATAW CNAME;
    DNS_PTR_DATAW MB;
    DNS_PTR_DATAW MD;
    DNS_PTR_DATAW MF;
    DNS_PTR_DATAW MG;
    DNS_PTR_DATAW MR;
    DNS_MINFO_DATAW MINFO;
    DNS_MINFO_DATAW RP;
    DNS_MX_DATAW MX;
    DNS_MX_DATAW AFSDB;
    DNS_MX_DATAW RT;
    DNS_AAAA_DATA AAAA;
    DNS_SRV_DATAW SRV;
    DNS_ATMA_DATA ATMA;
    DNS_DS_DATA DS;
    DNS_RRSIG_DATAW RRSIG;
    DNS_NSEC_DATAW NSEC;
    DNS_DNSKEY_DATA DNSKEY;
    DNS_OPT_DATA OPT;
} DNS_DATAW;
typedef struct _DnsRecordW {
    struct _DnsRecordW *pNext;
    LPWSTR pName;
    WORD wType;
    WORD wDataLength;
    DWORD Flags;
    DWORD dwTtl;
    DWORD dwReserved;
    DNS_DATAW Data;
} DNS_RECORDW;
typedef struct _DnsRecordW *PDNS_RECORDW;
typedef struct _DnsRRSet {
    PDNS_RECORDW pFirstRR;
    PDNS_RECORDW pLastRR;
} DNS_RRSET;
typedef struct _DnsRRSet *PDNS_RRSET;
#endif
#ifndef _WINDNS_UNDOC_H_
typedef struct _DNS_CACHE_ENTRY {
    struct _DNS_CACHE_ENTRY *pNext;
    PWSTR pszName;
    unsigned short wType1;
    unsigned short wType2;
    unsigned short wFlags;
} DNS_CACHE_ENTRY;
typedef struct _DNS_CACHE_ENTRY *PDNS_CACHE_ENTRY;
#endif
typedef LPWSTR DNSRSLVR_HANDLE;
/*****************************************************************************
 * DnsResolver interface (v2.0)
 */
#ifndef __DnsResolver_INTERFACE_DEFINED__
#define __DnsResolver_INTERFACE_DEFINED__

extern RPC_IF_HANDLE DnsResolver_v2_0_c_ifspec;
extern RPC_IF_HANDLE DnsResolver_v2_0_s_ifspec;
DWORD __stdcall CRrReadCache(
    DNSRSLVR_HANDLE pwszServerName,
    DNS_CACHE_ENTRY **ppCacheEntries);

DWORD __stdcall R_ResolverFlushCache(
    DNSRSLVR_HANDLE pwszServerName);

DWORD __stdcall R_ResolverFlushCacheEntry(
    DNSRSLVR_HANDLE pwszServerName,
    LPCWSTR pszName,
    WORD wType);

DWORD __stdcall R_ResolverQuery(
    DNSRSLVR_HANDLE pwszServerName,
    LPCWSTR pwsName,
    WORD wType,
    DWORD Flags,
    DWORD *dwRecords,
    DNS_RECORDW **ppResultRecords);


#endif  /* __DnsResolver_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

handle_t __RPC_USER DNSRSLVR_HANDLE_bind(DNSRSLVR_HANDLE);
void __RPC_USER DNSRSLVR_HANDLE_unbind(DNSRSLVR_HANDLE, handle_t);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __dnsrslvr_c_h__ */
