/*** Autogenerated by WIDL <undefined version> from dcom.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __dcom_h__
#define __dcom_h__

/* Forward declarations */

#ifndef __IRemUnknown_FWD_DEFINED__
#define __IRemUnknown_FWD_DEFINED__
typedef interface IRemUnknown IRemUnknown;
#ifdef __cplusplus
interface IRemUnknown;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <unknwn.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * ObjectRpcBaseTypes interface (v0.0)
 */
#ifndef __ObjectRpcBaseTypes_INTERFACE_DEFINED__
#define __ObjectRpcBaseTypes_INTERFACE_DEFINED__

extern RPC_IF_HANDLE ObjectRpcBaseTypes_v0_0_c_ifspec;
extern RPC_IF_HANDLE ObjectRpcBaseTypes_v0_0_s_ifspec;
typedef MIDL_uhyper ID;
typedef ID MID;
typedef ID OXID;
typedef ID OID;
typedef ID SETID;
typedef GUID IPID;
typedef GUID CID;
typedef REFGUID REFIPID;
#define COM_MINOR_VERSION_1 (1)

#define COM_MINOR_VERSION_2 (2)

#define COM_MAJOR_VERSION (5)

#define COM_MINOR_VERSION (3)

typedef struct tagCOMVERSION {
    unsigned short MajorVersion;
    unsigned short MinorVersion;
} COMVERSION;
#define ORPCF_NULL (0)

#define ORPCF_LOCAL (1)

#define ORPCF_RESERVED1 (2)

#define ORPCF_RESERVED2 (4)

#define ORPCF_RESERVED3 (8)

#define ORPCF_RESERVED4 (16)

typedef struct tagORPC_EXTENT {
    GUID id;
    ULONG size;
    byte data[1];
} ORPC_EXTENT;
typedef struct tagORPC_EXTENT_ARRAY {
    ULONG size;
    ULONG reserved;
    ORPC_EXTENT **extent;
} ORPC_EXTENT_ARRAY;
typedef struct tagORPCTHIS {
    COMVERSION version;
    ULONG flags;
    ULONG reserved1;
    CID cid;
    ORPC_EXTENT_ARRAY *extensions;
} ORPCTHIS;
typedef struct tagORPCTHAT {
    ULONG flags;
    ORPC_EXTENT_ARRAY *extensions;
} ORPCTHAT;
#define NCADG_IP_UDP (0x8)

#define NCACN_IP_TCP (0x7)

#define NCADG_IPX (0xe)

#define NCACN_SPX (0xc)

#define NCACN_NB_NB (0x12)

#define NCACN_NB_IPX (0xd)

#define NCACN_DNET_NSP (0x4)

#define NCACN_HTTP (0x1f)

typedef struct tagSTRINGBINDING {
    unsigned short wTowerId;
    WCHAR aNetworkAddr[1];
} STRINGBINDING;
#define COM_C_AUTHZ_NONE (0xffff)

typedef struct tagSECURITYBINDING {
    unsigned short wAuthnSvc;
    unsigned short wAuthzSvc;
    WCHAR aPrincName[1];
} SECURITYBINDING;
typedef struct tagDUALSTRINGARRAY {
    unsigned short wNumEntries;
    unsigned short wSecurityOffset;
    unsigned short aStringArray[1];
} DUALSTRINGARRAY;
typedef struct tagOXID_INFO {
    DWORD dwTid;
    DWORD dwPid;
    IPID ipidRemUnknown;
    DWORD dwAuthnHint;
    DUALSTRINGARRAY *psa;
} OXID_INFO;
#define OBJREF_SIGNATURE (0x574f454d)

#define OBJREF_STANDARD (0x1)

#define OBJREF_HANDLER (0x2)

#define OBJREF_CUSTOM (0x4)

#define SORF_OXRES1 (0x1)

#define SORF_OXRES2 (0x20)

#define SORF_OXRES3 (0x40)

#define SORF_OXRES4 (0x80)

#define SORF_OXRES5 (0x100)

#define SORF_OXRES6 (0x200)

#define SORF_OXRES7 (0x400)

#define SORF_OXRES8 (0x800)

#define SORF_NULL (0x0)

#define SORF_NOPING (0x1000)

typedef struct tagSTDOBJREF {
    ULONG flags;
    ULONG cPublicRefs;
    OXID oxid;
    OID oid;
    IPID ipid;
} STDOBJREF;
typedef struct tagOBJREF {
    ULONG signature;
    ULONG flags;
    GUID iid;
    union {
        struct OR_STANDARD {
            STDOBJREF std;
            DUALSTRINGARRAY saResAddr;
        } u_standard;
        struct OR_HANDLER {
            STDOBJREF std;
            CLSID clsid;
            DUALSTRINGARRAY saResAddr;
        } u_handler;
        struct OR_CUSTOM {
            CLSID clsid;
            ULONG cbExtension;
            ULONG size;
            byte *pData;
        } u_custom;
    } u_objref;
} OBJREF;
typedef struct tagMInterfacePointer {
    ULONG ulCntData;
    BYTE abData[1];
} MInterfacePointer;
typedef MInterfacePointer *PMInterfacePointer;

#endif  /* __ObjectRpcBaseTypes_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IRemUnknown interface
 */
#ifndef __IRemUnknown_INTERFACE_DEFINED__
#define __IRemUnknown_INTERFACE_DEFINED__

typedef IRemUnknown *LPREMUNKNOWN;
typedef struct tagREMQIRESULT {
    HRESULT hResult;
    STDOBJREF std;
} REMQIRESULT;
typedef struct tagREMINTERFACEREF {
    IPID ipid;
    ULONG cPublicRefs;
    ULONG cPrivateRefs;
} REMINTERFACEREF;
DEFINE_GUID(IID_IRemUnknown, 0x00000131, 0x0000, 0x0000, 0xc0,0x00, 0x00,0x00,0x00,0x00,0x00,0x46);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("00000131-0000-0000-c000-000000000046")
IRemUnknown : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE RemQueryInterface(
        REFIPID ripid,
        ULONG cRefs,
        unsigned short cIids,
        IID *iids,
        REMQIRESULT **ppQIResults) = 0;

    virtual HRESULT STDMETHODCALLTYPE RemAddRef(
        unsigned short cInterfaceRefs,
        REMINTERFACEREF *InterfaceRefs,
        HRESULT *pResults) = 0;

    virtual HRESULT STDMETHODCALLTYPE RemRelease(
        unsigned short cInterfaceRefs,
        REMINTERFACEREF *InterfaceRefs) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IRemUnknown, 0x00000131, 0x0000, 0x0000, 0xc0,0x00, 0x00,0x00,0x00,0x00,0x00,0x46)
#endif
#else
typedef struct IRemUnknownVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IRemUnknown *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IRemUnknown *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IRemUnknown *This);

    /*** IRemUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *RemQueryInterface)(
        IRemUnknown *This,
        REFIPID ripid,
        ULONG cRefs,
        unsigned short cIids,
        IID *iids,
        REMQIRESULT **ppQIResults);

    HRESULT (STDMETHODCALLTYPE *RemAddRef)(
        IRemUnknown *This,
        unsigned short cInterfaceRefs,
        REMINTERFACEREF *InterfaceRefs,
        HRESULT *pResults);

    HRESULT (STDMETHODCALLTYPE *RemRelease)(
        IRemUnknown *This,
        unsigned short cInterfaceRefs,
        REMINTERFACEREF *InterfaceRefs);

    END_INTERFACE
} IRemUnknownVtbl;

interface IRemUnknown {
    CONST_VTBL IRemUnknownVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IRemUnknown_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IRemUnknown_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IRemUnknown_Release(This) (This)->lpVtbl->Release(This)
/*** IRemUnknown methods ***/
#define IRemUnknown_RemQueryInterface(This,ripid,cRefs,cIids,iids,ppQIResults) (This)->lpVtbl->RemQueryInterface(This,ripid,cRefs,cIids,iids,ppQIResults)
#define IRemUnknown_RemAddRef(This,cInterfaceRefs,InterfaceRefs,pResults) (This)->lpVtbl->RemAddRef(This,cInterfaceRefs,InterfaceRefs,pResults)
#define IRemUnknown_RemRelease(This,cInterfaceRefs,InterfaceRefs) (This)->lpVtbl->RemRelease(This,cInterfaceRefs,InterfaceRefs)
#else
/*** IUnknown methods ***/
static inline HRESULT IRemUnknown_QueryInterface(IRemUnknown* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IRemUnknown_AddRef(IRemUnknown* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IRemUnknown_Release(IRemUnknown* This) {
    return This->lpVtbl->Release(This);
}
/*** IRemUnknown methods ***/
static inline HRESULT IRemUnknown_RemQueryInterface(IRemUnknown* This,REFIPID ripid,ULONG cRefs,unsigned short cIids,IID *iids,REMQIRESULT **ppQIResults) {
    return This->lpVtbl->RemQueryInterface(This,ripid,cRefs,cIids,iids,ppQIResults);
}
static inline HRESULT IRemUnknown_RemAddRef(IRemUnknown* This,unsigned short cInterfaceRefs,REMINTERFACEREF *InterfaceRefs,HRESULT *pResults) {
    return This->lpVtbl->RemAddRef(This,cInterfaceRefs,InterfaceRefs,pResults);
}
static inline HRESULT IRemUnknown_RemRelease(IRemUnknown* This,unsigned short cInterfaceRefs,REMINTERFACEREF *InterfaceRefs) {
    return This->lpVtbl->RemRelease(This,cInterfaceRefs,InterfaceRefs);
}
#endif
#endif

#endif


#endif  /* __IRemUnknown_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __dcom_h__ */
