/*** Autogenerated by WIDL <undefined version> from ctffunc.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __ctffunc_h__
#define __ctffunc_h__

/* Forward declarations */

#ifndef __IEnumTfCandidates_FWD_DEFINED__
#define __IEnumTfCandidates_FWD_DEFINED__
typedef interface IEnumTfCandidates IEnumTfCandidates;
#ifdef __cplusplus
interface IEnumTfCandidates;
#endif /* __cplusplus */
#endif

#ifndef __IEnumTfLatticeElements_FWD_DEFINED__
#define __IEnumTfLatticeElements_FWD_DEFINED__
typedef interface IEnumTfLatticeElements IEnumTfLatticeElements;
#ifdef __cplusplus
interface IEnumTfLatticeElements;
#endif /* __cplusplus */
#endif

#ifndef __ITfCandidateList_FWD_DEFINED__
#define __ITfCandidateList_FWD_DEFINED__
typedef interface ITfCandidateList ITfCandidateList;
#ifdef __cplusplus
interface ITfCandidateList;
#endif /* __cplusplus */
#endif

#ifndef __ITfCandidateString_FWD_DEFINED__
#define __ITfCandidateString_FWD_DEFINED__
typedef interface ITfCandidateString ITfCandidateString;
#ifdef __cplusplus
interface ITfCandidateString;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnAdviseText_FWD_DEFINED__
#define __ITfFnAdviseText_FWD_DEFINED__
typedef interface ITfFnAdviseText ITfFnAdviseText;
#ifdef __cplusplus
interface ITfFnAdviseText;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnBalloon_FWD_DEFINED__
#define __ITfFnBalloon_FWD_DEFINED__
typedef interface ITfFnBalloon ITfFnBalloon;
#ifdef __cplusplus
interface ITfFnBalloon;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnConfigure_FWD_DEFINED__
#define __ITfFnConfigure_FWD_DEFINED__
typedef interface ITfFnConfigure ITfFnConfigure;
#ifdef __cplusplus
interface ITfFnConfigure;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnConfigureRegisterEudc_FWD_DEFINED__
#define __ITfFnConfigureRegisterEudc_FWD_DEFINED__
typedef interface ITfFnConfigureRegisterEudc ITfFnConfigureRegisterEudc;
#ifdef __cplusplus
interface ITfFnConfigureRegisterEudc;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnConfigureRegisterWord_FWD_DEFINED__
#define __ITfFnConfigureRegisterWord_FWD_DEFINED__
typedef interface ITfFnConfigureRegisterWord ITfFnConfigureRegisterWord;
#ifdef __cplusplus
interface ITfFnConfigureRegisterWord;
#endif /* __cplusplus */
#endif

#ifndef __ITfFunction_FWD_DEFINED__
#define __ITfFunction_FWD_DEFINED__
typedef interface ITfFunction ITfFunction;
#ifdef __cplusplus
interface ITfFunction;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnGetLinguisticAlternates_FWD_DEFINED__
#define __ITfFnGetLinguisticAlternates_FWD_DEFINED__
typedef interface ITfFnGetLinguisticAlternates ITfFnGetLinguisticAlternates;
#ifdef __cplusplus
interface ITfFnGetLinguisticAlternates;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnGetPreferredTouchKeyboardLayout_FWD_DEFINED__
#define __ITfFnGetPreferredTouchKeyboardLayout_FWD_DEFINED__
typedef interface ITfFnGetPreferredTouchKeyboardLayout ITfFnGetPreferredTouchKeyboardLayout;
#ifdef __cplusplus
interface ITfFnGetPreferredTouchKeyboardLayout;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnGetSAPIObject_FWD_DEFINED__
#define __ITfFnGetSAPIObject_FWD_DEFINED__
typedef interface ITfFnGetSAPIObject ITfFnGetSAPIObject;
#ifdef __cplusplus
interface ITfFnGetSAPIObject;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnLMInternal_FWD_DEFINED__
#define __ITfFnLMInternal_FWD_DEFINED__
typedef interface ITfFnLMInternal ITfFnLMInternal;
#ifdef __cplusplus
interface ITfFnLMInternal;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnLMProcessor_FWD_DEFINED__
#define __ITfFnLMProcessor_FWD_DEFINED__
typedef interface ITfFnLMProcessor ITfFnLMProcessor;
#ifdef __cplusplus
interface ITfFnLMProcessor;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnLangProfileUtil_FWD_DEFINED__
#define __ITfFnLangProfileUtil_FWD_DEFINED__
typedef interface ITfFnLangProfileUtil ITfFnLangProfileUtil;
#ifdef __cplusplus
interface ITfFnLangProfileUtil;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnPlayBack_FWD_DEFINED__
#define __ITfFnPlayBack_FWD_DEFINED__
typedef interface ITfFnPlayBack ITfFnPlayBack;
#ifdef __cplusplus
interface ITfFnPlayBack;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnPropertyUIStatus_FWD_DEFINED__
#define __ITfFnPropertyUIStatus_FWD_DEFINED__
typedef interface ITfFnPropertyUIStatus ITfFnPropertyUIStatus;
#ifdef __cplusplus
interface ITfFnPropertyUIStatus;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnReconversion_FWD_DEFINED__
#define __ITfFnReconversion_FWD_DEFINED__
typedef interface ITfFnReconversion ITfFnReconversion;
#ifdef __cplusplus
interface ITfFnReconversion;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnSearchCandidateProvider_FWD_DEFINED__
#define __ITfFnSearchCandidateProvider_FWD_DEFINED__
typedef interface ITfFnSearchCandidateProvider ITfFnSearchCandidateProvider;
#ifdef __cplusplus
interface ITfFnSearchCandidateProvider;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnShowHelp_FWD_DEFINED__
#define __ITfFnShowHelp_FWD_DEFINED__
typedef interface ITfFnShowHelp ITfFnShowHelp;
#ifdef __cplusplus
interface ITfFnShowHelp;
#endif /* __cplusplus */
#endif

#ifndef __ITfIntegratableCandidateListUIElement_FWD_DEFINED__
#define __ITfIntegratableCandidateListUIElement_FWD_DEFINED__
typedef interface ITfIntegratableCandidateListUIElement ITfIntegratableCandidateListUIElement;
#ifdef __cplusplus
interface ITfIntegratableCandidateListUIElement;
#endif /* __cplusplus */
#endif

#ifndef __ITfLMLattice_FWD_DEFINED__
#define __ITfLMLattice_FWD_DEFINED__
typedef interface ITfLMLattice ITfLMLattice;
#ifdef __cplusplus
interface ITfLMLattice;
#endif /* __cplusplus */
#endif

#ifndef __IUIManagerEventSink_FWD_DEFINED__
#define __IUIManagerEventSink_FWD_DEFINED__
typedef interface IUIManagerEventSink IUIManagerEventSink;
#ifdef __cplusplus
interface IUIManagerEventSink;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <oaidl.h>
#include <msctf.h>
#include <ctfutb.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum __WIDL_ctffunc_generated_name_0000001C {
    STYLE_ACTIVE_SELECTION = 0,
    STYLE_IMPLIED_SELECTION = 0x1
} TfIntegratableCandidateListSelectionStyle;
typedef enum __WIDL_ctffunc_generated_name_0000001D {
    GETIF_RESMGR = 0,
    GETIF_RECOCONTEXT = 0x1,
    GETIF_RECOGNIZER = 0x2,
    GETIF_VOICE = 0x3,
    GETIF_DICTGRAM = 0x4,
    GETIF_RECOGNIZERNOINIT = 0x5
} TfSapiObject;
typedef struct TF_LMLATTELEMENT {
    DWORD dwFrameStart;
    DWORD dwFrameLen;
    DWORD dwFlags;
    __C89_NAMELESS union {
        INT iCost;
    } __C89_NAMELESSUNIONNAME;
    BSTR bstrText;
} TF_LMLATTELEMENT;
EXTERN_C const CLSID CLSID_SapiLayr;
#ifndef __IEnumTfCandidates_FWD_DEFINED__
#define __IEnumTfCandidates_FWD_DEFINED__
typedef interface IEnumTfCandidates IEnumTfCandidates;
#ifdef __cplusplus
interface IEnumTfCandidates;
#endif /* __cplusplus */
#endif

#ifndef __IEnumTfLatticeElements_FWD_DEFINED__
#define __IEnumTfLatticeElements_FWD_DEFINED__
typedef interface IEnumTfLatticeElements IEnumTfLatticeElements;
#ifdef __cplusplus
interface IEnumTfLatticeElements;
#endif /* __cplusplus */
#endif

#ifndef __ITfCandidateList_FWD_DEFINED__
#define __ITfCandidateList_FWD_DEFINED__
typedef interface ITfCandidateList ITfCandidateList;
#ifdef __cplusplus
interface ITfCandidateList;
#endif /* __cplusplus */
#endif

#ifndef __ITfCandidateString_FWD_DEFINED__
#define __ITfCandidateString_FWD_DEFINED__
typedef interface ITfCandidateString ITfCandidateString;
#ifdef __cplusplus
interface ITfCandidateString;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnAdviseText_FWD_DEFINED__
#define __ITfFnAdviseText_FWD_DEFINED__
typedef interface ITfFnAdviseText ITfFnAdviseText;
#ifdef __cplusplus
interface ITfFnAdviseText;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnBalloon_FWD_DEFINED__
#define __ITfFnBalloon_FWD_DEFINED__
typedef interface ITfFnBalloon ITfFnBalloon;
#ifdef __cplusplus
interface ITfFnBalloon;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnConfigure_FWD_DEFINED__
#define __ITfFnConfigure_FWD_DEFINED__
typedef interface ITfFnConfigure ITfFnConfigure;
#ifdef __cplusplus
interface ITfFnConfigure;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnConfigureRegisterEudc_FWD_DEFINED__
#define __ITfFnConfigureRegisterEudc_FWD_DEFINED__
typedef interface ITfFnConfigureRegisterEudc ITfFnConfigureRegisterEudc;
#ifdef __cplusplus
interface ITfFnConfigureRegisterEudc;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnConfigureRegisterWord_FWD_DEFINED__
#define __ITfFnConfigureRegisterWord_FWD_DEFINED__
typedef interface ITfFnConfigureRegisterWord ITfFnConfigureRegisterWord;
#ifdef __cplusplus
interface ITfFnConfigureRegisterWord;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnGetLinguisticAlternates_FWD_DEFINED__
#define __ITfFnGetLinguisticAlternates_FWD_DEFINED__
typedef interface ITfFnGetLinguisticAlternates ITfFnGetLinguisticAlternates;
#ifdef __cplusplus
interface ITfFnGetLinguisticAlternates;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnGetPreferredTouchKeyboardLayout_FWD_DEFINED__
#define __ITfFnGetPreferredTouchKeyboardLayout_FWD_DEFINED__
typedef interface ITfFnGetPreferredTouchKeyboardLayout ITfFnGetPreferredTouchKeyboardLayout;
#ifdef __cplusplus
interface ITfFnGetPreferredTouchKeyboardLayout;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnGetSAPIObject_FWD_DEFINED__
#define __ITfFnGetSAPIObject_FWD_DEFINED__
typedef interface ITfFnGetSAPIObject ITfFnGetSAPIObject;
#ifdef __cplusplus
interface ITfFnGetSAPIObject;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnLMInternal_FWD_DEFINED__
#define __ITfFnLMInternal_FWD_DEFINED__
typedef interface ITfFnLMInternal ITfFnLMInternal;
#ifdef __cplusplus
interface ITfFnLMInternal;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnLMProcessor_FWD_DEFINED__
#define __ITfFnLMProcessor_FWD_DEFINED__
typedef interface ITfFnLMProcessor ITfFnLMProcessor;
#ifdef __cplusplus
interface ITfFnLMProcessor;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnLangProfileUtil_FWD_DEFINED__
#define __ITfFnLangProfileUtil_FWD_DEFINED__
typedef interface ITfFnLangProfileUtil ITfFnLangProfileUtil;
#ifdef __cplusplus
interface ITfFnLangProfileUtil;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnPlayBack_FWD_DEFINED__
#define __ITfFnPlayBack_FWD_DEFINED__
typedef interface ITfFnPlayBack ITfFnPlayBack;
#ifdef __cplusplus
interface ITfFnPlayBack;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnPropertyUIStatus_FWD_DEFINED__
#define __ITfFnPropertyUIStatus_FWD_DEFINED__
typedef interface ITfFnPropertyUIStatus ITfFnPropertyUIStatus;
#ifdef __cplusplus
interface ITfFnPropertyUIStatus;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnReconversion_FWD_DEFINED__
#define __ITfFnReconversion_FWD_DEFINED__
typedef interface ITfFnReconversion ITfFnReconversion;
#ifdef __cplusplus
interface ITfFnReconversion;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnSearchCandidateProvider_FWD_DEFINED__
#define __ITfFnSearchCandidateProvider_FWD_DEFINED__
typedef interface ITfFnSearchCandidateProvider ITfFnSearchCandidateProvider;
#ifdef __cplusplus
interface ITfFnSearchCandidateProvider;
#endif /* __cplusplus */
#endif

#ifndef __ITfFnShowHelp_FWD_DEFINED__
#define __ITfFnShowHelp_FWD_DEFINED__
typedef interface ITfFnShowHelp ITfFnShowHelp;
#ifdef __cplusplus
interface ITfFnShowHelp;
#endif /* __cplusplus */
#endif

#ifndef __ITfFunction_FWD_DEFINED__
#define __ITfFunction_FWD_DEFINED__
typedef interface ITfFunction ITfFunction;
#ifdef __cplusplus
interface ITfFunction;
#endif /* __cplusplus */
#endif

#ifndef __ITfIntegratableCandidateListUIElement_FWD_DEFINED__
#define __ITfIntegratableCandidateListUIElement_FWD_DEFINED__
typedef interface ITfIntegratableCandidateListUIElement ITfIntegratableCandidateListUIElement;
#ifdef __cplusplus
interface ITfIntegratableCandidateListUIElement;
#endif /* __cplusplus */
#endif

#ifndef __ITfLMLattice_FWD_DEFINED__
#define __ITfLMLattice_FWD_DEFINED__
typedef interface ITfLMLattice ITfLMLattice;
#ifdef __cplusplus
interface ITfLMLattice;
#endif /* __cplusplus */
#endif

#ifndef __IUIManagerEventSink_FWD_DEFINED__
#define __IUIManagerEventSink_FWD_DEFINED__
typedef interface IUIManagerEventSink IUIManagerEventSink;
#ifdef __cplusplus
interface IUIManagerEventSink;
#endif /* __cplusplus */
#endif

/*****************************************************************************
 * IEnumTfCandidates interface
 */
#ifndef __IEnumTfCandidates_INTERFACE_DEFINED__
#define __IEnumTfCandidates_INTERFACE_DEFINED__

DEFINE_GUID(IID_IEnumTfCandidates, 0xdefb1926, 0x6c80, 0x4ce8, 0x87,0xd4, 0xd6,0xb7,0x2b,0x81,0x2b,0xde);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("defb1926-6c80-4ce8-87d4-d6b72b812bde")
IEnumTfCandidates : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Clone(
        IEnumTfCandidates **ppEnum) = 0;

    virtual HRESULT STDMETHODCALLTYPE Next(
        ULONG ulCount,
        ITfCandidateString **ppCand,
        ULONG *pcFetched) = 0;

    virtual HRESULT STDMETHODCALLTYPE Reset(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE Skip(
        ULONG ulCount) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IEnumTfCandidates, 0xdefb1926, 0x6c80, 0x4ce8, 0x87,0xd4, 0xd6,0xb7,0x2b,0x81,0x2b,0xde)
#endif
#else
typedef struct IEnumTfCandidatesVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IEnumTfCandidates *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IEnumTfCandidates *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IEnumTfCandidates *This);

    /*** IEnumTfCandidates methods ***/
    HRESULT (STDMETHODCALLTYPE *Clone)(
        IEnumTfCandidates *This,
        IEnumTfCandidates **ppEnum);

    HRESULT (STDMETHODCALLTYPE *Next)(
        IEnumTfCandidates *This,
        ULONG ulCount,
        ITfCandidateString **ppCand,
        ULONG *pcFetched);

    HRESULT (STDMETHODCALLTYPE *Reset)(
        IEnumTfCandidates *This);

    HRESULT (STDMETHODCALLTYPE *Skip)(
        IEnumTfCandidates *This,
        ULONG ulCount);

    END_INTERFACE
} IEnumTfCandidatesVtbl;

interface IEnumTfCandidates {
    CONST_VTBL IEnumTfCandidatesVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IEnumTfCandidates_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IEnumTfCandidates_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IEnumTfCandidates_Release(This) (This)->lpVtbl->Release(This)
/*** IEnumTfCandidates methods ***/
#define IEnumTfCandidates_Clone(This,ppEnum) (This)->lpVtbl->Clone(This,ppEnum)
#define IEnumTfCandidates_Next(This,ulCount,ppCand,pcFetched) (This)->lpVtbl->Next(This,ulCount,ppCand,pcFetched)
#define IEnumTfCandidates_Reset(This) (This)->lpVtbl->Reset(This)
#define IEnumTfCandidates_Skip(This,ulCount) (This)->lpVtbl->Skip(This,ulCount)
#else
/*** IUnknown methods ***/
static inline HRESULT IEnumTfCandidates_QueryInterface(IEnumTfCandidates* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IEnumTfCandidates_AddRef(IEnumTfCandidates* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IEnumTfCandidates_Release(IEnumTfCandidates* This) {
    return This->lpVtbl->Release(This);
}
/*** IEnumTfCandidates methods ***/
static inline HRESULT IEnumTfCandidates_Clone(IEnumTfCandidates* This,IEnumTfCandidates **ppEnum) {
    return This->lpVtbl->Clone(This,ppEnum);
}
static inline HRESULT IEnumTfCandidates_Next(IEnumTfCandidates* This,ULONG ulCount,ITfCandidateString **ppCand,ULONG *pcFetched) {
    return This->lpVtbl->Next(This,ulCount,ppCand,pcFetched);
}
static inline HRESULT IEnumTfCandidates_Reset(IEnumTfCandidates* This) {
    return This->lpVtbl->Reset(This);
}
static inline HRESULT IEnumTfCandidates_Skip(IEnumTfCandidates* This,ULONG ulCount) {
    return This->lpVtbl->Skip(This,ulCount);
}
#endif
#endif

#endif


#endif  /* __IEnumTfCandidates_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IEnumTfLatticeElements interface
 */
#ifndef __IEnumTfLatticeElements_INTERFACE_DEFINED__
#define __IEnumTfLatticeElements_INTERFACE_DEFINED__

DEFINE_GUID(IID_IEnumTfLatticeElements, 0x56988052, 0x47da, 0x4a05, 0x91,0x1a, 0xe3,0xd9,0x41,0xf1,0x71,0x45);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("56988052-47da-4a05-911a-e3d941f17145")
IEnumTfLatticeElements : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Clone(
        IEnumTfLatticeElements **ppEnum) = 0;

    virtual HRESULT STDMETHODCALLTYPE Next(
        ULONG ulCount,
        TF_LMLATTELEMENT *rgsElements,
        ULONG *pcFetched) = 0;

    virtual HRESULT STDMETHODCALLTYPE Reset(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE Skip(
        ULONG ulCount) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IEnumTfLatticeElements, 0x56988052, 0x47da, 0x4a05, 0x91,0x1a, 0xe3,0xd9,0x41,0xf1,0x71,0x45)
#endif
#else
typedef struct IEnumTfLatticeElementsVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IEnumTfLatticeElements *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IEnumTfLatticeElements *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IEnumTfLatticeElements *This);

    /*** IEnumTfLatticeElements methods ***/
    HRESULT (STDMETHODCALLTYPE *Clone)(
        IEnumTfLatticeElements *This,
        IEnumTfLatticeElements **ppEnum);

    HRESULT (STDMETHODCALLTYPE *Next)(
        IEnumTfLatticeElements *This,
        ULONG ulCount,
        TF_LMLATTELEMENT *rgsElements,
        ULONG *pcFetched);

    HRESULT (STDMETHODCALLTYPE *Reset)(
        IEnumTfLatticeElements *This);

    HRESULT (STDMETHODCALLTYPE *Skip)(
        IEnumTfLatticeElements *This,
        ULONG ulCount);

    END_INTERFACE
} IEnumTfLatticeElementsVtbl;

interface IEnumTfLatticeElements {
    CONST_VTBL IEnumTfLatticeElementsVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IEnumTfLatticeElements_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IEnumTfLatticeElements_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IEnumTfLatticeElements_Release(This) (This)->lpVtbl->Release(This)
/*** IEnumTfLatticeElements methods ***/
#define IEnumTfLatticeElements_Clone(This,ppEnum) (This)->lpVtbl->Clone(This,ppEnum)
#define IEnumTfLatticeElements_Next(This,ulCount,rgsElements,pcFetched) (This)->lpVtbl->Next(This,ulCount,rgsElements,pcFetched)
#define IEnumTfLatticeElements_Reset(This) (This)->lpVtbl->Reset(This)
#define IEnumTfLatticeElements_Skip(This,ulCount) (This)->lpVtbl->Skip(This,ulCount)
#else
/*** IUnknown methods ***/
static inline HRESULT IEnumTfLatticeElements_QueryInterface(IEnumTfLatticeElements* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IEnumTfLatticeElements_AddRef(IEnumTfLatticeElements* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IEnumTfLatticeElements_Release(IEnumTfLatticeElements* This) {
    return This->lpVtbl->Release(This);
}
/*** IEnumTfLatticeElements methods ***/
static inline HRESULT IEnumTfLatticeElements_Clone(IEnumTfLatticeElements* This,IEnumTfLatticeElements **ppEnum) {
    return This->lpVtbl->Clone(This,ppEnum);
}
static inline HRESULT IEnumTfLatticeElements_Next(IEnumTfLatticeElements* This,ULONG ulCount,TF_LMLATTELEMENT *rgsElements,ULONG *pcFetched) {
    return This->lpVtbl->Next(This,ulCount,rgsElements,pcFetched);
}
static inline HRESULT IEnumTfLatticeElements_Reset(IEnumTfLatticeElements* This) {
    return This->lpVtbl->Reset(This);
}
static inline HRESULT IEnumTfLatticeElements_Skip(IEnumTfLatticeElements* This,ULONG ulCount) {
    return This->lpVtbl->Skip(This,ulCount);
}
#endif
#endif

#endif


#endif  /* __IEnumTfLatticeElements_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfCandidateList interface
 */
#ifndef __ITfCandidateList_INTERFACE_DEFINED__
#define __ITfCandidateList_INTERFACE_DEFINED__

typedef enum __WIDL_ctffunc_generated_name_0000001E {
    CAND_FINALIZED = 0,
    CAND_SELECTED = 0x1,
    CAND_CANCELED = 0x2
} TfCandidateResult;
DEFINE_GUID(IID_ITfCandidateList, 0xa3ad50fb, 0x9bdb, 0x49e3, 0xa8,0x43, 0x6c,0x76,0x52,0x0f,0xbf,0x5d);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("a3ad50fb-9bdb-49e3-a843-6c76520fbf5d")
ITfCandidateList : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE EnumCandidates(
        IEnumTfCandidates **ppEnum) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetCandidate(
        ULONG nIndex,
        ITfCandidateString **ppCand) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetCandidateNum(
        ULONG *pnCnt) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetResult(
        ULONG nIndex,
        TfCandidateResult imcr) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfCandidateList, 0xa3ad50fb, 0x9bdb, 0x49e3, 0xa8,0x43, 0x6c,0x76,0x52,0x0f,0xbf,0x5d)
#endif
#else
typedef struct ITfCandidateListVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfCandidateList *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfCandidateList *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfCandidateList *This);

    /*** ITfCandidateList methods ***/
    HRESULT (STDMETHODCALLTYPE *EnumCandidates)(
        ITfCandidateList *This,
        IEnumTfCandidates **ppEnum);

    HRESULT (STDMETHODCALLTYPE *GetCandidate)(
        ITfCandidateList *This,
        ULONG nIndex,
        ITfCandidateString **ppCand);

    HRESULT (STDMETHODCALLTYPE *GetCandidateNum)(
        ITfCandidateList *This,
        ULONG *pnCnt);

    HRESULT (STDMETHODCALLTYPE *SetResult)(
        ITfCandidateList *This,
        ULONG nIndex,
        TfCandidateResult imcr);

    END_INTERFACE
} ITfCandidateListVtbl;

interface ITfCandidateList {
    CONST_VTBL ITfCandidateListVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfCandidateList_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfCandidateList_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfCandidateList_Release(This) (This)->lpVtbl->Release(This)
/*** ITfCandidateList methods ***/
#define ITfCandidateList_EnumCandidates(This,ppEnum) (This)->lpVtbl->EnumCandidates(This,ppEnum)
#define ITfCandidateList_GetCandidate(This,nIndex,ppCand) (This)->lpVtbl->GetCandidate(This,nIndex,ppCand)
#define ITfCandidateList_GetCandidateNum(This,pnCnt) (This)->lpVtbl->GetCandidateNum(This,pnCnt)
#define ITfCandidateList_SetResult(This,nIndex,imcr) (This)->lpVtbl->SetResult(This,nIndex,imcr)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfCandidateList_QueryInterface(ITfCandidateList* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfCandidateList_AddRef(ITfCandidateList* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfCandidateList_Release(ITfCandidateList* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfCandidateList methods ***/
static inline HRESULT ITfCandidateList_EnumCandidates(ITfCandidateList* This,IEnumTfCandidates **ppEnum) {
    return This->lpVtbl->EnumCandidates(This,ppEnum);
}
static inline HRESULT ITfCandidateList_GetCandidate(ITfCandidateList* This,ULONG nIndex,ITfCandidateString **ppCand) {
    return This->lpVtbl->GetCandidate(This,nIndex,ppCand);
}
static inline HRESULT ITfCandidateList_GetCandidateNum(ITfCandidateList* This,ULONG *pnCnt) {
    return This->lpVtbl->GetCandidateNum(This,pnCnt);
}
static inline HRESULT ITfCandidateList_SetResult(ITfCandidateList* This,ULONG nIndex,TfCandidateResult imcr) {
    return This->lpVtbl->SetResult(This,nIndex,imcr);
}
#endif
#endif

#endif


#endif  /* __ITfCandidateList_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfCandidateString interface
 */
#ifndef __ITfCandidateString_INTERFACE_DEFINED__
#define __ITfCandidateString_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfCandidateString, 0x581f317e, 0xfd9d, 0x443f, 0xb9,0x72, 0xed,0x00,0x46,0x7c,0x5d,0x40);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("581f317e-fd9d-443f-b972-ed00467c5d40")
ITfCandidateString : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE GetString(
        BSTR *pbstr) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetIndex(
        ULONG *pnIndex) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfCandidateString, 0x581f317e, 0xfd9d, 0x443f, 0xb9,0x72, 0xed,0x00,0x46,0x7c,0x5d,0x40)
#endif
#else
typedef struct ITfCandidateStringVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfCandidateString *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfCandidateString *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfCandidateString *This);

    /*** ITfCandidateString methods ***/
    HRESULT (STDMETHODCALLTYPE *GetString)(
        ITfCandidateString *This,
        BSTR *pbstr);

    HRESULT (STDMETHODCALLTYPE *GetIndex)(
        ITfCandidateString *This,
        ULONG *pnIndex);

    END_INTERFACE
} ITfCandidateStringVtbl;

interface ITfCandidateString {
    CONST_VTBL ITfCandidateStringVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfCandidateString_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfCandidateString_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfCandidateString_Release(This) (This)->lpVtbl->Release(This)
/*** ITfCandidateString methods ***/
#define ITfCandidateString_GetString(This,pbstr) (This)->lpVtbl->GetString(This,pbstr)
#define ITfCandidateString_GetIndex(This,pnIndex) (This)->lpVtbl->GetIndex(This,pnIndex)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfCandidateString_QueryInterface(ITfCandidateString* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfCandidateString_AddRef(ITfCandidateString* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfCandidateString_Release(ITfCandidateString* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfCandidateString methods ***/
static inline HRESULT ITfCandidateString_GetString(ITfCandidateString* This,BSTR *pbstr) {
    return This->lpVtbl->GetString(This,pbstr);
}
static inline HRESULT ITfCandidateString_GetIndex(ITfCandidateString* This,ULONG *pnIndex) {
    return This->lpVtbl->GetIndex(This,pnIndex);
}
#endif
#endif

#endif


#endif  /* __ITfCandidateString_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnAdviseText interface
 */
#ifndef __ITfFnAdviseText_INTERFACE_DEFINED__
#define __ITfFnAdviseText_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnAdviseText, 0x3527268b, 0x7d53, 0x4dd9, 0x92,0xb7, 0x72,0x96,0xae,0x46,0x12,0x49);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("3527268b-7d53-4dd9-92b7-7296ae461249")
ITfFnAdviseText : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE OnTextUpdate(
        ITfRange *pRange,
        const WCHAR *pchText,
        LONG cch) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnLatticeUpdate(
        ITfRange *pRange,
        ITfLMLattice *pLattice) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnAdviseText, 0x3527268b, 0x7d53, 0x4dd9, 0x92,0xb7, 0x72,0x96,0xae,0x46,0x12,0x49)
#endif
#else
typedef struct ITfFnAdviseTextVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnAdviseText *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnAdviseText *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnAdviseText *This);

    /*** ITfFnAdviseText methods ***/
    HRESULT (STDMETHODCALLTYPE *OnTextUpdate)(
        ITfFnAdviseText *This,
        ITfRange *pRange,
        const WCHAR *pchText,
        LONG cch);

    HRESULT (STDMETHODCALLTYPE *OnLatticeUpdate)(
        ITfFnAdviseText *This,
        ITfRange *pRange,
        ITfLMLattice *pLattice);

    END_INTERFACE
} ITfFnAdviseTextVtbl;

interface ITfFnAdviseText {
    CONST_VTBL ITfFnAdviseTextVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnAdviseText_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnAdviseText_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnAdviseText_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnAdviseText methods ***/
#define ITfFnAdviseText_OnTextUpdate(This,pRange,pchText,cch) (This)->lpVtbl->OnTextUpdate(This,pRange,pchText,cch)
#define ITfFnAdviseText_OnLatticeUpdate(This,pRange,pLattice) (This)->lpVtbl->OnLatticeUpdate(This,pRange,pLattice)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnAdviseText_QueryInterface(ITfFnAdviseText* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnAdviseText_AddRef(ITfFnAdviseText* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnAdviseText_Release(ITfFnAdviseText* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnAdviseText methods ***/
static inline HRESULT ITfFnAdviseText_OnTextUpdate(ITfFnAdviseText* This,ITfRange *pRange,const WCHAR *pchText,LONG cch) {
    return This->lpVtbl->OnTextUpdate(This,pRange,pchText,cch);
}
static inline HRESULT ITfFnAdviseText_OnLatticeUpdate(ITfFnAdviseText* This,ITfRange *pRange,ITfLMLattice *pLattice) {
    return This->lpVtbl->OnLatticeUpdate(This,pRange,pLattice);
}
#endif
#endif

#endif


#endif  /* __ITfFnAdviseText_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnBalloon interface
 */
#ifndef __ITfFnBalloon_INTERFACE_DEFINED__
#define __ITfFnBalloon_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnBalloon, 0x3bab89e4, 0x5fbe, 0x45f4, 0xa5,0xbc, 0xdc,0xa3,0x6a,0xd2,0x25,0xa8);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("3bab89e4-5fbe-45f4-a5bc-dca36ad225a8")
ITfFnBalloon : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE UpdateBalloon(
        TfLBBalloonStyle style,
        const WCHAR *pch,
        ULONG cch) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnBalloon, 0x3bab89e4, 0x5fbe, 0x45f4, 0xa5,0xbc, 0xdc,0xa3,0x6a,0xd2,0x25,0xa8)
#endif
#else
typedef struct ITfFnBalloonVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnBalloon *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnBalloon *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnBalloon *This);

    /*** ITfFnBalloon methods ***/
    HRESULT (STDMETHODCALLTYPE *UpdateBalloon)(
        ITfFnBalloon *This,
        TfLBBalloonStyle style,
        const WCHAR *pch,
        ULONG cch);

    END_INTERFACE
} ITfFnBalloonVtbl;

interface ITfFnBalloon {
    CONST_VTBL ITfFnBalloonVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnBalloon_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnBalloon_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnBalloon_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnBalloon methods ***/
#define ITfFnBalloon_UpdateBalloon(This,style,pch,cch) (This)->lpVtbl->UpdateBalloon(This,style,pch,cch)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnBalloon_QueryInterface(ITfFnBalloon* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnBalloon_AddRef(ITfFnBalloon* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnBalloon_Release(ITfFnBalloon* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnBalloon methods ***/
static inline HRESULT ITfFnBalloon_UpdateBalloon(ITfFnBalloon* This,TfLBBalloonStyle style,const WCHAR *pch,ULONG cch) {
    return This->lpVtbl->UpdateBalloon(This,style,pch,cch);
}
#endif
#endif

#endif


#endif  /* __ITfFnBalloon_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnConfigure interface
 */
#ifndef __ITfFnConfigure_INTERFACE_DEFINED__
#define __ITfFnConfigure_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnConfigure, 0x88f567c6, 0x1757, 0x49f8, 0xa1,0xb2, 0x89,0x23,0x4c,0x1e,0xef,0xf9);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("88f567c6-1757-49f8-a1b2-89234c1eeff9")
ITfFnConfigure : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Show(
        HWND hwndParent,
        LANGID langid,
        REFGUID rguidProfile) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnConfigure, 0x88f567c6, 0x1757, 0x49f8, 0xa1,0xb2, 0x89,0x23,0x4c,0x1e,0xef,0xf9)
#endif
#else
typedef struct ITfFnConfigureVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnConfigure *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnConfigure *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnConfigure *This);

    /*** ITfFnConfigure methods ***/
    HRESULT (STDMETHODCALLTYPE *Show)(
        ITfFnConfigure *This,
        HWND hwndParent,
        LANGID langid,
        REFGUID rguidProfile);

    END_INTERFACE
} ITfFnConfigureVtbl;

interface ITfFnConfigure {
    CONST_VTBL ITfFnConfigureVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnConfigure_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnConfigure_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnConfigure_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnConfigure methods ***/
#define ITfFnConfigure_Show(This,hwndParent,langid,rguidProfile) (This)->lpVtbl->Show(This,hwndParent,langid,rguidProfile)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnConfigure_QueryInterface(ITfFnConfigure* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnConfigure_AddRef(ITfFnConfigure* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnConfigure_Release(ITfFnConfigure* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnConfigure methods ***/
static inline HRESULT ITfFnConfigure_Show(ITfFnConfigure* This,HWND hwndParent,LANGID langid,REFGUID rguidProfile) {
    return This->lpVtbl->Show(This,hwndParent,langid,rguidProfile);
}
#endif
#endif

#endif


#endif  /* __ITfFnConfigure_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnConfigureRegisterEudc interface
 */
#ifndef __ITfFnConfigureRegisterEudc_INTERFACE_DEFINED__
#define __ITfFnConfigureRegisterEudc_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnConfigureRegisterEudc, 0xb5e26ff5, 0xd7ad, 0x4304, 0x91,0x3f, 0x21,0xa2,0xed,0x95,0xa1,0xb0);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("b5e26ff5-d7ad-4304-913f-21a2ed95a1b0")
ITfFnConfigureRegisterEudc : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Show(
        HWND hwndParent,
        LANGID langid,
        REFGUID rguidProfile,
        BSTR bstrRegistered) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnConfigureRegisterEudc, 0xb5e26ff5, 0xd7ad, 0x4304, 0x91,0x3f, 0x21,0xa2,0xed,0x95,0xa1,0xb0)
#endif
#else
typedef struct ITfFnConfigureRegisterEudcVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnConfigureRegisterEudc *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnConfigureRegisterEudc *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnConfigureRegisterEudc *This);

    /*** ITfFnConfigureRegisterEudc methods ***/
    HRESULT (STDMETHODCALLTYPE *Show)(
        ITfFnConfigureRegisterEudc *This,
        HWND hwndParent,
        LANGID langid,
        REFGUID rguidProfile,
        BSTR bstrRegistered);

    END_INTERFACE
} ITfFnConfigureRegisterEudcVtbl;

interface ITfFnConfigureRegisterEudc {
    CONST_VTBL ITfFnConfigureRegisterEudcVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnConfigureRegisterEudc_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnConfigureRegisterEudc_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnConfigureRegisterEudc_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnConfigureRegisterEudc methods ***/
#define ITfFnConfigureRegisterEudc_Show(This,hwndParent,langid,rguidProfile,bstrRegistered) (This)->lpVtbl->Show(This,hwndParent,langid,rguidProfile,bstrRegistered)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnConfigureRegisterEudc_QueryInterface(ITfFnConfigureRegisterEudc* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnConfigureRegisterEudc_AddRef(ITfFnConfigureRegisterEudc* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnConfigureRegisterEudc_Release(ITfFnConfigureRegisterEudc* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnConfigureRegisterEudc methods ***/
static inline HRESULT ITfFnConfigureRegisterEudc_Show(ITfFnConfigureRegisterEudc* This,HWND hwndParent,LANGID langid,REFGUID rguidProfile,BSTR bstrRegistered) {
    return This->lpVtbl->Show(This,hwndParent,langid,rguidProfile,bstrRegistered);
}
#endif
#endif

#endif


#endif  /* __ITfFnConfigureRegisterEudc_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnConfigureRegisterWord interface
 */
#ifndef __ITfFnConfigureRegisterWord_INTERFACE_DEFINED__
#define __ITfFnConfigureRegisterWord_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnConfigureRegisterWord, 0xbb95808a, 0x6d8f, 0x4bca, 0x84,0x00, 0x53,0x90,0xb5,0x86,0xae,0xdf);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("bb95808a-6d8f-4bca-8400-5390b586aedf")
ITfFnConfigureRegisterWord : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Show(
        HWND hwndParent,
        LANGID langid,
        REFGUID rguidProfile,
        BSTR bstrRegistered) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnConfigureRegisterWord, 0xbb95808a, 0x6d8f, 0x4bca, 0x84,0x00, 0x53,0x90,0xb5,0x86,0xae,0xdf)
#endif
#else
typedef struct ITfFnConfigureRegisterWordVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnConfigureRegisterWord *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnConfigureRegisterWord *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnConfigureRegisterWord *This);

    /*** ITfFnConfigureRegisterWord methods ***/
    HRESULT (STDMETHODCALLTYPE *Show)(
        ITfFnConfigureRegisterWord *This,
        HWND hwndParent,
        LANGID langid,
        REFGUID rguidProfile,
        BSTR bstrRegistered);

    END_INTERFACE
} ITfFnConfigureRegisterWordVtbl;

interface ITfFnConfigureRegisterWord {
    CONST_VTBL ITfFnConfigureRegisterWordVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnConfigureRegisterWord_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnConfigureRegisterWord_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnConfigureRegisterWord_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnConfigureRegisterWord methods ***/
#define ITfFnConfigureRegisterWord_Show(This,hwndParent,langid,rguidProfile,bstrRegistered) (This)->lpVtbl->Show(This,hwndParent,langid,rguidProfile,bstrRegistered)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnConfigureRegisterWord_QueryInterface(ITfFnConfigureRegisterWord* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnConfigureRegisterWord_AddRef(ITfFnConfigureRegisterWord* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnConfigureRegisterWord_Release(ITfFnConfigureRegisterWord* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnConfigureRegisterWord methods ***/
static inline HRESULT ITfFnConfigureRegisterWord_Show(ITfFnConfigureRegisterWord* This,HWND hwndParent,LANGID langid,REFGUID rguidProfile,BSTR bstrRegistered) {
    return This->lpVtbl->Show(This,hwndParent,langid,rguidProfile,bstrRegistered);
}
#endif
#endif

#endif


#endif  /* __ITfFnConfigureRegisterWord_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFunction interface
 */
#ifndef __ITfFunction_INTERFACE_DEFINED__
#define __ITfFunction_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFunction, 0xdb593490, 0x098f, 0x11d3, 0x8d,0xf0, 0x00,0x10,0x5a,0x27,0x99,0xb5);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("db593490-098f-11d3-8df0-00105a2799b5")
ITfFunction : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE GetDisplayName(
        BSTR *pbstrName) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFunction, 0xdb593490, 0x098f, 0x11d3, 0x8d,0xf0, 0x00,0x10,0x5a,0x27,0x99,0xb5)
#endif
#else
typedef struct ITfFunctionVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFunction *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFunction *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFunction *This);

    /*** ITfFunction methods ***/
    HRESULT (STDMETHODCALLTYPE *GetDisplayName)(
        ITfFunction *This,
        BSTR *pbstrName);

    END_INTERFACE
} ITfFunctionVtbl;

interface ITfFunction {
    CONST_VTBL ITfFunctionVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFunction_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFunction_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFunction_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFunction methods ***/
#define ITfFunction_GetDisplayName(This,pbstrName) (This)->lpVtbl->GetDisplayName(This,pbstrName)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFunction_QueryInterface(ITfFunction* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFunction_AddRef(ITfFunction* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFunction_Release(ITfFunction* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFunction methods ***/
static inline HRESULT ITfFunction_GetDisplayName(ITfFunction* This,BSTR *pbstrName) {
    return This->lpVtbl->GetDisplayName(This,pbstrName);
}
#endif
#endif

#endif


#endif  /* __ITfFunction_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnGetLinguisticAlternates interface
 */
#ifndef __ITfFnGetLinguisticAlternates_INTERFACE_DEFINED__
#define __ITfFnGetLinguisticAlternates_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnGetLinguisticAlternates, 0xea163ce2, 0x7a65, 0x4506, 0x82,0xa3, 0xc5,0x28,0x21,0x5d,0xa6,0x4e);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("ea163ce2-7a65-4506-82a3-c528215da64e")
ITfFnGetLinguisticAlternates : public ITfFunction
{
    virtual HRESULT STDMETHODCALLTYPE GetAlternates(
        ITfRange *pRange,
        ITfCandidateList **ppCandidateList) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnGetLinguisticAlternates, 0xea163ce2, 0x7a65, 0x4506, 0x82,0xa3, 0xc5,0x28,0x21,0x5d,0xa6,0x4e)
#endif
#else
typedef struct ITfFnGetLinguisticAlternatesVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnGetLinguisticAlternates *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnGetLinguisticAlternates *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnGetLinguisticAlternates *This);

    /*** ITfFunction methods ***/
    HRESULT (STDMETHODCALLTYPE *GetDisplayName)(
        ITfFnGetLinguisticAlternates *This,
        BSTR *pbstrName);

    /*** ITfFnGetLinguisticAlternates methods ***/
    HRESULT (STDMETHODCALLTYPE *GetAlternates)(
        ITfFnGetLinguisticAlternates *This,
        ITfRange *pRange,
        ITfCandidateList **ppCandidateList);

    END_INTERFACE
} ITfFnGetLinguisticAlternatesVtbl;

interface ITfFnGetLinguisticAlternates {
    CONST_VTBL ITfFnGetLinguisticAlternatesVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnGetLinguisticAlternates_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnGetLinguisticAlternates_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnGetLinguisticAlternates_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFunction methods ***/
#define ITfFnGetLinguisticAlternates_GetDisplayName(This,pbstrName) (This)->lpVtbl->GetDisplayName(This,pbstrName)
/*** ITfFnGetLinguisticAlternates methods ***/
#define ITfFnGetLinguisticAlternates_GetAlternates(This,pRange,ppCandidateList) (This)->lpVtbl->GetAlternates(This,pRange,ppCandidateList)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnGetLinguisticAlternates_QueryInterface(ITfFnGetLinguisticAlternates* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnGetLinguisticAlternates_AddRef(ITfFnGetLinguisticAlternates* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnGetLinguisticAlternates_Release(ITfFnGetLinguisticAlternates* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFunction methods ***/
static inline HRESULT ITfFnGetLinguisticAlternates_GetDisplayName(ITfFnGetLinguisticAlternates* This,BSTR *pbstrName) {
    return This->lpVtbl->GetDisplayName(This,pbstrName);
}
/*** ITfFnGetLinguisticAlternates methods ***/
static inline HRESULT ITfFnGetLinguisticAlternates_GetAlternates(ITfFnGetLinguisticAlternates* This,ITfRange *pRange,ITfCandidateList **ppCandidateList) {
    return This->lpVtbl->GetAlternates(This,pRange,ppCandidateList);
}
#endif
#endif

#endif


#endif  /* __ITfFnGetLinguisticAlternates_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnGetPreferredTouchKeyboardLayout interface
 */
#ifndef __ITfFnGetPreferredTouchKeyboardLayout_INTERFACE_DEFINED__
#define __ITfFnGetPreferredTouchKeyboardLayout_INTERFACE_DEFINED__

typedef enum __WIDL_ctffunc_generated_name_0000001F {
    TKBLT_UNDEFINED = 0,
    TKBLT_CLASSIC = 1,
    TKBLT_OPTIMIZED = 2
} TKBLayoutType;
DEFINE_GUID(IID_ITfFnGetPreferredTouchKeyboardLayout, 0x5f309a41, 0x590a, 0x4acc, 0xa9,0x7f, 0xd8,0xef,0xff,0x13,0xfd,0xfc);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("5f309a41-590a-4acc-a97f-d8efff13fdfc")
ITfFnGetPreferredTouchKeyboardLayout : public ITfFunction
{
    virtual HRESULT STDMETHODCALLTYPE GetLayout(
        TKBLayoutType *pTKBLayoutType,
        WORD *pwPreferredLayoutId) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnGetPreferredTouchKeyboardLayout, 0x5f309a41, 0x590a, 0x4acc, 0xa9,0x7f, 0xd8,0xef,0xff,0x13,0xfd,0xfc)
#endif
#else
typedef struct ITfFnGetPreferredTouchKeyboardLayoutVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnGetPreferredTouchKeyboardLayout *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnGetPreferredTouchKeyboardLayout *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnGetPreferredTouchKeyboardLayout *This);

    /*** ITfFunction methods ***/
    HRESULT (STDMETHODCALLTYPE *GetDisplayName)(
        ITfFnGetPreferredTouchKeyboardLayout *This,
        BSTR *pbstrName);

    /*** ITfFnGetPreferredTouchKeyboardLayout methods ***/
    HRESULT (STDMETHODCALLTYPE *GetLayout)(
        ITfFnGetPreferredTouchKeyboardLayout *This,
        TKBLayoutType *pTKBLayoutType,
        WORD *pwPreferredLayoutId);

    END_INTERFACE
} ITfFnGetPreferredTouchKeyboardLayoutVtbl;

interface ITfFnGetPreferredTouchKeyboardLayout {
    CONST_VTBL ITfFnGetPreferredTouchKeyboardLayoutVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnGetPreferredTouchKeyboardLayout_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnGetPreferredTouchKeyboardLayout_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnGetPreferredTouchKeyboardLayout_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFunction methods ***/
#define ITfFnGetPreferredTouchKeyboardLayout_GetDisplayName(This,pbstrName) (This)->lpVtbl->GetDisplayName(This,pbstrName)
/*** ITfFnGetPreferredTouchKeyboardLayout methods ***/
#define ITfFnGetPreferredTouchKeyboardLayout_GetLayout(This,pTKBLayoutType,pwPreferredLayoutId) (This)->lpVtbl->GetLayout(This,pTKBLayoutType,pwPreferredLayoutId)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnGetPreferredTouchKeyboardLayout_QueryInterface(ITfFnGetPreferredTouchKeyboardLayout* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnGetPreferredTouchKeyboardLayout_AddRef(ITfFnGetPreferredTouchKeyboardLayout* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnGetPreferredTouchKeyboardLayout_Release(ITfFnGetPreferredTouchKeyboardLayout* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFunction methods ***/
static inline HRESULT ITfFnGetPreferredTouchKeyboardLayout_GetDisplayName(ITfFnGetPreferredTouchKeyboardLayout* This,BSTR *pbstrName) {
    return This->lpVtbl->GetDisplayName(This,pbstrName);
}
/*** ITfFnGetPreferredTouchKeyboardLayout methods ***/
static inline HRESULT ITfFnGetPreferredTouchKeyboardLayout_GetLayout(ITfFnGetPreferredTouchKeyboardLayout* This,TKBLayoutType *pTKBLayoutType,WORD *pwPreferredLayoutId) {
    return This->lpVtbl->GetLayout(This,pTKBLayoutType,pwPreferredLayoutId);
}
#endif
#endif

#endif


#endif  /* __ITfFnGetPreferredTouchKeyboardLayout_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnGetSAPIObject interface
 */
#ifndef __ITfFnGetSAPIObject_INTERFACE_DEFINED__
#define __ITfFnGetSAPIObject_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnGetSAPIObject, 0x5c0ab7ea, 0x167d, 0x4f59, 0xbf,0xb5, 0x46,0x93,0x75,0x5e,0x90,0xca);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("5c0ab7ea-167d-4f59-bfb5-4693755e90ca")
ITfFnGetSAPIObject : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Get(
        TfSapiObject sObj,
        IUnknown **ppunk) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnGetSAPIObject, 0x5c0ab7ea, 0x167d, 0x4f59, 0xbf,0xb5, 0x46,0x93,0x75,0x5e,0x90,0xca)
#endif
#else
typedef struct ITfFnGetSAPIObjectVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnGetSAPIObject *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnGetSAPIObject *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnGetSAPIObject *This);

    /*** ITfFnGetSAPIObject methods ***/
    HRESULT (STDMETHODCALLTYPE *Get)(
        ITfFnGetSAPIObject *This,
        TfSapiObject sObj,
        IUnknown **ppunk);

    END_INTERFACE
} ITfFnGetSAPIObjectVtbl;

interface ITfFnGetSAPIObject {
    CONST_VTBL ITfFnGetSAPIObjectVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnGetSAPIObject_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnGetSAPIObject_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnGetSAPIObject_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnGetSAPIObject methods ***/
#define ITfFnGetSAPIObject_Get(This,sObj,ppunk) (This)->lpVtbl->Get(This,sObj,ppunk)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnGetSAPIObject_QueryInterface(ITfFnGetSAPIObject* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnGetSAPIObject_AddRef(ITfFnGetSAPIObject* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnGetSAPIObject_Release(ITfFnGetSAPIObject* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnGetSAPIObject methods ***/
static inline HRESULT ITfFnGetSAPIObject_Get(ITfFnGetSAPIObject* This,TfSapiObject sObj,IUnknown **ppunk) {
    return This->lpVtbl->Get(This,sObj,ppunk);
}
#endif
#endif

#endif


#endif  /* __ITfFnGetSAPIObject_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnLMInternal interface
 */
#ifndef __ITfFnLMInternal_INTERFACE_DEFINED__
#define __ITfFnLMInternal_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnLMInternal, 0x04b825b1, 0xac9a, 0x4f7b, 0xb5,0xad, 0xc7,0x16,0x8f,0x1e,0xe4,0x45);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("04b825b1-ac9a-4f7b-b5ad-c7168f1ee445")
ITfFnLMInternal : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE ProcessLattice(
        ITfRange *pRange) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnLMInternal, 0x04b825b1, 0xac9a, 0x4f7b, 0xb5,0xad, 0xc7,0x16,0x8f,0x1e,0xe4,0x45)
#endif
#else
typedef struct ITfFnLMInternalVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnLMInternal *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnLMInternal *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnLMInternal *This);

    /*** ITfFnLMInternal methods ***/
    HRESULT (STDMETHODCALLTYPE *ProcessLattice)(
        ITfFnLMInternal *This,
        ITfRange *pRange);

    END_INTERFACE
} ITfFnLMInternalVtbl;

interface ITfFnLMInternal {
    CONST_VTBL ITfFnLMInternalVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnLMInternal_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnLMInternal_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnLMInternal_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnLMInternal methods ***/
#define ITfFnLMInternal_ProcessLattice(This,pRange) (This)->lpVtbl->ProcessLattice(This,pRange)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnLMInternal_QueryInterface(ITfFnLMInternal* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnLMInternal_AddRef(ITfFnLMInternal* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnLMInternal_Release(ITfFnLMInternal* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnLMInternal methods ***/
static inline HRESULT ITfFnLMInternal_ProcessLattice(ITfFnLMInternal* This,ITfRange *pRange) {
    return This->lpVtbl->ProcessLattice(This,pRange);
}
#endif
#endif

#endif


#endif  /* __ITfFnLMInternal_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnLMProcessor interface
 */
#ifndef __ITfFnLMProcessor_INTERFACE_DEFINED__
#define __ITfFnLMProcessor_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnLMProcessor, 0x7afbf8e7, 0xac4b, 0x4082, 0xb0,0x58, 0x89,0x08,0x99,0xd3,0xa0,0x10);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("7afbf8e7-ac4b-4082-b058-890899d3a010")
ITfFnLMProcessor : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE QueryRange(
        ITfRange *pRange,
        ITfRange **ppNewRange,
        BOOL *pfAccepted) = 0;

    virtual HRESULT STDMETHODCALLTYPE QueryLangID(
        LANGID langid,
        BOOL *pfAccepted) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetReconversion(
        ITfRange *pRange,
        ITfCandidateList **ppCandList) = 0;

    virtual HRESULT STDMETHODCALLTYPE Reconvert(
        ITfRange *pRange) = 0;

    virtual HRESULT STDMETHODCALLTYPE QueryKey(
        BOOL fUp,
        WPARAM vKey,
        LPARAM lparamKeydata,
        BOOL *pfInterested) = 0;

    virtual HRESULT STDMETHODCALLTYPE InvokeKey(
        BOOL fUp,
        WPARAM vKey,
        LPARAM lparamKeyData) = 0;

    virtual HRESULT STDMETHODCALLTYPE InvokeFunc(
        ITfContext *pic,
        REFGUID refguidFunc) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnLMProcessor, 0x7afbf8e7, 0xac4b, 0x4082, 0xb0,0x58, 0x89,0x08,0x99,0xd3,0xa0,0x10)
#endif
#else
typedef struct ITfFnLMProcessorVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnLMProcessor *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnLMProcessor *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnLMProcessor *This);

    /*** ITfFnLMProcessor methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryRange)(
        ITfFnLMProcessor *This,
        ITfRange *pRange,
        ITfRange **ppNewRange,
        BOOL *pfAccepted);

    HRESULT (STDMETHODCALLTYPE *QueryLangID)(
        ITfFnLMProcessor *This,
        LANGID langid,
        BOOL *pfAccepted);

    HRESULT (STDMETHODCALLTYPE *GetReconversion)(
        ITfFnLMProcessor *This,
        ITfRange *pRange,
        ITfCandidateList **ppCandList);

    HRESULT (STDMETHODCALLTYPE *Reconvert)(
        ITfFnLMProcessor *This,
        ITfRange *pRange);

    HRESULT (STDMETHODCALLTYPE *QueryKey)(
        ITfFnLMProcessor *This,
        BOOL fUp,
        WPARAM vKey,
        LPARAM lparamKeydata,
        BOOL *pfInterested);

    HRESULT (STDMETHODCALLTYPE *InvokeKey)(
        ITfFnLMProcessor *This,
        BOOL fUp,
        WPARAM vKey,
        LPARAM lparamKeyData);

    HRESULT (STDMETHODCALLTYPE *InvokeFunc)(
        ITfFnLMProcessor *This,
        ITfContext *pic,
        REFGUID refguidFunc);

    END_INTERFACE
} ITfFnLMProcessorVtbl;

interface ITfFnLMProcessor {
    CONST_VTBL ITfFnLMProcessorVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnLMProcessor_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnLMProcessor_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnLMProcessor_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnLMProcessor methods ***/
#define ITfFnLMProcessor_QueryRange(This,pRange,ppNewRange,pfAccepted) (This)->lpVtbl->QueryRange(This,pRange,ppNewRange,pfAccepted)
#define ITfFnLMProcessor_QueryLangID(This,langid,pfAccepted) (This)->lpVtbl->QueryLangID(This,langid,pfAccepted)
#define ITfFnLMProcessor_GetReconversion(This,pRange,ppCandList) (This)->lpVtbl->GetReconversion(This,pRange,ppCandList)
#define ITfFnLMProcessor_Reconvert(This,pRange) (This)->lpVtbl->Reconvert(This,pRange)
#define ITfFnLMProcessor_QueryKey(This,fUp,vKey,lparamKeydata,pfInterested) (This)->lpVtbl->QueryKey(This,fUp,vKey,lparamKeydata,pfInterested)
#define ITfFnLMProcessor_InvokeKey(This,fUp,vKey,lparamKeyData) (This)->lpVtbl->InvokeKey(This,fUp,vKey,lparamKeyData)
#define ITfFnLMProcessor_InvokeFunc(This,pic,refguidFunc) (This)->lpVtbl->InvokeFunc(This,pic,refguidFunc)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnLMProcessor_QueryInterface(ITfFnLMProcessor* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnLMProcessor_AddRef(ITfFnLMProcessor* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnLMProcessor_Release(ITfFnLMProcessor* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnLMProcessor methods ***/
static inline HRESULT ITfFnLMProcessor_QueryRange(ITfFnLMProcessor* This,ITfRange *pRange,ITfRange **ppNewRange,BOOL *pfAccepted) {
    return This->lpVtbl->QueryRange(This,pRange,ppNewRange,pfAccepted);
}
static inline HRESULT ITfFnLMProcessor_QueryLangID(ITfFnLMProcessor* This,LANGID langid,BOOL *pfAccepted) {
    return This->lpVtbl->QueryLangID(This,langid,pfAccepted);
}
static inline HRESULT ITfFnLMProcessor_GetReconversion(ITfFnLMProcessor* This,ITfRange *pRange,ITfCandidateList **ppCandList) {
    return This->lpVtbl->GetReconversion(This,pRange,ppCandList);
}
static inline HRESULT ITfFnLMProcessor_Reconvert(ITfFnLMProcessor* This,ITfRange *pRange) {
    return This->lpVtbl->Reconvert(This,pRange);
}
static inline HRESULT ITfFnLMProcessor_QueryKey(ITfFnLMProcessor* This,BOOL fUp,WPARAM vKey,LPARAM lparamKeydata,BOOL *pfInterested) {
    return This->lpVtbl->QueryKey(This,fUp,vKey,lparamKeydata,pfInterested);
}
static inline HRESULT ITfFnLMProcessor_InvokeKey(ITfFnLMProcessor* This,BOOL fUp,WPARAM vKey,LPARAM lparamKeyData) {
    return This->lpVtbl->InvokeKey(This,fUp,vKey,lparamKeyData);
}
static inline HRESULT ITfFnLMProcessor_InvokeFunc(ITfFnLMProcessor* This,ITfContext *pic,REFGUID refguidFunc) {
    return This->lpVtbl->InvokeFunc(This,pic,refguidFunc);
}
#endif
#endif

#endif


#endif  /* __ITfFnLMProcessor_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnLangProfileUtil interface
 */
#ifndef __ITfFnLangProfileUtil_INTERFACE_DEFINED__
#define __ITfFnLangProfileUtil_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnLangProfileUtil, 0xa87a8574, 0xa6c1, 0x4e15, 0x99,0xf0, 0x3d,0x39,0x65,0xf5,0x48,0xeb);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("a87a8574-a6c1-4e15-99f0-3d3965f548eb")
ITfFnLangProfileUtil : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE RegisterActiveProfiles(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE IsProfileAvailableForLang(
        LANGID langid,
        BOOL *pfAvailable) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnLangProfileUtil, 0xa87a8574, 0xa6c1, 0x4e15, 0x99,0xf0, 0x3d,0x39,0x65,0xf5,0x48,0xeb)
#endif
#else
typedef struct ITfFnLangProfileUtilVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnLangProfileUtil *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnLangProfileUtil *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnLangProfileUtil *This);

    /*** ITfFnLangProfileUtil methods ***/
    HRESULT (STDMETHODCALLTYPE *RegisterActiveProfiles)(
        ITfFnLangProfileUtil *This);

    HRESULT (STDMETHODCALLTYPE *IsProfileAvailableForLang)(
        ITfFnLangProfileUtil *This,
        LANGID langid,
        BOOL *pfAvailable);

    END_INTERFACE
} ITfFnLangProfileUtilVtbl;

interface ITfFnLangProfileUtil {
    CONST_VTBL ITfFnLangProfileUtilVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnLangProfileUtil_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnLangProfileUtil_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnLangProfileUtil_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnLangProfileUtil methods ***/
#define ITfFnLangProfileUtil_RegisterActiveProfiles(This) (This)->lpVtbl->RegisterActiveProfiles(This)
#define ITfFnLangProfileUtil_IsProfileAvailableForLang(This,langid,pfAvailable) (This)->lpVtbl->IsProfileAvailableForLang(This,langid,pfAvailable)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnLangProfileUtil_QueryInterface(ITfFnLangProfileUtil* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnLangProfileUtil_AddRef(ITfFnLangProfileUtil* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnLangProfileUtil_Release(ITfFnLangProfileUtil* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnLangProfileUtil methods ***/
static inline HRESULT ITfFnLangProfileUtil_RegisterActiveProfiles(ITfFnLangProfileUtil* This) {
    return This->lpVtbl->RegisterActiveProfiles(This);
}
static inline HRESULT ITfFnLangProfileUtil_IsProfileAvailableForLang(ITfFnLangProfileUtil* This,LANGID langid,BOOL *pfAvailable) {
    return This->lpVtbl->IsProfileAvailableForLang(This,langid,pfAvailable);
}
#endif
#endif

#endif


#endif  /* __ITfFnLangProfileUtil_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnPlayBack interface
 */
#ifndef __ITfFnPlayBack_INTERFACE_DEFINED__
#define __ITfFnPlayBack_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnPlayBack, 0xa3a416a4, 0x0f64, 0x11d3, 0xb5,0xb7, 0x00,0xc0,0x4f,0xc3,0x24,0xa1);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("a3a416a4-0f64-11d3-b5b7-00c04fc324a1")
ITfFnPlayBack : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE QueryRange(
        ITfRange *pRange,
        ITfRange **ppNewRange,
        BOOL *pfPlayable) = 0;

    virtual HRESULT STDMETHODCALLTYPE Play(
        ITfRange *pRange) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnPlayBack, 0xa3a416a4, 0x0f64, 0x11d3, 0xb5,0xb7, 0x00,0xc0,0x4f,0xc3,0x24,0xa1)
#endif
#else
typedef struct ITfFnPlayBackVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnPlayBack *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnPlayBack *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnPlayBack *This);

    /*** ITfFnPlayBack methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryRange)(
        ITfFnPlayBack *This,
        ITfRange *pRange,
        ITfRange **ppNewRange,
        BOOL *pfPlayable);

    HRESULT (STDMETHODCALLTYPE *Play)(
        ITfFnPlayBack *This,
        ITfRange *pRange);

    END_INTERFACE
} ITfFnPlayBackVtbl;

interface ITfFnPlayBack {
    CONST_VTBL ITfFnPlayBackVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnPlayBack_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnPlayBack_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnPlayBack_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnPlayBack methods ***/
#define ITfFnPlayBack_QueryRange(This,pRange,ppNewRange,pfPlayable) (This)->lpVtbl->QueryRange(This,pRange,ppNewRange,pfPlayable)
#define ITfFnPlayBack_Play(This,pRange) (This)->lpVtbl->Play(This,pRange)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnPlayBack_QueryInterface(ITfFnPlayBack* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnPlayBack_AddRef(ITfFnPlayBack* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnPlayBack_Release(ITfFnPlayBack* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnPlayBack methods ***/
static inline HRESULT ITfFnPlayBack_QueryRange(ITfFnPlayBack* This,ITfRange *pRange,ITfRange **ppNewRange,BOOL *pfPlayable) {
    return This->lpVtbl->QueryRange(This,pRange,ppNewRange,pfPlayable);
}
static inline HRESULT ITfFnPlayBack_Play(ITfFnPlayBack* This,ITfRange *pRange) {
    return This->lpVtbl->Play(This,pRange);
}
#endif
#endif

#endif


#endif  /* __ITfFnPlayBack_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnPropertyUIStatus interface
 */
#ifndef __ITfFnPropertyUIStatus_INTERFACE_DEFINED__
#define __ITfFnPropertyUIStatus_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnPropertyUIStatus, 0x2338ac6e, 0x2b9d, 0x44c0, 0xa7,0x5e, 0xee,0x64,0xf2,0x56,0xb3,0xbd);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("2338ac6e-2b9d-44c0-a75e-ee64f256b3bd")
ITfFnPropertyUIStatus : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE GetStatus(
        REFGUID refguidProp,
        DWORD *pdw) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetStatus(
        REFGUID refguidProp,
        DWORD dw) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnPropertyUIStatus, 0x2338ac6e, 0x2b9d, 0x44c0, 0xa7,0x5e, 0xee,0x64,0xf2,0x56,0xb3,0xbd)
#endif
#else
typedef struct ITfFnPropertyUIStatusVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnPropertyUIStatus *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnPropertyUIStatus *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnPropertyUIStatus *This);

    /*** ITfFnPropertyUIStatus methods ***/
    HRESULT (STDMETHODCALLTYPE *GetStatus)(
        ITfFnPropertyUIStatus *This,
        REFGUID refguidProp,
        DWORD *pdw);

    HRESULT (STDMETHODCALLTYPE *SetStatus)(
        ITfFnPropertyUIStatus *This,
        REFGUID refguidProp,
        DWORD dw);

    END_INTERFACE
} ITfFnPropertyUIStatusVtbl;

interface ITfFnPropertyUIStatus {
    CONST_VTBL ITfFnPropertyUIStatusVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnPropertyUIStatus_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnPropertyUIStatus_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnPropertyUIStatus_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnPropertyUIStatus methods ***/
#define ITfFnPropertyUIStatus_GetStatus(This,refguidProp,pdw) (This)->lpVtbl->GetStatus(This,refguidProp,pdw)
#define ITfFnPropertyUIStatus_SetStatus(This,refguidProp,dw) (This)->lpVtbl->SetStatus(This,refguidProp,dw)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnPropertyUIStatus_QueryInterface(ITfFnPropertyUIStatus* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnPropertyUIStatus_AddRef(ITfFnPropertyUIStatus* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnPropertyUIStatus_Release(ITfFnPropertyUIStatus* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnPropertyUIStatus methods ***/
static inline HRESULT ITfFnPropertyUIStatus_GetStatus(ITfFnPropertyUIStatus* This,REFGUID refguidProp,DWORD *pdw) {
    return This->lpVtbl->GetStatus(This,refguidProp,pdw);
}
static inline HRESULT ITfFnPropertyUIStatus_SetStatus(ITfFnPropertyUIStatus* This,REFGUID refguidProp,DWORD dw) {
    return This->lpVtbl->SetStatus(This,refguidProp,dw);
}
#endif
#endif

#endif


#endif  /* __ITfFnPropertyUIStatus_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnReconversion interface
 */
#ifndef __ITfFnReconversion_INTERFACE_DEFINED__
#define __ITfFnReconversion_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnReconversion, 0x4cea93c0, 0x0a58, 0x11d3, 0x8d,0xf0, 0x00,0x10,0x5a,0x27,0x99,0xb5);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("4cea93c0-0a58-11d3-8df0-00105a2799b5")
ITfFnReconversion : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE QueryRange(
        ITfRange *pRange,
        ITfRange **ppNewRange,
        BOOL *pfConvertable) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetReconversion(
        ITfRange *pRange,
        ITfCandidateList **ppCandList) = 0;

    virtual HRESULT STDMETHODCALLTYPE Reconvert(
        ITfRange *pRange) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnReconversion, 0x4cea93c0, 0x0a58, 0x11d3, 0x8d,0xf0, 0x00,0x10,0x5a,0x27,0x99,0xb5)
#endif
#else
typedef struct ITfFnReconversionVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnReconversion *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnReconversion *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnReconversion *This);

    /*** ITfFnReconversion methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryRange)(
        ITfFnReconversion *This,
        ITfRange *pRange,
        ITfRange **ppNewRange,
        BOOL *pfConvertable);

    HRESULT (STDMETHODCALLTYPE *GetReconversion)(
        ITfFnReconversion *This,
        ITfRange *pRange,
        ITfCandidateList **ppCandList);

    HRESULT (STDMETHODCALLTYPE *Reconvert)(
        ITfFnReconversion *This,
        ITfRange *pRange);

    END_INTERFACE
} ITfFnReconversionVtbl;

interface ITfFnReconversion {
    CONST_VTBL ITfFnReconversionVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnReconversion_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnReconversion_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnReconversion_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnReconversion methods ***/
#define ITfFnReconversion_QueryRange(This,pRange,ppNewRange,pfConvertable) (This)->lpVtbl->QueryRange(This,pRange,ppNewRange,pfConvertable)
#define ITfFnReconversion_GetReconversion(This,pRange,ppCandList) (This)->lpVtbl->GetReconversion(This,pRange,ppCandList)
#define ITfFnReconversion_Reconvert(This,pRange) (This)->lpVtbl->Reconvert(This,pRange)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnReconversion_QueryInterface(ITfFnReconversion* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnReconversion_AddRef(ITfFnReconversion* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnReconversion_Release(ITfFnReconversion* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnReconversion methods ***/
static inline HRESULT ITfFnReconversion_QueryRange(ITfFnReconversion* This,ITfRange *pRange,ITfRange **ppNewRange,BOOL *pfConvertable) {
    return This->lpVtbl->QueryRange(This,pRange,ppNewRange,pfConvertable);
}
static inline HRESULT ITfFnReconversion_GetReconversion(ITfFnReconversion* This,ITfRange *pRange,ITfCandidateList **ppCandList) {
    return This->lpVtbl->GetReconversion(This,pRange,ppCandList);
}
static inline HRESULT ITfFnReconversion_Reconvert(ITfFnReconversion* This,ITfRange *pRange) {
    return This->lpVtbl->Reconvert(This,pRange);
}
#endif
#endif

#endif


#endif  /* __ITfFnReconversion_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnSearchCandidateProvider interface
 */
#ifndef __ITfFnSearchCandidateProvider_INTERFACE_DEFINED__
#define __ITfFnSearchCandidateProvider_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnSearchCandidateProvider, 0x87a2ad8f, 0xf27b, 0x4920, 0x85,0x01, 0x67,0x60,0x22,0x80,0x17,0x5d);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("87a2ad8f-f27b-4920-8501-67602280175d")
ITfFnSearchCandidateProvider : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE GetSearchCandidates(
        BSTR bstrQuery,
        BSTR bstrApplicationId,
        ITfCandidateList **pplist) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetResult(
        BSTR bstrQuery,
        BSTR bstrApplicationID,
        BSTR bstrResult) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnSearchCandidateProvider, 0x87a2ad8f, 0xf27b, 0x4920, 0x85,0x01, 0x67,0x60,0x22,0x80,0x17,0x5d)
#endif
#else
typedef struct ITfFnSearchCandidateProviderVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnSearchCandidateProvider *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnSearchCandidateProvider *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnSearchCandidateProvider *This);

    /*** ITfFnSearchCandidateProvider methods ***/
    HRESULT (STDMETHODCALLTYPE *GetSearchCandidates)(
        ITfFnSearchCandidateProvider *This,
        BSTR bstrQuery,
        BSTR bstrApplicationId,
        ITfCandidateList **pplist);

    HRESULT (STDMETHODCALLTYPE *SetResult)(
        ITfFnSearchCandidateProvider *This,
        BSTR bstrQuery,
        BSTR bstrApplicationID,
        BSTR bstrResult);

    END_INTERFACE
} ITfFnSearchCandidateProviderVtbl;

interface ITfFnSearchCandidateProvider {
    CONST_VTBL ITfFnSearchCandidateProviderVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnSearchCandidateProvider_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnSearchCandidateProvider_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnSearchCandidateProvider_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnSearchCandidateProvider methods ***/
#define ITfFnSearchCandidateProvider_GetSearchCandidates(This,bstrQuery,bstrApplicationId,pplist) (This)->lpVtbl->GetSearchCandidates(This,bstrQuery,bstrApplicationId,pplist)
#define ITfFnSearchCandidateProvider_SetResult(This,bstrQuery,bstrApplicationID,bstrResult) (This)->lpVtbl->SetResult(This,bstrQuery,bstrApplicationID,bstrResult)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnSearchCandidateProvider_QueryInterface(ITfFnSearchCandidateProvider* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnSearchCandidateProvider_AddRef(ITfFnSearchCandidateProvider* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnSearchCandidateProvider_Release(ITfFnSearchCandidateProvider* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnSearchCandidateProvider methods ***/
static inline HRESULT ITfFnSearchCandidateProvider_GetSearchCandidates(ITfFnSearchCandidateProvider* This,BSTR bstrQuery,BSTR bstrApplicationId,ITfCandidateList **pplist) {
    return This->lpVtbl->GetSearchCandidates(This,bstrQuery,bstrApplicationId,pplist);
}
static inline HRESULT ITfFnSearchCandidateProvider_SetResult(ITfFnSearchCandidateProvider* This,BSTR bstrQuery,BSTR bstrApplicationID,BSTR bstrResult) {
    return This->lpVtbl->SetResult(This,bstrQuery,bstrApplicationID,bstrResult);
}
#endif
#endif

#endif


#endif  /* __ITfFnSearchCandidateProvider_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfFnShowHelp interface
 */
#ifndef __ITfFnShowHelp_INTERFACE_DEFINED__
#define __ITfFnShowHelp_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfFnShowHelp, 0x5ab1d30c, 0x094d, 0x4c29, 0x8e,0xa5, 0x0b,0xf5,0x9b,0xe8,0x7b,0xf3);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("5ab1d30c-094d-4c29-8ea5-0bf59be87bf3")
ITfFnShowHelp : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Show(
        HWND hwndParent) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfFnShowHelp, 0x5ab1d30c, 0x094d, 0x4c29, 0x8e,0xa5, 0x0b,0xf5,0x9b,0xe8,0x7b,0xf3)
#endif
#else
typedef struct ITfFnShowHelpVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfFnShowHelp *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfFnShowHelp *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfFnShowHelp *This);

    /*** ITfFnShowHelp methods ***/
    HRESULT (STDMETHODCALLTYPE *Show)(
        ITfFnShowHelp *This,
        HWND hwndParent);

    END_INTERFACE
} ITfFnShowHelpVtbl;

interface ITfFnShowHelp {
    CONST_VTBL ITfFnShowHelpVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfFnShowHelp_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfFnShowHelp_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfFnShowHelp_Release(This) (This)->lpVtbl->Release(This)
/*** ITfFnShowHelp methods ***/
#define ITfFnShowHelp_Show(This,hwndParent) (This)->lpVtbl->Show(This,hwndParent)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfFnShowHelp_QueryInterface(ITfFnShowHelp* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfFnShowHelp_AddRef(ITfFnShowHelp* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfFnShowHelp_Release(ITfFnShowHelp* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfFnShowHelp methods ***/
static inline HRESULT ITfFnShowHelp_Show(ITfFnShowHelp* This,HWND hwndParent) {
    return This->lpVtbl->Show(This,hwndParent);
}
#endif
#endif

#endif


#endif  /* __ITfFnShowHelp_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfIntegratableCandidateListUIElement interface
 */
#ifndef __ITfIntegratableCandidateListUIElement_INTERFACE_DEFINED__
#define __ITfIntegratableCandidateListUIElement_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfIntegratableCandidateListUIElement, 0x5ab1d30c, 0x094d, 0x4c29, 0x8e,0xa5, 0x0b,0xf5,0x9b,0xe8,0x7b,0xf3);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("5ab1d30c-094d-4c29-8ea5-0bf59be87bf3")
ITfIntegratableCandidateListUIElement : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE SetIntegrationStyle(
        GUID guidIntegrationStyle) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetSelectionStyle(
        TfIntegratableCandidateListSelectionStyle *ptfSelectionStyle) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnKeyDown(
        WPARAM wParam,
        LPARAM lParam,
        BOOL *pfEaten) = 0;

    virtual HRESULT STDMETHODCALLTYPE ShowCandidateNumbers(
        BOOL *pfShow) = 0;

    virtual HRESULT STDMETHODCALLTYPE FinalizeExactCompositionString(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfIntegratableCandidateListUIElement, 0x5ab1d30c, 0x094d, 0x4c29, 0x8e,0xa5, 0x0b,0xf5,0x9b,0xe8,0x7b,0xf3)
#endif
#else
typedef struct ITfIntegratableCandidateListUIElementVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfIntegratableCandidateListUIElement *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfIntegratableCandidateListUIElement *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfIntegratableCandidateListUIElement *This);

    /*** ITfIntegratableCandidateListUIElement methods ***/
    HRESULT (STDMETHODCALLTYPE *SetIntegrationStyle)(
        ITfIntegratableCandidateListUIElement *This,
        GUID guidIntegrationStyle);

    HRESULT (STDMETHODCALLTYPE *GetSelectionStyle)(
        ITfIntegratableCandidateListUIElement *This,
        TfIntegratableCandidateListSelectionStyle *ptfSelectionStyle);

    HRESULT (STDMETHODCALLTYPE *OnKeyDown)(
        ITfIntegratableCandidateListUIElement *This,
        WPARAM wParam,
        LPARAM lParam,
        BOOL *pfEaten);

    HRESULT (STDMETHODCALLTYPE *ShowCandidateNumbers)(
        ITfIntegratableCandidateListUIElement *This,
        BOOL *pfShow);

    HRESULT (STDMETHODCALLTYPE *FinalizeExactCompositionString)(
        ITfIntegratableCandidateListUIElement *This);

    END_INTERFACE
} ITfIntegratableCandidateListUIElementVtbl;

interface ITfIntegratableCandidateListUIElement {
    CONST_VTBL ITfIntegratableCandidateListUIElementVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfIntegratableCandidateListUIElement_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfIntegratableCandidateListUIElement_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfIntegratableCandidateListUIElement_Release(This) (This)->lpVtbl->Release(This)
/*** ITfIntegratableCandidateListUIElement methods ***/
#define ITfIntegratableCandidateListUIElement_SetIntegrationStyle(This,guidIntegrationStyle) (This)->lpVtbl->SetIntegrationStyle(This,guidIntegrationStyle)
#define ITfIntegratableCandidateListUIElement_GetSelectionStyle(This,ptfSelectionStyle) (This)->lpVtbl->GetSelectionStyle(This,ptfSelectionStyle)
#define ITfIntegratableCandidateListUIElement_OnKeyDown(This,wParam,lParam,pfEaten) (This)->lpVtbl->OnKeyDown(This,wParam,lParam,pfEaten)
#define ITfIntegratableCandidateListUIElement_ShowCandidateNumbers(This,pfShow) (This)->lpVtbl->ShowCandidateNumbers(This,pfShow)
#define ITfIntegratableCandidateListUIElement_FinalizeExactCompositionString(This) (This)->lpVtbl->FinalizeExactCompositionString(This)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfIntegratableCandidateListUIElement_QueryInterface(ITfIntegratableCandidateListUIElement* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfIntegratableCandidateListUIElement_AddRef(ITfIntegratableCandidateListUIElement* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfIntegratableCandidateListUIElement_Release(ITfIntegratableCandidateListUIElement* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfIntegratableCandidateListUIElement methods ***/
static inline HRESULT ITfIntegratableCandidateListUIElement_SetIntegrationStyle(ITfIntegratableCandidateListUIElement* This,GUID guidIntegrationStyle) {
    return This->lpVtbl->SetIntegrationStyle(This,guidIntegrationStyle);
}
static inline HRESULT ITfIntegratableCandidateListUIElement_GetSelectionStyle(ITfIntegratableCandidateListUIElement* This,TfIntegratableCandidateListSelectionStyle *ptfSelectionStyle) {
    return This->lpVtbl->GetSelectionStyle(This,ptfSelectionStyle);
}
static inline HRESULT ITfIntegratableCandidateListUIElement_OnKeyDown(ITfIntegratableCandidateListUIElement* This,WPARAM wParam,LPARAM lParam,BOOL *pfEaten) {
    return This->lpVtbl->OnKeyDown(This,wParam,lParam,pfEaten);
}
static inline HRESULT ITfIntegratableCandidateListUIElement_ShowCandidateNumbers(ITfIntegratableCandidateListUIElement* This,BOOL *pfShow) {
    return This->lpVtbl->ShowCandidateNumbers(This,pfShow);
}
static inline HRESULT ITfIntegratableCandidateListUIElement_FinalizeExactCompositionString(ITfIntegratableCandidateListUIElement* This) {
    return This->lpVtbl->FinalizeExactCompositionString(This);
}
#endif
#endif

#endif


#endif  /* __ITfIntegratableCandidateListUIElement_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfLMLattice interface
 */
#ifndef __ITfLMLattice_INTERFACE_DEFINED__
#define __ITfLMLattice_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfLMLattice, 0xd4236675, 0xa5bf, 0x4570, 0x9d,0x42, 0x5d,0x6d,0x7b,0x02,0xd5,0x9b);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("d4236675-a5bf-4570-9d42-5d6d7b02d59b")
ITfLMLattice : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE QueryType(
        REFGUID rguidType,
        BOOL *pfSupported) = 0;

    virtual HRESULT STDMETHODCALLTYPE EnumLatticeElements(
        DWORD dwFrameStart,
        REFGUID rguidType,
        IEnumTfLatticeElements **ppEnum) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfLMLattice, 0xd4236675, 0xa5bf, 0x4570, 0x9d,0x42, 0x5d,0x6d,0x7b,0x02,0xd5,0x9b)
#endif
#else
typedef struct ITfLMLatticeVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfLMLattice *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfLMLattice *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfLMLattice *This);

    /*** ITfLMLattice methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryType)(
        ITfLMLattice *This,
        REFGUID rguidType,
        BOOL *pfSupported);

    HRESULT (STDMETHODCALLTYPE *EnumLatticeElements)(
        ITfLMLattice *This,
        DWORD dwFrameStart,
        REFGUID rguidType,
        IEnumTfLatticeElements **ppEnum);

    END_INTERFACE
} ITfLMLatticeVtbl;

interface ITfLMLattice {
    CONST_VTBL ITfLMLatticeVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfLMLattice_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfLMLattice_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfLMLattice_Release(This) (This)->lpVtbl->Release(This)
/*** ITfLMLattice methods ***/
#define ITfLMLattice_QueryType(This,rguidType,pfSupported) (This)->lpVtbl->QueryType(This,rguidType,pfSupported)
#define ITfLMLattice_EnumLatticeElements(This,dwFrameStart,rguidType,ppEnum) (This)->lpVtbl->EnumLatticeElements(This,dwFrameStart,rguidType,ppEnum)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfLMLattice_QueryInterface(ITfLMLattice* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfLMLattice_AddRef(ITfLMLattice* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfLMLattice_Release(ITfLMLattice* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfLMLattice methods ***/
static inline HRESULT ITfLMLattice_QueryType(ITfLMLattice* This,REFGUID rguidType,BOOL *pfSupported) {
    return This->lpVtbl->QueryType(This,rguidType,pfSupported);
}
static inline HRESULT ITfLMLattice_EnumLatticeElements(ITfLMLattice* This,DWORD dwFrameStart,REFGUID rguidType,IEnumTfLatticeElements **ppEnum) {
    return This->lpVtbl->EnumLatticeElements(This,dwFrameStart,rguidType,ppEnum);
}
#endif
#endif

#endif


#endif  /* __ITfLMLattice_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IUIManagerEventSink interface
 */
#ifndef __IUIManagerEventSink_INTERFACE_DEFINED__
#define __IUIManagerEventSink_INTERFACE_DEFINED__

DEFINE_GUID(IID_IUIManagerEventSink, 0xcd91d690, 0xa7e8, 0x4265, 0x9b,0x38, 0x8b,0xb3,0xbb,0xab,0xa7,0xde);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("cd91d690-a7e8-4265-9b38-8bb3bbaba7de")
IUIManagerEventSink : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE OnWindowOpening(
        RECT *prcBounds) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnWindowOpened(
        RECT *prcBounds) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnWindowUpdating(
        RECT *prcUpdatedBounds) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnWindowUpdated(
        RECT *prcUpdatedBounds) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnWindowClosing(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnWindowClosed(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IUIManagerEventSink, 0xcd91d690, 0xa7e8, 0x4265, 0x9b,0x38, 0x8b,0xb3,0xbb,0xab,0xa7,0xde)
#endif
#else
typedef struct IUIManagerEventSinkVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IUIManagerEventSink *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IUIManagerEventSink *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IUIManagerEventSink *This);

    /*** IUIManagerEventSink methods ***/
    HRESULT (STDMETHODCALLTYPE *OnWindowOpening)(
        IUIManagerEventSink *This,
        RECT *prcBounds);

    HRESULT (STDMETHODCALLTYPE *OnWindowOpened)(
        IUIManagerEventSink *This,
        RECT *prcBounds);

    HRESULT (STDMETHODCALLTYPE *OnWindowUpdating)(
        IUIManagerEventSink *This,
        RECT *prcUpdatedBounds);

    HRESULT (STDMETHODCALLTYPE *OnWindowUpdated)(
        IUIManagerEventSink *This,
        RECT *prcUpdatedBounds);

    HRESULT (STDMETHODCALLTYPE *OnWindowClosing)(
        IUIManagerEventSink *This);

    HRESULT (STDMETHODCALLTYPE *OnWindowClosed)(
        IUIManagerEventSink *This);

    END_INTERFACE
} IUIManagerEventSinkVtbl;

interface IUIManagerEventSink {
    CONST_VTBL IUIManagerEventSinkVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IUIManagerEventSink_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IUIManagerEventSink_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IUIManagerEventSink_Release(This) (This)->lpVtbl->Release(This)
/*** IUIManagerEventSink methods ***/
#define IUIManagerEventSink_OnWindowOpening(This,prcBounds) (This)->lpVtbl->OnWindowOpening(This,prcBounds)
#define IUIManagerEventSink_OnWindowOpened(This,prcBounds) (This)->lpVtbl->OnWindowOpened(This,prcBounds)
#define IUIManagerEventSink_OnWindowUpdating(This,prcUpdatedBounds) (This)->lpVtbl->OnWindowUpdating(This,prcUpdatedBounds)
#define IUIManagerEventSink_OnWindowUpdated(This,prcUpdatedBounds) (This)->lpVtbl->OnWindowUpdated(This,prcUpdatedBounds)
#define IUIManagerEventSink_OnWindowClosing(This) (This)->lpVtbl->OnWindowClosing(This)
#define IUIManagerEventSink_OnWindowClosed(This) (This)->lpVtbl->OnWindowClosed(This)
#else
/*** IUnknown methods ***/
static inline HRESULT IUIManagerEventSink_QueryInterface(IUIManagerEventSink* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IUIManagerEventSink_AddRef(IUIManagerEventSink* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IUIManagerEventSink_Release(IUIManagerEventSink* This) {
    return This->lpVtbl->Release(This);
}
/*** IUIManagerEventSink methods ***/
static inline HRESULT IUIManagerEventSink_OnWindowOpening(IUIManagerEventSink* This,RECT *prcBounds) {
    return This->lpVtbl->OnWindowOpening(This,prcBounds);
}
static inline HRESULT IUIManagerEventSink_OnWindowOpened(IUIManagerEventSink* This,RECT *prcBounds) {
    return This->lpVtbl->OnWindowOpened(This,prcBounds);
}
static inline HRESULT IUIManagerEventSink_OnWindowUpdating(IUIManagerEventSink* This,RECT *prcUpdatedBounds) {
    return This->lpVtbl->OnWindowUpdating(This,prcUpdatedBounds);
}
static inline HRESULT IUIManagerEventSink_OnWindowUpdated(IUIManagerEventSink* This,RECT *prcUpdatedBounds) {
    return This->lpVtbl->OnWindowUpdated(This,prcUpdatedBounds);
}
static inline HRESULT IUIManagerEventSink_OnWindowClosing(IUIManagerEventSink* This) {
    return This->lpVtbl->OnWindowClosing(This);
}
static inline HRESULT IUIManagerEventSink_OnWindowClosed(IUIManagerEventSink* This) {
    return This->lpVtbl->OnWindowClosed(This);
}
#endif
#endif

#endif


#endif  /* __IUIManagerEventSink_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER BSTR_UserSize     (ULONG *, ULONG, BSTR *);
unsigned char * __RPC_USER BSTR_UserMarshal  (ULONG *, unsigned char *, BSTR *);
unsigned char * __RPC_USER BSTR_UserUnmarshal(ULONG *, unsigned char *, BSTR *);
void            __RPC_USER BSTR_UserFree     (ULONG *, BSTR *);
ULONG           __RPC_USER HWND_UserSize     (ULONG *, ULONG, HWND *);
unsigned char * __RPC_USER HWND_UserMarshal  (ULONG *, unsigned char *, HWND *);
unsigned char * __RPC_USER HWND_UserUnmarshal(ULONG *, unsigned char *, HWND *);
void            __RPC_USER HWND_UserFree     (ULONG *, HWND *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __ctffunc_h__ */
