/*** Autogenerated by WIDL <undefined version> from ctfutb.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __ctfutb_h__
#define __ctfutb_h__

/* Forward declarations */

#ifndef __ITfLangBarMgr_FWD_DEFINED__
#define __ITfLangBarMgr_FWD_DEFINED__
typedef interface ITfLangBarMgr ITfLangBarMgr;
#ifdef __cplusplus
interface ITfLangBarMgr;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarEventSink_FWD_DEFINED__
#define __ITfLangBarEventSink_FWD_DEFINED__
typedef interface ITfLangBarEventSink ITfLangBarEventSink;
#ifdef __cplusplus
interface ITfLangBarEventSink;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemMgr_FWD_DEFINED__
#define __ITfLangBarItemMgr_FWD_DEFINED__
typedef interface ITfLangBarItemMgr ITfLangBarItemMgr;
#ifdef __cplusplus
interface ITfLangBarItemMgr;
#endif /* __cplusplus */
#endif

#ifndef __IEnumTfLangBarItems_FWD_DEFINED__
#define __IEnumTfLangBarItems_FWD_DEFINED__
typedef interface IEnumTfLangBarItems IEnumTfLangBarItems;
#ifdef __cplusplus
interface IEnumTfLangBarItems;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItem_FWD_DEFINED__
#define __ITfLangBarItem_FWD_DEFINED__
typedef interface ITfLangBarItem ITfLangBarItem;
#ifdef __cplusplus
interface ITfLangBarItem;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemSink_FWD_DEFINED__
#define __ITfLangBarItemSink_FWD_DEFINED__
typedef interface ITfLangBarItemSink ITfLangBarItemSink;
#ifdef __cplusplus
interface ITfLangBarItemSink;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemBalloon_FWD_DEFINED__
#define __ITfLangBarItemBalloon_FWD_DEFINED__
typedef interface ITfLangBarItemBalloon ITfLangBarItemBalloon;
#ifdef __cplusplus
interface ITfLangBarItemBalloon;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemBitmap_FWD_DEFINED__
#define __ITfLangBarItemBitmap_FWD_DEFINED__
typedef interface ITfLangBarItemBitmap ITfLangBarItemBitmap;
#ifdef __cplusplus
interface ITfLangBarItemBitmap;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemBitmapButton_FWD_DEFINED__
#define __ITfLangBarItemBitmapButton_FWD_DEFINED__
typedef interface ITfLangBarItemBitmapButton ITfLangBarItemBitmapButton;
#ifdef __cplusplus
interface ITfLangBarItemBitmapButton;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemButton_FWD_DEFINED__
#define __ITfLangBarItemButton_FWD_DEFINED__
typedef interface ITfLangBarItemButton ITfLangBarItemButton;
#ifdef __cplusplus
interface ITfLangBarItemButton;
#endif /* __cplusplus */
#endif

#ifndef __ITfMenu_FWD_DEFINED__
#define __ITfMenu_FWD_DEFINED__
typedef interface ITfMenu ITfMenu;
#ifdef __cplusplus
interface ITfMenu;
#endif /* __cplusplus */
#endif

#ifndef __ITfSystemDeviceTypeLangBarItem_FWD_DEFINED__
#define __ITfSystemDeviceTypeLangBarItem_FWD_DEFINED__
typedef interface ITfSystemDeviceTypeLangBarItem ITfSystemDeviceTypeLangBarItem;
#ifdef __cplusplus
interface ITfSystemDeviceTypeLangBarItem;
#endif /* __cplusplus */
#endif

#ifndef __ITfSystemLangBarItem_FWD_DEFINED__
#define __ITfSystemLangBarItem_FWD_DEFINED__
typedef interface ITfSystemLangBarItem ITfSystemLangBarItem;
#ifdef __cplusplus
interface ITfSystemLangBarItem;
#endif /* __cplusplus */
#endif

#ifndef __ITfSystemLangBarItemSink_FWD_DEFINED__
#define __ITfSystemLangBarItemSink_FWD_DEFINED__
typedef interface ITfSystemLangBarItemSink ITfSystemLangBarItemSink;
#ifdef __cplusplus
interface ITfSystemLangBarItemSink;
#endif /* __cplusplus */
#endif

#ifndef __ITfSystemLangBarItemText_FWD_DEFINED__
#define __ITfSystemLangBarItemText_FWD_DEFINED__
typedef interface ITfSystemLangBarItemText ITfSystemLangBarItemText;
#ifdef __cplusplus
interface ITfSystemLangBarItemText;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <oaidl.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TF_FLOATINGLANGBAR_WNDTITLEW L"TF_FloatingLangBar_WndTitle"
#define TF_FLOATINGLANGBAR_WNDTITLEA "TF_FloatingLangBar_WndTitle"
#ifdef UNICODE
#define TF_FLOATINGLANGBAR_WNDTITLE TF_FLOATINGLANGBAR_WNDTITLEW
#else
#define TF_FLOATINGLANGBAR_WNDTITLE TF_FLOATINGLANGBAR_WNDTITLEA
#endif
#define TF_LBI_ICON      0x00000001
#define TF_LBI_TEXT      0x00000002
#define TF_LBI_TOOLTIP   0x00000004
#define TF_LBI_BITMAP    0x00000008
#define TF_LBI_BALLOON   0x00000010
#define TF_LBI_CUSTOMUI  0x00000020
#define TF_LBI_BTNALL    (TF_LBI_TEXT | TF_LBI_ICON | TF_LBI_TOOLTIP)
#define TF_LBI_BMPBTNALL (TF_LBI_TEXT | TF_LBI_BITMAP | TF_LBI_TOOLTIP)
#define TF_LBI_BMPALL    (TF_LBI_BITMAP | TF_LBI_TOOLTIP)
#define TF_LBI_STATUS    0x00010000
#define TF_LBI_STYLE_HIDDENSTATUSCONTROL 0x00000001
#define TF_LBI_STYLE_SHOWNINTRAY         0x00000002
#define TF_LBI_STYLE_HIDEONNOOTHERITEMS  0x00000004
#define TF_LBI_STYLE_SHOWNINTRAYONLY     0x00000008
#define TF_LBI_STYLE_HIDDENBYDEFAULT     0x00000010
#define TF_LBI_STYLE_TEXTCOLORICON       0x00000020
#define TF_LBI_STYLE_BTN_BUTTON          0x00010000
#define TF_LBI_STYLE_BTN_MENU            0x00020000
#define TF_LBI_STYLE_BTN_TOGGLE          0x00040000
#define TF_LBI_STATUS_HIDDEN      0x00000001
#define TF_LBI_STATUS_DISABLED    0x00000002
#define TF_LBI_STATUS_BTN_TOGGLED 0x00010000
#define TF_LBI_BMPF_VERTICAL 0x00000001
#define TF_SFT_SHOWNORMAL              0x00000001
#define TF_SFT_DOCK                    0x00000002
#define TF_SFT_MINIMIZED               0x00000004
#define TF_SFT_HIDDEN                  0x00000008
#define TF_SFT_NOTRANSPARENCY          0x00000010
#define TF_SFT_LOWTRANSPARENCY         0x00000020
#define TF_SFT_HIGHTRANSPARENCY        0x00000040
#define TF_SFT_LABELS                  0x00000080
#define TF_SFT_NOLABELS                0x00000100
#define TF_SFT_EXTRAICONSONMINIMIZED   0x00000200
#define TF_SFT_NOEXTRAICONSONMINIMIZED 0x00000400
#define TF_SFT_DESKBAND                0x00000800
#define TF_INVALIDMENUITEM (UINT)(-1)
#define TF_DTLBI_USEPROFILEICON         0x00000001
typedef enum __WIDL_ctfutb_generated_name_0000000D {
    TF_LBI_CLK_RIGHT = 1,
    TF_LBI_CLK_LEFT = 2
} TfLBIClick;
#ifndef __ITfLangBarEventSink_FWD_DEFINED__
#define __ITfLangBarEventSink_FWD_DEFINED__
typedef interface ITfLangBarEventSink ITfLangBarEventSink;
#ifdef __cplusplus
interface ITfLangBarEventSink;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemMgr_FWD_DEFINED__
#define __ITfLangBarItemMgr_FWD_DEFINED__
typedef interface ITfLangBarItemMgr ITfLangBarItemMgr;
#ifdef __cplusplus
interface ITfLangBarItemMgr;
#endif /* __cplusplus */
#endif

#ifndef __ITfInputProcessorProfiles_FWD_DEFINED__
#define __ITfInputProcessorProfiles_FWD_DEFINED__
typedef interface ITfInputProcessorProfiles ITfInputProcessorProfiles;
#ifdef __cplusplus
interface ITfInputProcessorProfiles;
#endif /* __cplusplus */
#endif

#ifndef __IEnumTfLangBarItems_FWD_DEFINED__
#define __IEnumTfLangBarItems_FWD_DEFINED__
typedef interface IEnumTfLangBarItems IEnumTfLangBarItems;
#ifdef __cplusplus
interface IEnumTfLangBarItems;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItem_FWD_DEFINED__
#define __ITfLangBarItem_FWD_DEFINED__
typedef interface ITfLangBarItem ITfLangBarItem;
#ifdef __cplusplus
interface ITfLangBarItem;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemSink_FWD_DEFINED__
#define __ITfLangBarItemSink_FWD_DEFINED__
typedef interface ITfLangBarItemSink ITfLangBarItemSink;
#ifdef __cplusplus
interface ITfLangBarItemSink;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemBalloon_FWD_DEFINED__
#define __ITfLangBarItemBalloon_FWD_DEFINED__
typedef interface ITfLangBarItemBalloon ITfLangBarItemBalloon;
#ifdef __cplusplus
interface ITfLangBarItemBalloon;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemBitmap_FWD_DEFINED__
#define __ITfLangBarItemBitmap_FWD_DEFINED__
typedef interface ITfLangBarItemBitmap ITfLangBarItemBitmap;
#ifdef __cplusplus
interface ITfLangBarItemBitmap;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemBitmapButton_FWD_DEFINED__
#define __ITfLangBarItemBitmapButton_FWD_DEFINED__
typedef interface ITfLangBarItemBitmapButton ITfLangBarItemBitmapButton;
#ifdef __cplusplus
interface ITfLangBarItemBitmapButton;
#endif /* __cplusplus */
#endif

#ifndef __ITfLangBarItemButton_FWD_DEFINED__
#define __ITfLangBarItemButton_FWD_DEFINED__
typedef interface ITfLangBarItemButton ITfLangBarItemButton;
#ifdef __cplusplus
interface ITfLangBarItemButton;
#endif /* __cplusplus */
#endif

#ifndef __ITfMenu_FWD_DEFINED__
#define __ITfMenu_FWD_DEFINED__
typedef interface ITfMenu ITfMenu;
#ifdef __cplusplus
interface ITfMenu;
#endif /* __cplusplus */
#endif

#ifndef __ITfSystemDeviceTypeLangBarItem_FWD_DEFINED__
#define __ITfSystemDeviceTypeLangBarItem_FWD_DEFINED__
typedef interface ITfSystemDeviceTypeLangBarItem ITfSystemDeviceTypeLangBarItem;
#ifdef __cplusplus
interface ITfSystemDeviceTypeLangBarItem;
#endif /* __cplusplus */
#endif

#ifndef __ITfSystemLangBarItem_FWD_DEFINED__
#define __ITfSystemLangBarItem_FWD_DEFINED__
typedef interface ITfSystemLangBarItem ITfSystemLangBarItem;
#ifdef __cplusplus
interface ITfSystemLangBarItem;
#endif /* __cplusplus */
#endif

#ifndef __ITfSystemLangBarItemSink_FWD_DEFINED__
#define __ITfSystemLangBarItemSink_FWD_DEFINED__
typedef interface ITfSystemLangBarItemSink ITfSystemLangBarItemSink;
#ifdef __cplusplus
interface ITfSystemLangBarItemSink;
#endif /* __cplusplus */
#endif

#ifndef __ITfSystemLangBarItemText_FWD_DEFINED__
#define __ITfSystemLangBarItemText_FWD_DEFINED__
typedef interface ITfSystemLangBarItemText ITfSystemLangBarItemText;
#ifdef __cplusplus
interface ITfSystemLangBarItemText;
#endif /* __cplusplus */
#endif

/*****************************************************************************
 * ITfLangBarMgr interface
 */
#ifndef __ITfLangBarMgr_INTERFACE_DEFINED__
#define __ITfLangBarMgr_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfLangBarMgr, 0x87955690, 0xe627, 0x11d2, 0x8d,0xdb, 0x00,0x10,0x5a,0x27,0x99,0xb5);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("87955690-e627-11d2-8ddb-00105a2799b5")
ITfLangBarMgr : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE AdviseEventSink(
        ITfLangBarEventSink *pSink,
        HWND hwnd,
        DWORD dwflags,
        DWORD *pdwCookie) = 0;

    virtual HRESULT STDMETHODCALLTYPE UnAdviseEventSink(
        DWORD dwCookie) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetThreadMarshalInterface(
        DWORD dwThreadId,
        DWORD dwType,
        REFIID riid,
        IUnknown **ppunk) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetThreadLangBarItemMgr(
        DWORD dwThreadId,
        ITfLangBarItemMgr **pplbie,
        DWORD *pdwThreadid) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetInputProcessorProfiles(
        DWORD dwThreadId,
        ITfInputProcessorProfiles **ppaip,
        DWORD *pdwThreadid) = 0;

    virtual HRESULT STDMETHODCALLTYPE RestoreLastFocus(
        DWORD *dwThreadId,
        BOOL fPrev) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetModalInput(
        ITfLangBarEventSink *pSink,
        DWORD dwThreadId,
        DWORD dwFlags) = 0;

    virtual HRESULT STDMETHODCALLTYPE ShowFloating(
        DWORD dwFlags) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetShowFloatingStatus(
        DWORD *pdwFlags) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfLangBarMgr, 0x87955690, 0xe627, 0x11d2, 0x8d,0xdb, 0x00,0x10,0x5a,0x27,0x99,0xb5)
#endif
#else
typedef struct ITfLangBarMgrVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfLangBarMgr *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfLangBarMgr *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfLangBarMgr *This);

    /*** ITfLangBarMgr methods ***/
    HRESULT (STDMETHODCALLTYPE *AdviseEventSink)(
        ITfLangBarMgr *This,
        ITfLangBarEventSink *pSink,
        HWND hwnd,
        DWORD dwflags,
        DWORD *pdwCookie);

    HRESULT (STDMETHODCALLTYPE *UnAdviseEventSink)(
        ITfLangBarMgr *This,
        DWORD dwCookie);

    HRESULT (STDMETHODCALLTYPE *GetThreadMarshalInterface)(
        ITfLangBarMgr *This,
        DWORD dwThreadId,
        DWORD dwType,
        REFIID riid,
        IUnknown **ppunk);

    HRESULT (STDMETHODCALLTYPE *GetThreadLangBarItemMgr)(
        ITfLangBarMgr *This,
        DWORD dwThreadId,
        ITfLangBarItemMgr **pplbie,
        DWORD *pdwThreadid);

    HRESULT (STDMETHODCALLTYPE *GetInputProcessorProfiles)(
        ITfLangBarMgr *This,
        DWORD dwThreadId,
        ITfInputProcessorProfiles **ppaip,
        DWORD *pdwThreadid);

    HRESULT (STDMETHODCALLTYPE *RestoreLastFocus)(
        ITfLangBarMgr *This,
        DWORD *dwThreadId,
        BOOL fPrev);

    HRESULT (STDMETHODCALLTYPE *SetModalInput)(
        ITfLangBarMgr *This,
        ITfLangBarEventSink *pSink,
        DWORD dwThreadId,
        DWORD dwFlags);

    HRESULT (STDMETHODCALLTYPE *ShowFloating)(
        ITfLangBarMgr *This,
        DWORD dwFlags);

    HRESULT (STDMETHODCALLTYPE *GetShowFloatingStatus)(
        ITfLangBarMgr *This,
        DWORD *pdwFlags);

    END_INTERFACE
} ITfLangBarMgrVtbl;

interface ITfLangBarMgr {
    CONST_VTBL ITfLangBarMgrVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfLangBarMgr_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfLangBarMgr_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfLangBarMgr_Release(This) (This)->lpVtbl->Release(This)
/*** ITfLangBarMgr methods ***/
#define ITfLangBarMgr_AdviseEventSink(This,pSink,hwnd,dwflags,pdwCookie) (This)->lpVtbl->AdviseEventSink(This,pSink,hwnd,dwflags,pdwCookie)
#define ITfLangBarMgr_UnAdviseEventSink(This,dwCookie) (This)->lpVtbl->UnAdviseEventSink(This,dwCookie)
#define ITfLangBarMgr_GetThreadMarshalInterface(This,dwThreadId,dwType,riid,ppunk) (This)->lpVtbl->GetThreadMarshalInterface(This,dwThreadId,dwType,riid,ppunk)
#define ITfLangBarMgr_GetThreadLangBarItemMgr(This,dwThreadId,pplbie,pdwThreadid) (This)->lpVtbl->GetThreadLangBarItemMgr(This,dwThreadId,pplbie,pdwThreadid)
#define ITfLangBarMgr_GetInputProcessorProfiles(This,dwThreadId,ppaip,pdwThreadid) (This)->lpVtbl->GetInputProcessorProfiles(This,dwThreadId,ppaip,pdwThreadid)
#define ITfLangBarMgr_RestoreLastFocus(This,dwThreadId,fPrev) (This)->lpVtbl->RestoreLastFocus(This,dwThreadId,fPrev)
#define ITfLangBarMgr_SetModalInput(This,pSink,dwThreadId,dwFlags) (This)->lpVtbl->SetModalInput(This,pSink,dwThreadId,dwFlags)
#define ITfLangBarMgr_ShowFloating(This,dwFlags) (This)->lpVtbl->ShowFloating(This,dwFlags)
#define ITfLangBarMgr_GetShowFloatingStatus(This,pdwFlags) (This)->lpVtbl->GetShowFloatingStatus(This,pdwFlags)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfLangBarMgr_QueryInterface(ITfLangBarMgr* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfLangBarMgr_AddRef(ITfLangBarMgr* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfLangBarMgr_Release(ITfLangBarMgr* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfLangBarMgr methods ***/
static inline HRESULT ITfLangBarMgr_AdviseEventSink(ITfLangBarMgr* This,ITfLangBarEventSink *pSink,HWND hwnd,DWORD dwflags,DWORD *pdwCookie) {
    return This->lpVtbl->AdviseEventSink(This,pSink,hwnd,dwflags,pdwCookie);
}
static inline HRESULT ITfLangBarMgr_UnAdviseEventSink(ITfLangBarMgr* This,DWORD dwCookie) {
    return This->lpVtbl->UnAdviseEventSink(This,dwCookie);
}
static inline HRESULT ITfLangBarMgr_GetThreadMarshalInterface(ITfLangBarMgr* This,DWORD dwThreadId,DWORD dwType,REFIID riid,IUnknown **ppunk) {
    return This->lpVtbl->GetThreadMarshalInterface(This,dwThreadId,dwType,riid,ppunk);
}
static inline HRESULT ITfLangBarMgr_GetThreadLangBarItemMgr(ITfLangBarMgr* This,DWORD dwThreadId,ITfLangBarItemMgr **pplbie,DWORD *pdwThreadid) {
    return This->lpVtbl->GetThreadLangBarItemMgr(This,dwThreadId,pplbie,pdwThreadid);
}
static inline HRESULT ITfLangBarMgr_GetInputProcessorProfiles(ITfLangBarMgr* This,DWORD dwThreadId,ITfInputProcessorProfiles **ppaip,DWORD *pdwThreadid) {
    return This->lpVtbl->GetInputProcessorProfiles(This,dwThreadId,ppaip,pdwThreadid);
}
static inline HRESULT ITfLangBarMgr_RestoreLastFocus(ITfLangBarMgr* This,DWORD *dwThreadId,BOOL fPrev) {
    return This->lpVtbl->RestoreLastFocus(This,dwThreadId,fPrev);
}
static inline HRESULT ITfLangBarMgr_SetModalInput(ITfLangBarMgr* This,ITfLangBarEventSink *pSink,DWORD dwThreadId,DWORD dwFlags) {
    return This->lpVtbl->SetModalInput(This,pSink,dwThreadId,dwFlags);
}
static inline HRESULT ITfLangBarMgr_ShowFloating(ITfLangBarMgr* This,DWORD dwFlags) {
    return This->lpVtbl->ShowFloating(This,dwFlags);
}
static inline HRESULT ITfLangBarMgr_GetShowFloatingStatus(ITfLangBarMgr* This,DWORD *pdwFlags) {
    return This->lpVtbl->GetShowFloatingStatus(This,pdwFlags);
}
#endif
#endif

#endif


#endif  /* __ITfLangBarMgr_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfLangBarEventSink interface
 */
#ifndef __ITfLangBarEventSink_INTERFACE_DEFINED__
#define __ITfLangBarEventSink_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfLangBarEventSink, 0x18a4e900, 0xe0ae, 0x11d2, 0xaf,0xdd, 0x00,0x10,0x5a,0x27,0x99,0xb5);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("18a4e900-e0ae-11d2-afdd-00105a2799b5")
ITfLangBarEventSink : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE OnSetFocus(
        DWORD dwThreadId) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnThreadTerminate(
        DWORD dwThreadId) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnThreadItemChange(
        DWORD dwThreadId) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnModalInput(
        DWORD dwThreadId,
        UINT uMsg,
        WPARAM wParam,
        LPARAM lParam) = 0;

    virtual HRESULT STDMETHODCALLTYPE ShowFloating(
        DWORD dwFlags) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetItemFloatingRect(
        DWORD dwThreadId,
        REFGUID rguid,
        RECT *prc) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfLangBarEventSink, 0x18a4e900, 0xe0ae, 0x11d2, 0xaf,0xdd, 0x00,0x10,0x5a,0x27,0x99,0xb5)
#endif
#else
typedef struct ITfLangBarEventSinkVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfLangBarEventSink *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfLangBarEventSink *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfLangBarEventSink *This);

    /*** ITfLangBarEventSink methods ***/
    HRESULT (STDMETHODCALLTYPE *OnSetFocus)(
        ITfLangBarEventSink *This,
        DWORD dwThreadId);

    HRESULT (STDMETHODCALLTYPE *OnThreadTerminate)(
        ITfLangBarEventSink *This,
        DWORD dwThreadId);

    HRESULT (STDMETHODCALLTYPE *OnThreadItemChange)(
        ITfLangBarEventSink *This,
        DWORD dwThreadId);

    HRESULT (STDMETHODCALLTYPE *OnModalInput)(
        ITfLangBarEventSink *This,
        DWORD dwThreadId,
        UINT uMsg,
        WPARAM wParam,
        LPARAM lParam);

    HRESULT (STDMETHODCALLTYPE *ShowFloating)(
        ITfLangBarEventSink *This,
        DWORD dwFlags);

    HRESULT (STDMETHODCALLTYPE *GetItemFloatingRect)(
        ITfLangBarEventSink *This,
        DWORD dwThreadId,
        REFGUID rguid,
        RECT *prc);

    END_INTERFACE
} ITfLangBarEventSinkVtbl;

interface ITfLangBarEventSink {
    CONST_VTBL ITfLangBarEventSinkVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfLangBarEventSink_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfLangBarEventSink_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfLangBarEventSink_Release(This) (This)->lpVtbl->Release(This)
/*** ITfLangBarEventSink methods ***/
#define ITfLangBarEventSink_OnSetFocus(This,dwThreadId) (This)->lpVtbl->OnSetFocus(This,dwThreadId)
#define ITfLangBarEventSink_OnThreadTerminate(This,dwThreadId) (This)->lpVtbl->OnThreadTerminate(This,dwThreadId)
#define ITfLangBarEventSink_OnThreadItemChange(This,dwThreadId) (This)->lpVtbl->OnThreadItemChange(This,dwThreadId)
#define ITfLangBarEventSink_OnModalInput(This,dwThreadId,uMsg,wParam,lParam) (This)->lpVtbl->OnModalInput(This,dwThreadId,uMsg,wParam,lParam)
#define ITfLangBarEventSink_ShowFloating(This,dwFlags) (This)->lpVtbl->ShowFloating(This,dwFlags)
#define ITfLangBarEventSink_GetItemFloatingRect(This,dwThreadId,rguid,prc) (This)->lpVtbl->GetItemFloatingRect(This,dwThreadId,rguid,prc)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfLangBarEventSink_QueryInterface(ITfLangBarEventSink* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfLangBarEventSink_AddRef(ITfLangBarEventSink* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfLangBarEventSink_Release(ITfLangBarEventSink* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfLangBarEventSink methods ***/
static inline HRESULT ITfLangBarEventSink_OnSetFocus(ITfLangBarEventSink* This,DWORD dwThreadId) {
    return This->lpVtbl->OnSetFocus(This,dwThreadId);
}
static inline HRESULT ITfLangBarEventSink_OnThreadTerminate(ITfLangBarEventSink* This,DWORD dwThreadId) {
    return This->lpVtbl->OnThreadTerminate(This,dwThreadId);
}
static inline HRESULT ITfLangBarEventSink_OnThreadItemChange(ITfLangBarEventSink* This,DWORD dwThreadId) {
    return This->lpVtbl->OnThreadItemChange(This,dwThreadId);
}
static inline HRESULT ITfLangBarEventSink_OnModalInput(ITfLangBarEventSink* This,DWORD dwThreadId,UINT uMsg,WPARAM wParam,LPARAM lParam) {
    return This->lpVtbl->OnModalInput(This,dwThreadId,uMsg,wParam,lParam);
}
static inline HRESULT ITfLangBarEventSink_ShowFloating(ITfLangBarEventSink* This,DWORD dwFlags) {
    return This->lpVtbl->ShowFloating(This,dwFlags);
}
static inline HRESULT ITfLangBarEventSink_GetItemFloatingRect(ITfLangBarEventSink* This,DWORD dwThreadId,REFGUID rguid,RECT *prc) {
    return This->lpVtbl->GetItemFloatingRect(This,dwThreadId,rguid,prc);
}
#endif
#endif

#endif


#endif  /* __ITfLangBarEventSink_INTERFACE_DEFINED__ */

#define TF_LBI_DESC_MAXLEN (32)

typedef struct TF_LANGBARITEMINFO {
    CLSID clsidService;
    GUID guidItem;
    DWORD dwStyle;
    ULONG ulSort;
    WCHAR szDescription[32];
} TF_LANGBARITEMINFO;
/*****************************************************************************
 * ITfLangBarItemMgr interface
 */
#ifndef __ITfLangBarItemMgr_INTERFACE_DEFINED__
#define __ITfLangBarItemMgr_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfLangBarItemMgr, 0xba468c55, 0x9956, 0x4fb1, 0xa5,0x9d, 0x52,0xa7,0xdd,0x7c,0xc6,0xaa);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("ba468c55-9956-4fb1-a59d-52a7dd7cc6aa")
ITfLangBarItemMgr : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE EnumItems(
        IEnumTfLangBarItems **ppEnum) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetItem(
        REFGUID rguid,
        ITfLangBarItem **ppItem) = 0;

    virtual HRESULT STDMETHODCALLTYPE AddItem(
        ITfLangBarItem *punk) = 0;

    virtual HRESULT STDMETHODCALLTYPE RemoveItem(
        ITfLangBarItem *punk) = 0;

    virtual HRESULT STDMETHODCALLTYPE AdviseItemSink(
        ITfLangBarItemSink *punk,
        DWORD *pdwCookie,
        REFGUID rguidItem) = 0;

    virtual HRESULT STDMETHODCALLTYPE UnadviseItemSink(
        DWORD dwCookie) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetItemFloatingRect(
        DWORD dwThreadId,
        REFGUID rguid,
        RECT *prc) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetItemsStatus(
        ULONG ulCount,
        const GUID *prgguid,
        DWORD *pdwStatus) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetItemNum(
        ULONG *pulCount) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetItems(
        ULONG ulCount,
        ITfLangBarItem **ppItem,
        TF_LANGBARITEMINFO *pInfo,
        DWORD *pdwStatus,
        ULONG *pcFetched) = 0;

    virtual HRESULT STDMETHODCALLTYPE AdviseItemsSink(
        ULONG ulCount,
        ITfLangBarItemSink **ppunk,
        const GUID *pguidItem,
        DWORD *pdwCookie) = 0;

    virtual HRESULT STDMETHODCALLTYPE UnadviseItemsSink(
        ULONG ulCount,
        DWORD *pdwCookie) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfLangBarItemMgr, 0xba468c55, 0x9956, 0x4fb1, 0xa5,0x9d, 0x52,0xa7,0xdd,0x7c,0xc6,0xaa)
#endif
#else
typedef struct ITfLangBarItemMgrVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfLangBarItemMgr *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfLangBarItemMgr *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfLangBarItemMgr *This);

    /*** ITfLangBarItemMgr methods ***/
    HRESULT (STDMETHODCALLTYPE *EnumItems)(
        ITfLangBarItemMgr *This,
        IEnumTfLangBarItems **ppEnum);

    HRESULT (STDMETHODCALLTYPE *GetItem)(
        ITfLangBarItemMgr *This,
        REFGUID rguid,
        ITfLangBarItem **ppItem);

    HRESULT (STDMETHODCALLTYPE *AddItem)(
        ITfLangBarItemMgr *This,
        ITfLangBarItem *punk);

    HRESULT (STDMETHODCALLTYPE *RemoveItem)(
        ITfLangBarItemMgr *This,
        ITfLangBarItem *punk);

    HRESULT (STDMETHODCALLTYPE *AdviseItemSink)(
        ITfLangBarItemMgr *This,
        ITfLangBarItemSink *punk,
        DWORD *pdwCookie,
        REFGUID rguidItem);

    HRESULT (STDMETHODCALLTYPE *UnadviseItemSink)(
        ITfLangBarItemMgr *This,
        DWORD dwCookie);

    HRESULT (STDMETHODCALLTYPE *GetItemFloatingRect)(
        ITfLangBarItemMgr *This,
        DWORD dwThreadId,
        REFGUID rguid,
        RECT *prc);

    HRESULT (STDMETHODCALLTYPE *GetItemsStatus)(
        ITfLangBarItemMgr *This,
        ULONG ulCount,
        const GUID *prgguid,
        DWORD *pdwStatus);

    HRESULT (STDMETHODCALLTYPE *GetItemNum)(
        ITfLangBarItemMgr *This,
        ULONG *pulCount);

    HRESULT (STDMETHODCALLTYPE *GetItems)(
        ITfLangBarItemMgr *This,
        ULONG ulCount,
        ITfLangBarItem **ppItem,
        TF_LANGBARITEMINFO *pInfo,
        DWORD *pdwStatus,
        ULONG *pcFetched);

    HRESULT (STDMETHODCALLTYPE *AdviseItemsSink)(
        ITfLangBarItemMgr *This,
        ULONG ulCount,
        ITfLangBarItemSink **ppunk,
        const GUID *pguidItem,
        DWORD *pdwCookie);

    HRESULT (STDMETHODCALLTYPE *UnadviseItemsSink)(
        ITfLangBarItemMgr *This,
        ULONG ulCount,
        DWORD *pdwCookie);

    END_INTERFACE
} ITfLangBarItemMgrVtbl;

interface ITfLangBarItemMgr {
    CONST_VTBL ITfLangBarItemMgrVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfLangBarItemMgr_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfLangBarItemMgr_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfLangBarItemMgr_Release(This) (This)->lpVtbl->Release(This)
/*** ITfLangBarItemMgr methods ***/
#define ITfLangBarItemMgr_EnumItems(This,ppEnum) (This)->lpVtbl->EnumItems(This,ppEnum)
#define ITfLangBarItemMgr_GetItem(This,rguid,ppItem) (This)->lpVtbl->GetItem(This,rguid,ppItem)
#define ITfLangBarItemMgr_AddItem(This,punk) (This)->lpVtbl->AddItem(This,punk)
#define ITfLangBarItemMgr_RemoveItem(This,punk) (This)->lpVtbl->RemoveItem(This,punk)
#define ITfLangBarItemMgr_AdviseItemSink(This,punk,pdwCookie,rguidItem) (This)->lpVtbl->AdviseItemSink(This,punk,pdwCookie,rguidItem)
#define ITfLangBarItemMgr_UnadviseItemSink(This,dwCookie) (This)->lpVtbl->UnadviseItemSink(This,dwCookie)
#define ITfLangBarItemMgr_GetItemFloatingRect(This,dwThreadId,rguid,prc) (This)->lpVtbl->GetItemFloatingRect(This,dwThreadId,rguid,prc)
#define ITfLangBarItemMgr_GetItemsStatus(This,ulCount,prgguid,pdwStatus) (This)->lpVtbl->GetItemsStatus(This,ulCount,prgguid,pdwStatus)
#define ITfLangBarItemMgr_GetItemNum(This,pulCount) (This)->lpVtbl->GetItemNum(This,pulCount)
#define ITfLangBarItemMgr_GetItems(This,ulCount,ppItem,pInfo,pdwStatus,pcFetched) (This)->lpVtbl->GetItems(This,ulCount,ppItem,pInfo,pdwStatus,pcFetched)
#define ITfLangBarItemMgr_AdviseItemsSink(This,ulCount,ppunk,pguidItem,pdwCookie) (This)->lpVtbl->AdviseItemsSink(This,ulCount,ppunk,pguidItem,pdwCookie)
#define ITfLangBarItemMgr_UnadviseItemsSink(This,ulCount,pdwCookie) (This)->lpVtbl->UnadviseItemsSink(This,ulCount,pdwCookie)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfLangBarItemMgr_QueryInterface(ITfLangBarItemMgr* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfLangBarItemMgr_AddRef(ITfLangBarItemMgr* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfLangBarItemMgr_Release(ITfLangBarItemMgr* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfLangBarItemMgr methods ***/
static inline HRESULT ITfLangBarItemMgr_EnumItems(ITfLangBarItemMgr* This,IEnumTfLangBarItems **ppEnum) {
    return This->lpVtbl->EnumItems(This,ppEnum);
}
static inline HRESULT ITfLangBarItemMgr_GetItem(ITfLangBarItemMgr* This,REFGUID rguid,ITfLangBarItem **ppItem) {
    return This->lpVtbl->GetItem(This,rguid,ppItem);
}
static inline HRESULT ITfLangBarItemMgr_AddItem(ITfLangBarItemMgr* This,ITfLangBarItem *punk) {
    return This->lpVtbl->AddItem(This,punk);
}
static inline HRESULT ITfLangBarItemMgr_RemoveItem(ITfLangBarItemMgr* This,ITfLangBarItem *punk) {
    return This->lpVtbl->RemoveItem(This,punk);
}
static inline HRESULT ITfLangBarItemMgr_AdviseItemSink(ITfLangBarItemMgr* This,ITfLangBarItemSink *punk,DWORD *pdwCookie,REFGUID rguidItem) {
    return This->lpVtbl->AdviseItemSink(This,punk,pdwCookie,rguidItem);
}
static inline HRESULT ITfLangBarItemMgr_UnadviseItemSink(ITfLangBarItemMgr* This,DWORD dwCookie) {
    return This->lpVtbl->UnadviseItemSink(This,dwCookie);
}
static inline HRESULT ITfLangBarItemMgr_GetItemFloatingRect(ITfLangBarItemMgr* This,DWORD dwThreadId,REFGUID rguid,RECT *prc) {
    return This->lpVtbl->GetItemFloatingRect(This,dwThreadId,rguid,prc);
}
static inline HRESULT ITfLangBarItemMgr_GetItemsStatus(ITfLangBarItemMgr* This,ULONG ulCount,const GUID *prgguid,DWORD *pdwStatus) {
    return This->lpVtbl->GetItemsStatus(This,ulCount,prgguid,pdwStatus);
}
static inline HRESULT ITfLangBarItemMgr_GetItemNum(ITfLangBarItemMgr* This,ULONG *pulCount) {
    return This->lpVtbl->GetItemNum(This,pulCount);
}
static inline HRESULT ITfLangBarItemMgr_GetItems(ITfLangBarItemMgr* This,ULONG ulCount,ITfLangBarItem **ppItem,TF_LANGBARITEMINFO *pInfo,DWORD *pdwStatus,ULONG *pcFetched) {
    return This->lpVtbl->GetItems(This,ulCount,ppItem,pInfo,pdwStatus,pcFetched);
}
static inline HRESULT ITfLangBarItemMgr_AdviseItemsSink(ITfLangBarItemMgr* This,ULONG ulCount,ITfLangBarItemSink **ppunk,const GUID *pguidItem,DWORD *pdwCookie) {
    return This->lpVtbl->AdviseItemsSink(This,ulCount,ppunk,pguidItem,pdwCookie);
}
static inline HRESULT ITfLangBarItemMgr_UnadviseItemsSink(ITfLangBarItemMgr* This,ULONG ulCount,DWORD *pdwCookie) {
    return This->lpVtbl->UnadviseItemsSink(This,ulCount,pdwCookie);
}
#endif
#endif

#endif


#endif  /* __ITfLangBarItemMgr_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IEnumTfLangBarItems interface
 */
#ifndef __IEnumTfLangBarItems_INTERFACE_DEFINED__
#define __IEnumTfLangBarItems_INTERFACE_DEFINED__

DEFINE_GUID(IID_IEnumTfLangBarItems, 0x583f34d0, 0xde25, 0x11d2, 0xaf,0xdd, 0x00,0x10,0x5a,0x27,0x99,0xb5);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("583f34d0-de25-11d2-afdd-00105a2799b5")
IEnumTfLangBarItems : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Clone(
        IEnumTfLangBarItems **ppEnum) = 0;

    virtual HRESULT STDMETHODCALLTYPE Next(
        ULONG ulCount,
        ITfLangBarItem **ppItem,
        ULONG *pcFetched) = 0;

    virtual HRESULT STDMETHODCALLTYPE Reset(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE Skip(
        ULONG ulCount) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IEnumTfLangBarItems, 0x583f34d0, 0xde25, 0x11d2, 0xaf,0xdd, 0x00,0x10,0x5a,0x27,0x99,0xb5)
#endif
#else
typedef struct IEnumTfLangBarItemsVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IEnumTfLangBarItems *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IEnumTfLangBarItems *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IEnumTfLangBarItems *This);

    /*** IEnumTfLangBarItems methods ***/
    HRESULT (STDMETHODCALLTYPE *Clone)(
        IEnumTfLangBarItems *This,
        IEnumTfLangBarItems **ppEnum);

    HRESULT (STDMETHODCALLTYPE *Next)(
        IEnumTfLangBarItems *This,
        ULONG ulCount,
        ITfLangBarItem **ppItem,
        ULONG *pcFetched);

    HRESULT (STDMETHODCALLTYPE *Reset)(
        IEnumTfLangBarItems *This);

    HRESULT (STDMETHODCALLTYPE *Skip)(
        IEnumTfLangBarItems *This,
        ULONG ulCount);

    END_INTERFACE
} IEnumTfLangBarItemsVtbl;

interface IEnumTfLangBarItems {
    CONST_VTBL IEnumTfLangBarItemsVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IEnumTfLangBarItems_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IEnumTfLangBarItems_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IEnumTfLangBarItems_Release(This) (This)->lpVtbl->Release(This)
/*** IEnumTfLangBarItems methods ***/
#define IEnumTfLangBarItems_Clone(This,ppEnum) (This)->lpVtbl->Clone(This,ppEnum)
#define IEnumTfLangBarItems_Next(This,ulCount,ppItem,pcFetched) (This)->lpVtbl->Next(This,ulCount,ppItem,pcFetched)
#define IEnumTfLangBarItems_Reset(This) (This)->lpVtbl->Reset(This)
#define IEnumTfLangBarItems_Skip(This,ulCount) (This)->lpVtbl->Skip(This,ulCount)
#else
/*** IUnknown methods ***/
static inline HRESULT IEnumTfLangBarItems_QueryInterface(IEnumTfLangBarItems* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IEnumTfLangBarItems_AddRef(IEnumTfLangBarItems* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IEnumTfLangBarItems_Release(IEnumTfLangBarItems* This) {
    return This->lpVtbl->Release(This);
}
/*** IEnumTfLangBarItems methods ***/
static inline HRESULT IEnumTfLangBarItems_Clone(IEnumTfLangBarItems* This,IEnumTfLangBarItems **ppEnum) {
    return This->lpVtbl->Clone(This,ppEnum);
}
static inline HRESULT IEnumTfLangBarItems_Next(IEnumTfLangBarItems* This,ULONG ulCount,ITfLangBarItem **ppItem,ULONG *pcFetched) {
    return This->lpVtbl->Next(This,ulCount,ppItem,pcFetched);
}
static inline HRESULT IEnumTfLangBarItems_Reset(IEnumTfLangBarItems* This) {
    return This->lpVtbl->Reset(This);
}
static inline HRESULT IEnumTfLangBarItems_Skip(IEnumTfLangBarItems* This,ULONG ulCount) {
    return This->lpVtbl->Skip(This,ulCount);
}
#endif
#endif

#endif


#endif  /* __IEnumTfLangBarItems_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfLangBarItem interface
 */
#ifndef __ITfLangBarItem_INTERFACE_DEFINED__
#define __ITfLangBarItem_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfLangBarItem, 0x73540d69, 0xedeb, 0x4ee9, 0x96,0xc9, 0x23,0xaa,0x30,0xb2,0x59,0x16);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("73540d69-edeb-4ee9-96c9-23aa30b25916")
ITfLangBarItem : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE GetInfo(
        TF_LANGBARITEMINFO *pInfo) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetStatus(
        DWORD *pdwStatus) = 0;

    virtual HRESULT STDMETHODCALLTYPE Show(
        BOOL fShow) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetTooltipString(
        BSTR *pbstrToolTip) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfLangBarItem, 0x73540d69, 0xedeb, 0x4ee9, 0x96,0xc9, 0x23,0xaa,0x30,0xb2,0x59,0x16)
#endif
#else
typedef struct ITfLangBarItemVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfLangBarItem *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfLangBarItem *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfLangBarItem *This);

    /*** ITfLangBarItem methods ***/
    HRESULT (STDMETHODCALLTYPE *GetInfo)(
        ITfLangBarItem *This,
        TF_LANGBARITEMINFO *pInfo);

    HRESULT (STDMETHODCALLTYPE *GetStatus)(
        ITfLangBarItem *This,
        DWORD *pdwStatus);

    HRESULT (STDMETHODCALLTYPE *Show)(
        ITfLangBarItem *This,
        BOOL fShow);

    HRESULT (STDMETHODCALLTYPE *GetTooltipString)(
        ITfLangBarItem *This,
        BSTR *pbstrToolTip);

    END_INTERFACE
} ITfLangBarItemVtbl;

interface ITfLangBarItem {
    CONST_VTBL ITfLangBarItemVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfLangBarItem_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfLangBarItem_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfLangBarItem_Release(This) (This)->lpVtbl->Release(This)
/*** ITfLangBarItem methods ***/
#define ITfLangBarItem_GetInfo(This,pInfo) (This)->lpVtbl->GetInfo(This,pInfo)
#define ITfLangBarItem_GetStatus(This,pdwStatus) (This)->lpVtbl->GetStatus(This,pdwStatus)
#define ITfLangBarItem_Show(This,fShow) (This)->lpVtbl->Show(This,fShow)
#define ITfLangBarItem_GetTooltipString(This,pbstrToolTip) (This)->lpVtbl->GetTooltipString(This,pbstrToolTip)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfLangBarItem_QueryInterface(ITfLangBarItem* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfLangBarItem_AddRef(ITfLangBarItem* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfLangBarItem_Release(ITfLangBarItem* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfLangBarItem methods ***/
static inline HRESULT ITfLangBarItem_GetInfo(ITfLangBarItem* This,TF_LANGBARITEMINFO *pInfo) {
    return This->lpVtbl->GetInfo(This,pInfo);
}
static inline HRESULT ITfLangBarItem_GetStatus(ITfLangBarItem* This,DWORD *pdwStatus) {
    return This->lpVtbl->GetStatus(This,pdwStatus);
}
static inline HRESULT ITfLangBarItem_Show(ITfLangBarItem* This,BOOL fShow) {
    return This->lpVtbl->Show(This,fShow);
}
static inline HRESULT ITfLangBarItem_GetTooltipString(ITfLangBarItem* This,BSTR *pbstrToolTip) {
    return This->lpVtbl->GetTooltipString(This,pbstrToolTip);
}
#endif
#endif

#endif


#endif  /* __ITfLangBarItem_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfLangBarItemSink interface
 */
#ifndef __ITfLangBarItemSink_INTERFACE_DEFINED__
#define __ITfLangBarItemSink_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfLangBarItemSink, 0x57dbe1a0, 0xde25, 0x11d2, 0xaf,0xdd, 0x00,0x10,0x5a,0x27,0x99,0xb5);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("57dbe1a0-de25-11d2-afdd-00105a2799b5")
ITfLangBarItemSink : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE OnUpdate(
        DWORD dwFlags) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfLangBarItemSink, 0x57dbe1a0, 0xde25, 0x11d2, 0xaf,0xdd, 0x00,0x10,0x5a,0x27,0x99,0xb5)
#endif
#else
typedef struct ITfLangBarItemSinkVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfLangBarItemSink *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfLangBarItemSink *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfLangBarItemSink *This);

    /*** ITfLangBarItemSink methods ***/
    HRESULT (STDMETHODCALLTYPE *OnUpdate)(
        ITfLangBarItemSink *This,
        DWORD dwFlags);

    END_INTERFACE
} ITfLangBarItemSinkVtbl;

interface ITfLangBarItemSink {
    CONST_VTBL ITfLangBarItemSinkVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfLangBarItemSink_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfLangBarItemSink_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfLangBarItemSink_Release(This) (This)->lpVtbl->Release(This)
/*** ITfLangBarItemSink methods ***/
#define ITfLangBarItemSink_OnUpdate(This,dwFlags) (This)->lpVtbl->OnUpdate(This,dwFlags)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfLangBarItemSink_QueryInterface(ITfLangBarItemSink* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfLangBarItemSink_AddRef(ITfLangBarItemSink* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfLangBarItemSink_Release(ITfLangBarItemSink* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfLangBarItemSink methods ***/
static inline HRESULT ITfLangBarItemSink_OnUpdate(ITfLangBarItemSink* This,DWORD dwFlags) {
    return This->lpVtbl->OnUpdate(This,dwFlags);
}
#endif
#endif

#endif


#endif  /* __ITfLangBarItemSink_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfLangBarItemBalloon interface
 */
#ifndef __ITfLangBarItemBalloon_INTERFACE_DEFINED__
#define __ITfLangBarItemBalloon_INTERFACE_DEFINED__

typedef enum __WIDL_ctfutb_generated_name_0000000E {
    TF_LB_BALLOON_RECO = 0,
    TF_LB_BALLOON_SHOW = 1,
    TF_LB_BALLOON_MISS = 2
} TfLBBalloonStyle;
typedef struct TF_LBBALLOONINFO {
    TfLBBalloonStyle style;
    BSTR bstrText;
} TF_LBBALLOONINFO;
DEFINE_GUID(IID_ITfLangBarItemBalloon, 0x01c2d285, 0xd3c7, 0x4b7b, 0xb5,0xb5, 0xd9,0x74,0x11,0xd0,0xc2,0x83);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("01c2d285-d3c7-4b7b-b5b5-d97411d0c283")
ITfLangBarItemBalloon : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE OnClick(
        TfLBIClick click,
        POINT pt,
        const RECT *prcArea) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetPreferredSize(
        const SIZE *pszDefault,
        SIZE *psz) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetBalloonInfo(
        TF_LBBALLOONINFO *pInfo) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfLangBarItemBalloon, 0x01c2d285, 0xd3c7, 0x4b7b, 0xb5,0xb5, 0xd9,0x74,0x11,0xd0,0xc2,0x83)
#endif
#else
typedef struct ITfLangBarItemBalloonVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfLangBarItemBalloon *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfLangBarItemBalloon *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfLangBarItemBalloon *This);

    /*** ITfLangBarItemBalloon methods ***/
    HRESULT (STDMETHODCALLTYPE *OnClick)(
        ITfLangBarItemBalloon *This,
        TfLBIClick click,
        POINT pt,
        const RECT *prcArea);

    HRESULT (STDMETHODCALLTYPE *GetPreferredSize)(
        ITfLangBarItemBalloon *This,
        const SIZE *pszDefault,
        SIZE *psz);

    HRESULT (STDMETHODCALLTYPE *GetBalloonInfo)(
        ITfLangBarItemBalloon *This,
        TF_LBBALLOONINFO *pInfo);

    END_INTERFACE
} ITfLangBarItemBalloonVtbl;

interface ITfLangBarItemBalloon {
    CONST_VTBL ITfLangBarItemBalloonVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfLangBarItemBalloon_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfLangBarItemBalloon_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfLangBarItemBalloon_Release(This) (This)->lpVtbl->Release(This)
/*** ITfLangBarItemBalloon methods ***/
#define ITfLangBarItemBalloon_OnClick(This,click,pt,prcArea) (This)->lpVtbl->OnClick(This,click,pt,prcArea)
#define ITfLangBarItemBalloon_GetPreferredSize(This,pszDefault,psz) (This)->lpVtbl->GetPreferredSize(This,pszDefault,psz)
#define ITfLangBarItemBalloon_GetBalloonInfo(This,pInfo) (This)->lpVtbl->GetBalloonInfo(This,pInfo)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfLangBarItemBalloon_QueryInterface(ITfLangBarItemBalloon* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfLangBarItemBalloon_AddRef(ITfLangBarItemBalloon* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfLangBarItemBalloon_Release(ITfLangBarItemBalloon* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfLangBarItemBalloon methods ***/
static inline HRESULT ITfLangBarItemBalloon_OnClick(ITfLangBarItemBalloon* This,TfLBIClick click,POINT pt,const RECT *prcArea) {
    return This->lpVtbl->OnClick(This,click,pt,prcArea);
}
static inline HRESULT ITfLangBarItemBalloon_GetPreferredSize(ITfLangBarItemBalloon* This,const SIZE *pszDefault,SIZE *psz) {
    return This->lpVtbl->GetPreferredSize(This,pszDefault,psz);
}
static inline HRESULT ITfLangBarItemBalloon_GetBalloonInfo(ITfLangBarItemBalloon* This,TF_LBBALLOONINFO *pInfo) {
    return This->lpVtbl->GetBalloonInfo(This,pInfo);
}
#endif
#endif

#endif


#endif  /* __ITfLangBarItemBalloon_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfLangBarItemBitmap interface
 */
#ifndef __ITfLangBarItemBitmap_INTERFACE_DEFINED__
#define __ITfLangBarItemBitmap_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfLangBarItemBitmap, 0x73830352, 0xd722, 0x4179, 0xad,0xa5, 0xf0,0x45,0xc9,0x8d,0xf3,0x55);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("73830352-d722-4179-ada5-f045c98df355")
ITfLangBarItemBitmap : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE OnClick(
        TfLBIClick click,
        POINT pt,
        const RECT *prcArea) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetPreferredSize(
        const SIZE *pszDefault,
        SIZE *psz) = 0;

    virtual HRESULT STDMETHODCALLTYPE DrawBitmap(
        LONG bmWidth,
        LONG bmHeight,
        DWORD dwFlags,
        HBITMAP *phbmp,
        HBITMAP *phbmpMask) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfLangBarItemBitmap, 0x73830352, 0xd722, 0x4179, 0xad,0xa5, 0xf0,0x45,0xc9,0x8d,0xf3,0x55)
#endif
#else
typedef struct ITfLangBarItemBitmapVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfLangBarItemBitmap *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfLangBarItemBitmap *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfLangBarItemBitmap *This);

    /*** ITfLangBarItemBitmap methods ***/
    HRESULT (STDMETHODCALLTYPE *OnClick)(
        ITfLangBarItemBitmap *This,
        TfLBIClick click,
        POINT pt,
        const RECT *prcArea);

    HRESULT (STDMETHODCALLTYPE *GetPreferredSize)(
        ITfLangBarItemBitmap *This,
        const SIZE *pszDefault,
        SIZE *psz);

    HRESULT (STDMETHODCALLTYPE *DrawBitmap)(
        ITfLangBarItemBitmap *This,
        LONG bmWidth,
        LONG bmHeight,
        DWORD dwFlags,
        HBITMAP *phbmp,
        HBITMAP *phbmpMask);

    END_INTERFACE
} ITfLangBarItemBitmapVtbl;

interface ITfLangBarItemBitmap {
    CONST_VTBL ITfLangBarItemBitmapVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfLangBarItemBitmap_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfLangBarItemBitmap_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfLangBarItemBitmap_Release(This) (This)->lpVtbl->Release(This)
/*** ITfLangBarItemBitmap methods ***/
#define ITfLangBarItemBitmap_OnClick(This,click,pt,prcArea) (This)->lpVtbl->OnClick(This,click,pt,prcArea)
#define ITfLangBarItemBitmap_GetPreferredSize(This,pszDefault,psz) (This)->lpVtbl->GetPreferredSize(This,pszDefault,psz)
#define ITfLangBarItemBitmap_DrawBitmap(This,bmWidth,bmHeight,dwFlags,phbmp,phbmpMask) (This)->lpVtbl->DrawBitmap(This,bmWidth,bmHeight,dwFlags,phbmp,phbmpMask)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfLangBarItemBitmap_QueryInterface(ITfLangBarItemBitmap* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfLangBarItemBitmap_AddRef(ITfLangBarItemBitmap* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfLangBarItemBitmap_Release(ITfLangBarItemBitmap* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfLangBarItemBitmap methods ***/
static inline HRESULT ITfLangBarItemBitmap_OnClick(ITfLangBarItemBitmap* This,TfLBIClick click,POINT pt,const RECT *prcArea) {
    return This->lpVtbl->OnClick(This,click,pt,prcArea);
}
static inline HRESULT ITfLangBarItemBitmap_GetPreferredSize(ITfLangBarItemBitmap* This,const SIZE *pszDefault,SIZE *psz) {
    return This->lpVtbl->GetPreferredSize(This,pszDefault,psz);
}
static inline HRESULT ITfLangBarItemBitmap_DrawBitmap(ITfLangBarItemBitmap* This,LONG bmWidth,LONG bmHeight,DWORD dwFlags,HBITMAP *phbmp,HBITMAP *phbmpMask) {
    return This->lpVtbl->DrawBitmap(This,bmWidth,bmHeight,dwFlags,phbmp,phbmpMask);
}
#endif
#endif

#endif


#endif  /* __ITfLangBarItemBitmap_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfLangBarItemBitmapButton interface
 */
#ifndef __ITfLangBarItemBitmapButton_INTERFACE_DEFINED__
#define __ITfLangBarItemBitmapButton_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfLangBarItemBitmapButton, 0xa26a0525, 0x3fae, 0x4fa0, 0x89,0xee, 0x88,0xa9,0x64,0xf9,0xf1,0xb5);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("a26a0525-3fae-4fa0-89ee-88a964f9f1b5")
ITfLangBarItemBitmapButton : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE OnClick(
        TfLBIClick click,
        POINT pt,
        const RECT *prcArea) = 0;

    virtual HRESULT STDMETHODCALLTYPE InitMenu(
        ITfMenu *pMenu) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnMenuSelect(
        UINT wID) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetPreferredSize(
        const SIZE *pszDefault,
        SIZE *psz) = 0;

    virtual HRESULT STDMETHODCALLTYPE DrawBitmap(
        LONG bmWidth,
        LONG bmHeight,
        DWORD dwFlags,
        HBITMAP *phbmp,
        HBITMAP *phbmpMask) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetText(
        BSTR *pbstrText) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfLangBarItemBitmapButton, 0xa26a0525, 0x3fae, 0x4fa0, 0x89,0xee, 0x88,0xa9,0x64,0xf9,0xf1,0xb5)
#endif
#else
typedef struct ITfLangBarItemBitmapButtonVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfLangBarItemBitmapButton *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfLangBarItemBitmapButton *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfLangBarItemBitmapButton *This);

    /*** ITfLangBarItemBitmapButton methods ***/
    HRESULT (STDMETHODCALLTYPE *OnClick)(
        ITfLangBarItemBitmapButton *This,
        TfLBIClick click,
        POINT pt,
        const RECT *prcArea);

    HRESULT (STDMETHODCALLTYPE *InitMenu)(
        ITfLangBarItemBitmapButton *This,
        ITfMenu *pMenu);

    HRESULT (STDMETHODCALLTYPE *OnMenuSelect)(
        ITfLangBarItemBitmapButton *This,
        UINT wID);

    HRESULT (STDMETHODCALLTYPE *GetPreferredSize)(
        ITfLangBarItemBitmapButton *This,
        const SIZE *pszDefault,
        SIZE *psz);

    HRESULT (STDMETHODCALLTYPE *DrawBitmap)(
        ITfLangBarItemBitmapButton *This,
        LONG bmWidth,
        LONG bmHeight,
        DWORD dwFlags,
        HBITMAP *phbmp,
        HBITMAP *phbmpMask);

    HRESULT (STDMETHODCALLTYPE *GetText)(
        ITfLangBarItemBitmapButton *This,
        BSTR *pbstrText);

    END_INTERFACE
} ITfLangBarItemBitmapButtonVtbl;

interface ITfLangBarItemBitmapButton {
    CONST_VTBL ITfLangBarItemBitmapButtonVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfLangBarItemBitmapButton_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfLangBarItemBitmapButton_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfLangBarItemBitmapButton_Release(This) (This)->lpVtbl->Release(This)
/*** ITfLangBarItemBitmapButton methods ***/
#define ITfLangBarItemBitmapButton_OnClick(This,click,pt,prcArea) (This)->lpVtbl->OnClick(This,click,pt,prcArea)
#define ITfLangBarItemBitmapButton_InitMenu(This,pMenu) (This)->lpVtbl->InitMenu(This,pMenu)
#define ITfLangBarItemBitmapButton_OnMenuSelect(This,wID) (This)->lpVtbl->OnMenuSelect(This,wID)
#define ITfLangBarItemBitmapButton_GetPreferredSize(This,pszDefault,psz) (This)->lpVtbl->GetPreferredSize(This,pszDefault,psz)
#define ITfLangBarItemBitmapButton_DrawBitmap(This,bmWidth,bmHeight,dwFlags,phbmp,phbmpMask) (This)->lpVtbl->DrawBitmap(This,bmWidth,bmHeight,dwFlags,phbmp,phbmpMask)
#define ITfLangBarItemBitmapButton_GetText(This,pbstrText) (This)->lpVtbl->GetText(This,pbstrText)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfLangBarItemBitmapButton_QueryInterface(ITfLangBarItemBitmapButton* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfLangBarItemBitmapButton_AddRef(ITfLangBarItemBitmapButton* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfLangBarItemBitmapButton_Release(ITfLangBarItemBitmapButton* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfLangBarItemBitmapButton methods ***/
static inline HRESULT ITfLangBarItemBitmapButton_OnClick(ITfLangBarItemBitmapButton* This,TfLBIClick click,POINT pt,const RECT *prcArea) {
    return This->lpVtbl->OnClick(This,click,pt,prcArea);
}
static inline HRESULT ITfLangBarItemBitmapButton_InitMenu(ITfLangBarItemBitmapButton* This,ITfMenu *pMenu) {
    return This->lpVtbl->InitMenu(This,pMenu);
}
static inline HRESULT ITfLangBarItemBitmapButton_OnMenuSelect(ITfLangBarItemBitmapButton* This,UINT wID) {
    return This->lpVtbl->OnMenuSelect(This,wID);
}
static inline HRESULT ITfLangBarItemBitmapButton_GetPreferredSize(ITfLangBarItemBitmapButton* This,const SIZE *pszDefault,SIZE *psz) {
    return This->lpVtbl->GetPreferredSize(This,pszDefault,psz);
}
static inline HRESULT ITfLangBarItemBitmapButton_DrawBitmap(ITfLangBarItemBitmapButton* This,LONG bmWidth,LONG bmHeight,DWORD dwFlags,HBITMAP *phbmp,HBITMAP *phbmpMask) {
    return This->lpVtbl->DrawBitmap(This,bmWidth,bmHeight,dwFlags,phbmp,phbmpMask);
}
static inline HRESULT ITfLangBarItemBitmapButton_GetText(ITfLangBarItemBitmapButton* This,BSTR *pbstrText) {
    return This->lpVtbl->GetText(This,pbstrText);
}
#endif
#endif

#endif


#endif  /* __ITfLangBarItemBitmapButton_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfLangBarItemButton interface
 */
#ifndef __ITfLangBarItemButton_INTERFACE_DEFINED__
#define __ITfLangBarItemButton_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfLangBarItemButton, 0x28c7f1d0, 0xde25, 0x11d2, 0xaf,0xdd, 0x00,0x10,0x5a,0x27,0x99,0xb5);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("28c7f1d0-de25-11d2-afdd-00105a2799b5")
ITfLangBarItemButton : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE OnClick(
        TfLBIClick click,
        POINT pt,
        const RECT *prcArea) = 0;

    virtual HRESULT STDMETHODCALLTYPE InitMenu(
        ITfMenu *pMenu) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnMenuSelect(
        UINT wID) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetIcon(
        HICON *phIcon) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetText(
        BSTR *pbstrText) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfLangBarItemButton, 0x28c7f1d0, 0xde25, 0x11d2, 0xaf,0xdd, 0x00,0x10,0x5a,0x27,0x99,0xb5)
#endif
#else
typedef struct ITfLangBarItemButtonVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfLangBarItemButton *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfLangBarItemButton *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfLangBarItemButton *This);

    /*** ITfLangBarItemButton methods ***/
    HRESULT (STDMETHODCALLTYPE *OnClick)(
        ITfLangBarItemButton *This,
        TfLBIClick click,
        POINT pt,
        const RECT *prcArea);

    HRESULT (STDMETHODCALLTYPE *InitMenu)(
        ITfLangBarItemButton *This,
        ITfMenu *pMenu);

    HRESULT (STDMETHODCALLTYPE *OnMenuSelect)(
        ITfLangBarItemButton *This,
        UINT wID);

    HRESULT (STDMETHODCALLTYPE *GetIcon)(
        ITfLangBarItemButton *This,
        HICON *phIcon);

    HRESULT (STDMETHODCALLTYPE *GetText)(
        ITfLangBarItemButton *This,
        BSTR *pbstrText);

    END_INTERFACE
} ITfLangBarItemButtonVtbl;

interface ITfLangBarItemButton {
    CONST_VTBL ITfLangBarItemButtonVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfLangBarItemButton_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfLangBarItemButton_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfLangBarItemButton_Release(This) (This)->lpVtbl->Release(This)
/*** ITfLangBarItemButton methods ***/
#define ITfLangBarItemButton_OnClick(This,click,pt,prcArea) (This)->lpVtbl->OnClick(This,click,pt,prcArea)
#define ITfLangBarItemButton_InitMenu(This,pMenu) (This)->lpVtbl->InitMenu(This,pMenu)
#define ITfLangBarItemButton_OnMenuSelect(This,wID) (This)->lpVtbl->OnMenuSelect(This,wID)
#define ITfLangBarItemButton_GetIcon(This,phIcon) (This)->lpVtbl->GetIcon(This,phIcon)
#define ITfLangBarItemButton_GetText(This,pbstrText) (This)->lpVtbl->GetText(This,pbstrText)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfLangBarItemButton_QueryInterface(ITfLangBarItemButton* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfLangBarItemButton_AddRef(ITfLangBarItemButton* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfLangBarItemButton_Release(ITfLangBarItemButton* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfLangBarItemButton methods ***/
static inline HRESULT ITfLangBarItemButton_OnClick(ITfLangBarItemButton* This,TfLBIClick click,POINT pt,const RECT *prcArea) {
    return This->lpVtbl->OnClick(This,click,pt,prcArea);
}
static inline HRESULT ITfLangBarItemButton_InitMenu(ITfLangBarItemButton* This,ITfMenu *pMenu) {
    return This->lpVtbl->InitMenu(This,pMenu);
}
static inline HRESULT ITfLangBarItemButton_OnMenuSelect(ITfLangBarItemButton* This,UINT wID) {
    return This->lpVtbl->OnMenuSelect(This,wID);
}
static inline HRESULT ITfLangBarItemButton_GetIcon(ITfLangBarItemButton* This,HICON *phIcon) {
    return This->lpVtbl->GetIcon(This,phIcon);
}
static inline HRESULT ITfLangBarItemButton_GetText(ITfLangBarItemButton* This,BSTR *pbstrText) {
    return This->lpVtbl->GetText(This,pbstrText);
}
#endif
#endif

#endif


#endif  /* __ITfLangBarItemButton_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfMenu interface
 */
#ifndef __ITfMenu_INTERFACE_DEFINED__
#define __ITfMenu_INTERFACE_DEFINED__

#define TF_LBMENUF_CHECKED (0x1)

#define TF_LBMENUF_SUBMENU (0x2)

#define TF_LBMENUF_SEPARATOR (0x4)

#define TF_LBMENUF_RADIOCHECKED (0x8)

#define TF_LBMENUF_GRAYED (0x10)

DEFINE_GUID(IID_ITfMenu, 0x6f8a98e4, 0xaaa0, 0x4f15, 0x8c,0x5b, 0x07,0xe0,0xdf,0x0a,0x3d,0xd8);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("6f8a98e4-aaa0-4f15-8c5b-07e0df0a3dd8")
ITfMenu : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE AddMenuItem(
        UINT uId,
        DWORD dwFlags,
        HBITMAP hbmp,
        HBITMAP hbmpMask,
        const WCHAR *pch,
        ULONG cch,
        ITfMenu **ppMenu) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfMenu, 0x6f8a98e4, 0xaaa0, 0x4f15, 0x8c,0x5b, 0x07,0xe0,0xdf,0x0a,0x3d,0xd8)
#endif
#else
typedef struct ITfMenuVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfMenu *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfMenu *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfMenu *This);

    /*** ITfMenu methods ***/
    HRESULT (STDMETHODCALLTYPE *AddMenuItem)(
        ITfMenu *This,
        UINT uId,
        DWORD dwFlags,
        HBITMAP hbmp,
        HBITMAP hbmpMask,
        const WCHAR *pch,
        ULONG cch,
        ITfMenu **ppMenu);

    END_INTERFACE
} ITfMenuVtbl;

interface ITfMenu {
    CONST_VTBL ITfMenuVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfMenu_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfMenu_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfMenu_Release(This) (This)->lpVtbl->Release(This)
/*** ITfMenu methods ***/
#define ITfMenu_AddMenuItem(This,uId,dwFlags,hbmp,hbmpMask,pch,cch,ppMenu) (This)->lpVtbl->AddMenuItem(This,uId,dwFlags,hbmp,hbmpMask,pch,cch,ppMenu)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfMenu_QueryInterface(ITfMenu* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfMenu_AddRef(ITfMenu* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfMenu_Release(ITfMenu* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfMenu methods ***/
static inline HRESULT ITfMenu_AddMenuItem(ITfMenu* This,UINT uId,DWORD dwFlags,HBITMAP hbmp,HBITMAP hbmpMask,const WCHAR *pch,ULONG cch,ITfMenu **ppMenu) {
    return This->lpVtbl->AddMenuItem(This,uId,dwFlags,hbmp,hbmpMask,pch,cch,ppMenu);
}
#endif
#endif

#endif


#endif  /* __ITfMenu_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfSystemDeviceTypeLangBarItem interface
 */
#ifndef __ITfSystemDeviceTypeLangBarItem_INTERFACE_DEFINED__
#define __ITfSystemDeviceTypeLangBarItem_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfSystemDeviceTypeLangBarItem, 0x45672eb9, 0x9059, 0x46a2, 0x83,0x8d, 0x45,0x30,0x35,0x5f,0x6a,0x77);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("45672eb9-9059-46a2-838d-4530355f6a77")
ITfSystemDeviceTypeLangBarItem : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE SetIconMode(
        DWORD dwFlags) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetIconMode(
        DWORD *pdwFlags) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfSystemDeviceTypeLangBarItem, 0x45672eb9, 0x9059, 0x46a2, 0x83,0x8d, 0x45,0x30,0x35,0x5f,0x6a,0x77)
#endif
#else
typedef struct ITfSystemDeviceTypeLangBarItemVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfSystemDeviceTypeLangBarItem *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfSystemDeviceTypeLangBarItem *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfSystemDeviceTypeLangBarItem *This);

    /*** ITfSystemDeviceTypeLangBarItem methods ***/
    HRESULT (STDMETHODCALLTYPE *SetIconMode)(
        ITfSystemDeviceTypeLangBarItem *This,
        DWORD dwFlags);

    HRESULT (STDMETHODCALLTYPE *GetIconMode)(
        ITfSystemDeviceTypeLangBarItem *This,
        DWORD *pdwFlags);

    END_INTERFACE
} ITfSystemDeviceTypeLangBarItemVtbl;

interface ITfSystemDeviceTypeLangBarItem {
    CONST_VTBL ITfSystemDeviceTypeLangBarItemVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfSystemDeviceTypeLangBarItem_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfSystemDeviceTypeLangBarItem_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfSystemDeviceTypeLangBarItem_Release(This) (This)->lpVtbl->Release(This)
/*** ITfSystemDeviceTypeLangBarItem methods ***/
#define ITfSystemDeviceTypeLangBarItem_SetIconMode(This,dwFlags) (This)->lpVtbl->SetIconMode(This,dwFlags)
#define ITfSystemDeviceTypeLangBarItem_GetIconMode(This,pdwFlags) (This)->lpVtbl->GetIconMode(This,pdwFlags)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfSystemDeviceTypeLangBarItem_QueryInterface(ITfSystemDeviceTypeLangBarItem* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfSystemDeviceTypeLangBarItem_AddRef(ITfSystemDeviceTypeLangBarItem* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfSystemDeviceTypeLangBarItem_Release(ITfSystemDeviceTypeLangBarItem* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfSystemDeviceTypeLangBarItem methods ***/
static inline HRESULT ITfSystemDeviceTypeLangBarItem_SetIconMode(ITfSystemDeviceTypeLangBarItem* This,DWORD dwFlags) {
    return This->lpVtbl->SetIconMode(This,dwFlags);
}
static inline HRESULT ITfSystemDeviceTypeLangBarItem_GetIconMode(ITfSystemDeviceTypeLangBarItem* This,DWORD *pdwFlags) {
    return This->lpVtbl->GetIconMode(This,pdwFlags);
}
#endif
#endif

#endif


#endif  /* __ITfSystemDeviceTypeLangBarItem_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfSystemLangBarItem interface
 */
#ifndef __ITfSystemLangBarItem_INTERFACE_DEFINED__
#define __ITfSystemLangBarItem_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfSystemLangBarItem, 0x1e13e9ec, 0x6b33, 0x4d4a, 0xb5,0xeb, 0x8a,0x92,0xf0,0x29,0xf3,0x56);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("1e13e9ec-6b33-4d4a-b5eb-8a92f029f356")
ITfSystemLangBarItem : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE SetIcon(
        HICON hIcon) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetTooltipString(
        WCHAR *pchToolTip,
        ULONG cch) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfSystemLangBarItem, 0x1e13e9ec, 0x6b33, 0x4d4a, 0xb5,0xeb, 0x8a,0x92,0xf0,0x29,0xf3,0x56)
#endif
#else
typedef struct ITfSystemLangBarItemVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfSystemLangBarItem *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfSystemLangBarItem *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfSystemLangBarItem *This);

    /*** ITfSystemLangBarItem methods ***/
    HRESULT (STDMETHODCALLTYPE *SetIcon)(
        ITfSystemLangBarItem *This,
        HICON hIcon);

    HRESULT (STDMETHODCALLTYPE *SetTooltipString)(
        ITfSystemLangBarItem *This,
        WCHAR *pchToolTip,
        ULONG cch);

    END_INTERFACE
} ITfSystemLangBarItemVtbl;

interface ITfSystemLangBarItem {
    CONST_VTBL ITfSystemLangBarItemVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfSystemLangBarItem_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfSystemLangBarItem_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfSystemLangBarItem_Release(This) (This)->lpVtbl->Release(This)
/*** ITfSystemLangBarItem methods ***/
#define ITfSystemLangBarItem_SetIcon(This,hIcon) (This)->lpVtbl->SetIcon(This,hIcon)
#define ITfSystemLangBarItem_SetTooltipString(This,pchToolTip,cch) (This)->lpVtbl->SetTooltipString(This,pchToolTip,cch)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfSystemLangBarItem_QueryInterface(ITfSystemLangBarItem* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfSystemLangBarItem_AddRef(ITfSystemLangBarItem* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfSystemLangBarItem_Release(ITfSystemLangBarItem* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfSystemLangBarItem methods ***/
static inline HRESULT ITfSystemLangBarItem_SetIcon(ITfSystemLangBarItem* This,HICON hIcon) {
    return This->lpVtbl->SetIcon(This,hIcon);
}
static inline HRESULT ITfSystemLangBarItem_SetTooltipString(ITfSystemLangBarItem* This,WCHAR *pchToolTip,ULONG cch) {
    return This->lpVtbl->SetTooltipString(This,pchToolTip,cch);
}
#endif
#endif

#endif


#endif  /* __ITfSystemLangBarItem_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfSystemLangBarItemSink interface
 */
#ifndef __ITfSystemLangBarItemSink_INTERFACE_DEFINED__
#define __ITfSystemLangBarItemSink_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfSystemLangBarItemSink, 0x1449d9ab, 0x13cf, 0x4687, 0xaa,0x3e, 0x8d,0x8b,0x18,0x57,0x43,0x96);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("1449d9ab-13cf-4687-aa3e-8d8b18574396")
ITfSystemLangBarItemSink : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE InitMenu(
        ITfMenu *pMenu) = 0;

    virtual HRESULT STDMETHODCALLTYPE OnMenuSelect(
        UINT wID) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfSystemLangBarItemSink, 0x1449d9ab, 0x13cf, 0x4687, 0xaa,0x3e, 0x8d,0x8b,0x18,0x57,0x43,0x96)
#endif
#else
typedef struct ITfSystemLangBarItemSinkVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfSystemLangBarItemSink *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfSystemLangBarItemSink *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfSystemLangBarItemSink *This);

    /*** ITfSystemLangBarItemSink methods ***/
    HRESULT (STDMETHODCALLTYPE *InitMenu)(
        ITfSystemLangBarItemSink *This,
        ITfMenu *pMenu);

    HRESULT (STDMETHODCALLTYPE *OnMenuSelect)(
        ITfSystemLangBarItemSink *This,
        UINT wID);

    END_INTERFACE
} ITfSystemLangBarItemSinkVtbl;

interface ITfSystemLangBarItemSink {
    CONST_VTBL ITfSystemLangBarItemSinkVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfSystemLangBarItemSink_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfSystemLangBarItemSink_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfSystemLangBarItemSink_Release(This) (This)->lpVtbl->Release(This)
/*** ITfSystemLangBarItemSink methods ***/
#define ITfSystemLangBarItemSink_InitMenu(This,pMenu) (This)->lpVtbl->InitMenu(This,pMenu)
#define ITfSystemLangBarItemSink_OnMenuSelect(This,wID) (This)->lpVtbl->OnMenuSelect(This,wID)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfSystemLangBarItemSink_QueryInterface(ITfSystemLangBarItemSink* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfSystemLangBarItemSink_AddRef(ITfSystemLangBarItemSink* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfSystemLangBarItemSink_Release(ITfSystemLangBarItemSink* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfSystemLangBarItemSink methods ***/
static inline HRESULT ITfSystemLangBarItemSink_InitMenu(ITfSystemLangBarItemSink* This,ITfMenu *pMenu) {
    return This->lpVtbl->InitMenu(This,pMenu);
}
static inline HRESULT ITfSystemLangBarItemSink_OnMenuSelect(ITfSystemLangBarItemSink* This,UINT wID) {
    return This->lpVtbl->OnMenuSelect(This,wID);
}
#endif
#endif

#endif


#endif  /* __ITfSystemLangBarItemSink_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfSystemLangBarItemText interface
 */
#ifndef __ITfSystemLangBarItemText_INTERFACE_DEFINED__
#define __ITfSystemLangBarItemText_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfSystemLangBarItemText, 0x5c4ce0e5, 0xba49, 0x4b52, 0xac,0x6b, 0x3b,0x39,0x7b,0x4f,0x70,0x1f);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("5c4ce0e5-ba49-4b52-ac6b-3b397b4f701f")
ITfSystemLangBarItemText : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE SetItemText(
        const WCHAR *pch,
        ULONG cch) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetItemText(
        BSTR *pbstrText) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfSystemLangBarItemText, 0x5c4ce0e5, 0xba49, 0x4b52, 0xac,0x6b, 0x3b,0x39,0x7b,0x4f,0x70,0x1f)
#endif
#else
typedef struct ITfSystemLangBarItemTextVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfSystemLangBarItemText *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfSystemLangBarItemText *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfSystemLangBarItemText *This);

    /*** ITfSystemLangBarItemText methods ***/
    HRESULT (STDMETHODCALLTYPE *SetItemText)(
        ITfSystemLangBarItemText *This,
        const WCHAR *pch,
        ULONG cch);

    HRESULT (STDMETHODCALLTYPE *GetItemText)(
        ITfSystemLangBarItemText *This,
        BSTR *pbstrText);

    END_INTERFACE
} ITfSystemLangBarItemTextVtbl;

interface ITfSystemLangBarItemText {
    CONST_VTBL ITfSystemLangBarItemTextVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfSystemLangBarItemText_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfSystemLangBarItemText_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfSystemLangBarItemText_Release(This) (This)->lpVtbl->Release(This)
/*** ITfSystemLangBarItemText methods ***/
#define ITfSystemLangBarItemText_SetItemText(This,pch,cch) (This)->lpVtbl->SetItemText(This,pch,cch)
#define ITfSystemLangBarItemText_GetItemText(This,pbstrText) (This)->lpVtbl->GetItemText(This,pbstrText)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfSystemLangBarItemText_QueryInterface(ITfSystemLangBarItemText* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfSystemLangBarItemText_AddRef(ITfSystemLangBarItemText* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfSystemLangBarItemText_Release(ITfSystemLangBarItemText* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfSystemLangBarItemText methods ***/
static inline HRESULT ITfSystemLangBarItemText_SetItemText(ITfSystemLangBarItemText* This,const WCHAR *pch,ULONG cch) {
    return This->lpVtbl->SetItemText(This,pch,cch);
}
static inline HRESULT ITfSystemLangBarItemText_GetItemText(ITfSystemLangBarItemText* This,BSTR *pbstrText) {
    return This->lpVtbl->GetItemText(This,pbstrText);
}
#endif
#endif

#endif


#endif  /* __ITfSystemLangBarItemText_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER HWND_UserSize     (ULONG *, ULONG, HWND *);
unsigned char * __RPC_USER HWND_UserMarshal  (ULONG *, unsigned char *, HWND *);
unsigned char * __RPC_USER HWND_UserUnmarshal(ULONG *, unsigned char *, HWND *);
void            __RPC_USER HWND_UserFree     (ULONG *, HWND *);
ULONG           __RPC_USER BSTR_UserSize     (ULONG *, ULONG, BSTR *);
unsigned char * __RPC_USER BSTR_UserMarshal  (ULONG *, unsigned char *, BSTR *);
unsigned char * __RPC_USER BSTR_UserUnmarshal(ULONG *, unsigned char *, BSTR *);
void            __RPC_USER BSTR_UserFree     (ULONG *, BSTR *);
ULONG           __RPC_USER HBITMAP_UserSize     (ULONG *, ULONG, HBITMAP *);
unsigned char * __RPC_USER HBITMAP_UserMarshal  (ULONG *, unsigned char *, HBITMAP *);
unsigned char * __RPC_USER HBITMAP_UserUnmarshal(ULONG *, unsigned char *, HBITMAP *);
void            __RPC_USER HBITMAP_UserFree     (ULONG *, HBITMAP *);
ULONG           __RPC_USER HICON_UserSize     (ULONG *, ULONG, HICON *);
unsigned char * __RPC_USER HICON_UserMarshal  (ULONG *, unsigned char *, HICON *);
unsigned char * __RPC_USER HICON_UserUnmarshal(ULONG *, unsigned char *, HICON *);
void            __RPC_USER HICON_UserFree     (ULONG *, HICON *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __ctfutb_h__ */
