/*** Autogenerated by WIDL <undefined version> from drmexternals.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __drmexternals_h__
#define __drmexternals_h__

/* Forward declarations */

/* Headers for imported files */

#include <wmdrmsdk.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __drmexternals_h__ */
