/*** Autogenerated by WIDL <undefined version> from structuredquerycondition.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __structuredquerycondition_h__
#define __structuredquerycondition_h__

/* Forward declarations */

/* Headers for imported files */

#include <oaidl.h>
#include <ocidl.h>
#include <objidl.h>
#include <propidl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum tagCONDITION_TYPE {
    CT_AND_CONDITION = 0,
    CT_OR_CONDITION = 1ul,
    CT_NOT_CONDITION = 2ul,
    CT_LEAF_CONDITION = 3ul
} CONDITION_TYPE;
typedef enum tagCONDITION_OPERATION {
    COP_IMPLICIT = 0,
    COP_EQUAL = 1ul,
    COP_NOTEQUAL = 2ul,
    COP_LESSTHAN = 3ul,
    COP_GREATERTHAN = 4ul,
    COP_LESSTHANOREQUAL = 5ul,
    COP_GREATERTHANOREQUAL = 6ul,
    COP_VALUE_STARTSWITH = 7ul,
    COP_VALUE_ENDSWITH = 8ul,
    COP_VALUE_CONTAINS = 9ul,
    COP_VALUE_NOTCONTAINS = 10ul,
    COP_DOSWILDCARDS = 11ul,
    COP_WORD_EQUAL = 12ul,
    COP_WORD_STARTSWITH = 13ul,
    COP_APPLICATION_SPECIFIC = 14ul
} CONDITION_OPERATION;
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __structuredquerycondition_h__ */
