/*static char *SCCSID = "@(#)pmwin16.h   1.1 90/01/06";*/
/***************************************************************************\
*
* Module Name: PMWIN16.H
*
* OS/2 Presentation Manager API mapping include file
*
* Copyright (c) Microsoft Corporation 1989
* Copyright (c) International Business Machines Corporation 1989
*
* =======================================================================
*
* This file is used to map API names to their 16-bit ordinal name,
* when compiling with the 32-bit compiler and calling 16-bit APIs.
*
***************************************************************************/

/* XLATOFF */
#ifndef INCL_NOXLATE_WIN16
#define WinRegisterClass Win16RegisterClass
#define WinDefWindowProc Win16DefWindowProc
#define WinDestroyWindow Win16DestroyWindow
#define WinShowWindow Win16ShowWindow
#define WinQueryWindowRect Win16QueryWindowRect
#define WinGetPS Win16GetPS
#define WinReleasePS Win16ReleasePS
#define WinEndPaint Win16EndPaint
#define WinGetClipPS Win16GetClipPS
#define WinIsWindowShowing Win16IsWindowShowing
#define WinBeginPaint Win16BeginPaint
#define WinOpenWindowDC Win16OpenWindowDC
#define WinScrollWindow Win16ScrollWindow
#define WinFillRect Win16FillRect
#define WinQueryVersion Win16QueryVersion
#define WinInitialize Win16Initialize
#define WinTerminate Win16Terminate
#define WinQueryAnchorBlock Win16QueryAnchorBlock
#define WinCreateWindow Win16CreateWindow
#define WinEnableWindow Win16EnableWindow
#define WinIsWindowEnabled Win16IsWindowEnabled
#define WinEnableWindowUpdate Win16EnableWindowUpdate
#define WinIsWindowVisible Win16IsWindowVisible
#define WinQueryWindowText Win16QueryWindowText
#define WinSetWindowText Win16SetWindowText
#define WinQueryWindowTextLength Win16QueryWindowTextLength
#define WinWindowFromID Win16WindowFromID
#define WinIsWindow Win16IsWindow
#define WinQueryWindow Win16QueryWindow
#define WinMultWindowFromIDs Win16MultWindowFromIDs
#define WinSetParent Win16SetParent
#define WinIsChild Win16IsChild
#define WinSetOwner Win16SetOwner
#define WinQueryWindowProcess Win16QueryWindowProcess
#define WinQueryObjectWindow Win16QueryObjectWindow
#define WinQueryDesktopWindow Win16QueryDesktopWindow
#define WinSetWindowPos Win16SetWindowPos
#define WinQueryWindowPos Win16QueryWindowPos
#define WinSetMultWindowPos Win16SetMultWindowPos
#define WinUpdateWindow Win16UpdateWindow
#define WinInvalidateRect Win16InvalidateRect
#define WinInvalidateRegion Win16InvalidateRegion
#define WinInvertRect Win16InvertRect
#define WinDrawBitmap Win16DrawBitmap
#define WinDrawText Win16DrawText
#define WinDrawBorder Win16DrawBorder
#define WinLoadString Win16LoadString
#define WinLoadMessage Win16LoadMessage
#define WinSetActiveWindow Win16SetActiveWindow
#define WinSetAtomTableOwner Win16SetAtomTableOwner
#define WinSubclassWindow Win16SubclassWindow
#define WinQueryClassName Win16QueryClassName
#define WinQueryClassInfo Win16QueryClassInfo
#define WinQueryActiveWindow Win16QueryActiveWindow
#define WinIsThreadActive Win16IsThreadActive
#define WinQuerySysModalWindow Win16QuerySysModalWindow
#define WinLockWindow Win16LockWindow
#define WinRegisterWindowDestroy Win16RegisterWindowDestroy
#define WinSetSysModalWindow Win16SetSysModalWindow
#define WinQueryWindowLockCount Win16QueryWindowLockCount
#define WinQueryWindowUShort Win16QueryWindowUShort
#define WinSetWindowUShort Win16SetWindowUShort
#define WinQueryWindowULong Win16QueryWindowULong
#define WinSetWindowULong Win16SetWindowULong
#define WinQueryWindowPtr Win16QueryWindowPtr
#define WinSetWindowPtr Win16SetWindowPtr
#define WinSetWindowBits Win16SetWindowBits
#define WinBeginEnumWindows Win16BeginEnumWindows
#define WinGetNextWindow Win16GetNextWindow
#define WinEndEnumWindows Win16EndEnumWindows
#define WinWindowFromPoint Win16WindowFromPoint
#define WinMapWindowPoints Win16MapWindowPoints
#define WinValidateRect Win16ValidateRect
#define WinValidateRegion Win16ValidateRegion
#define WinWindowFromDC Win16WindowFromDC
#define WinQueryWindowDC Win16QueryWindowDC
#define WinGetScreenPS Win16GetScreenPS
#define WinLockWindowUpdate Win16LockWindowUpdate
#define WinLockVisRegions Win16LockVisRegions
#define WinQueryUpdateRect Win16QueryUpdateRect
#define WinQueryUpdateRegion Win16QueryUpdateRegion
#define WinExcludeUpdateRegion Win16ExcludeUpdateRegion
#define WinSendMsg Win16SendMsg
#define WinCreateMsgQueue Win16CreateMsgQueue
#define WinDestroyMsgQueue Win16DestroyMsgQueue
#define WinQueryQueueInfo Win16QueryQueueInfo
#define WinCancelShutdown Win16CancelShutdown
#define WinGetMsg Win16GetMsg
#define WinPeekMsg Win16PeekMsg
#define WinDispatchMsg Win16DispatchMsg
#define WinPostMsg Win16PostMsg
#define WinRegisterUserMsg Win16RegisterUserMsg
#define WinRegisterUserDatatype Win16RegisterUserDatatype
#define WinSetMsgMode Win16SetMsgMode
#define WinSetSynchroMode Win16SetSynchroMode
#define WinInSendMsg Win16InSendMsg
#define WinBroadcastMsg Win16BroadcastMsg
#define WinWaitMsg Win16WaitMsg
#define WinQueryQueueStatus Win16QueryQueueStatus
#define WinQueryMsgPos Win16QueryMsgPos
#define WinQueryMsgTime Win16QueryMsgTime
#define WinMsgSemWait Win16MsgSemWait
#define WinMsgMuxSemWait Win16MsgMuxSemWait
#define WinPostQueueMsg Win16PostQueueMsg
#define WinSetMsgInterest Win16SetMsgInterest
#define WinSetClassMsgInterest Win16SetClassMsgInterest
#define WinSetFocus Win16SetFocus
#define WinFocusChange Win16FocusChange
#define WinSetCapture Win16SetCapture
#define WinQueryCapture Win16QueryCapture
#define WinQueryFocus Win16QueryFocus
#define WinGetKeyState Win16GetKeyState
#define WinGetPhysKeyState Win16GetPhysKeyState
#define WinEnablePhysInput Win16EnablePhysInput
#define WinIsPhysInputEnabled Win16IsPhysInputEnabled
#define WinSetKeyboardStateTable Win16SetKeyboardStateTable
#define WinGetDlgMsg Win16GetDlgMsg
#define WinLoadDlg Win16LoadDlg
#define WinDlgBox Win16DlgBox
#define WinDismissDlg Win16DismissDlg
#define WinQueryDlgItemShort Win16QueryDlgItemShort
#define WinSetDlgItemShort Win16SetDlgItemShort
#define WinSetDlgItemText Win16SetDlgItemText
#define WinQueryDlgItemText Win16QueryDlgItemText
#define WinQueryDlgItemTextLength Win16QueryDlgItemTextLength
#define WinDefDlgProc Win16DefDlgProc
#define WinAlarm Win16Alarm
#define WinMessageBox Win16MessageBox
#define WinProcessDlg Win16ProcessDlg
#define WinSendDlgItemMsg Win16SendDlgItemMsg
#define WinMapDlgPoints Win16MapDlgPoints
#define WinEnumDlgItem Win16EnumDlgItem
#define WinSubstituteStrings Win16SubstituteStrings
#define WinCreateDlg Win16CreateDlg
#define WinLoadMenu Win16LoadMenu
#define WinCreateMenu Win16CreateMenu
#define WinCreateStdWindow Win16CreateStdWindow
#define WinFlashWindow Win16FlashWindow
#define WinCreateFrameControls Win16CreateFrameControls
#define WinFormatFrame Win16FormatFrame
#define WinCalcFrameRect Win16CalcFrameRect
#define WinGetMinPosition Win16GetMinPosition
#define WinGetMaxPosition Win16GetMaxPosition
#define WinCopyRect Win16CopyRect
#define WinSetRect Win16SetRect
#define WinIsRectEmpty Win16IsRectEmpty
#define WinEqualRect Win16EqualRect
#define WinSetRectEmpty Win16SetRectEmpty
#define WinOffsetRect Win16OffsetRect
#define WinInflateRect Win16InflateRect
#define WinPtInRect Win16PtInRect
#define WinIntersectRect Win16IntersectRect
#define WinUnionRect Win16UnionRect
#define WinSubtractRect Win16SubtractRect
#define WinMakeRect Win16MakeRect
#define WinMakePoints Win16MakePoints
#define WinQuerySysValue Win16QuerySysValue
#define WinSetSysValue Win16SetSysValue
#define WinQueryPalette Win16QueryPalette
#define WinQuerySysColor Win16QuerySysColor
#define WinSetSysColors Win16SetSysColors
#define WinStartTimer Win16StartTimer
#define WinStopTimer Win16StopTimer
#define WinGetCurrentTime Win16GetCurrentTime
#define WinLoadAccelTable Win16LoadAccelTable
#define WinCreateAccelTable Win16CreateAccelTable
#define WinDestroyAccelTable Win16DestroyAccelTable
#define WinCopyAccelTable Win16CopyAccelTable
#define WinTranslateAccel Win16TranslateAccel
#define WinSetAccelTable Win16SetAccelTable
#define WinQueryAccelTable Win16QueryAccelTable
#define WinTrackRect Win16TrackRect
#define WinShowTrackRect Win16ShowTrackRect
#define WinSetClipbrdOwner Win16SetClipbrdOwner
#define WinSetClipbrdData Win16SetClipbrdData
#define WinQueryClipbrdData Win16QueryClipbrdData
#define WinQueryClipbrdFmtInfo Win16QueryClipbrdFmtInfo
#define WinSetClipbrdViewer Win16SetClipbrdViewer
#define WinEnumClipbrdFmts Win16EnumClipbrdFmts
#define WinEmptyClipbrd Win16EmptyClipbrd
#define WinOpenClipbrd Win16OpenClipbrd
#define WinCloseClipbrd Win16CloseClipbrd
#define WinQueryClipbrdOwner Win16QueryClipbrdOwner
#define WinQueryClipbrdViewer Win16QueryClipbrdViewer
#define WinDestroyCursor Win16DestroyCursor
#define WinShowCursor Win16ShowCursor
#define WinCreateCursor Win16CreateCursor
#define WinQueryCursorInfo Win16QueryCursorInfo
#define WinSetPointer Win16SetPointer
#define WinShowPointer Win16ShowPointer
#define WinQuerySysPointer Win16QuerySysPointer
#define WinLoadPointer Win16LoadPointer
#define WinDestroyPointer Win16DestroyPointer
#define WinCreatePointer Win16CreatePointer
#define WinQueryPointer Win16QueryPointer
#define WinSetPointerPos Win16SetPointerPos
#define WinQueryPointerPos Win16QueryPointerPos
#define WinQueryPointerInfo Win16QueryPointerInfo
#define WinDrawPointer Win16DrawPointer
#define WinGetSysBitmap Win16GetSysBitmap
#define WinSetHook Win16SetHook
#define WinReleaseHook Win16ReleaseHook
#define WinCallMsgFilter Win16CallMsgFilter
#define WinQueryCp Win16QueryCp
#define WinSetCp Win16SetCp
#define WinQueryCpList Win16QueryCpList
#define WinCpTranslateString Win16CpTranslateString
#define WinCpTranslateChar Win16CpTranslateChar
#define WinUpper Win16Upper
#define WinUpperChar Win16UpperChar
#define WinNextChar Win16NextChar
#define WinPrevChar Win16PrevChar
#define WinCompareStrings Win16CompareStrings
#define WinCreateHeap Win16CreateHeap
#define WinDestroyHeap Win16DestroyHeap
#define WinAvailMem Win16AvailMem
#define WinAllocMem Win16AllocMem
#define WinReallocMem Win16ReallocMem
#define WinFreeMem Win16FreeMem
#define WinLockHeap Win16LockHeap
#define WinQuerySystemAtomTable Win16QuerySystemAtomTable
#define WinCreateAtomTable Win16CreateAtomTable
#define WinDestroyAtomTable Win16DestroyAtomTable
#define WinAddAtom Win16AddAtom
#define WinFindAtom Win16FindAtom
#define WinDeleteAtom Win16DeleteAtom
#define WinQueryAtomUsage Win16QueryAtomUsage
#define WinQueryAtomLength Win16QueryAtomLength
#define WinQueryAtomName Win16QueryAtomName
#define WinCatch Win16Catch
#define WinThrow Win16Throw
#define WinGetLastError Win16GetLastError
#define WinGetErrorInfo Win16GetErrorInfo
#define WinFreeErrorInfo Win16FreeErrorInfo
#define WinDdeInitiate Win16DdeInitiate
#define WinDdeInitiate2 Win16DdeInitiate2
#define WinDdeRespond Win16DdeRespond
#define WinDdeRespond2 Win16DdeRespond2
#define WinDdePostMsg Win16DdePostMsg
#define WinDdePostMsg2 Win16DdePostMsg2
#define WinDeleteProcedure Win16DeleteProcedure
#define WinDeleteLibrary Win16DeleteLibrary
#define WinLoadProcedure Win16LoadProcedure
#define WinLoadLibrary Win16LoadLibrary
#define WinSetClassThunkProc Win16SetClassThunkProc
#define WinQueryClassThunkProc Win16QueryClassThunkProc
#define WinSetWindowThunkProc Win16SetWindowThunkProc
#define WinQueryWindowThunkProc Win16QueryWindowThunkProc
#define WinQueryWindowModel Win16QueryWindowModel
#define WinSetDesktopBkgnd Win16SetDesktopBkgnd
#define WinQueryDesktopBkgnd Win16QueryDesktopBkgnd
#define WinPopupMenu Win16PopupMenu
#define WinSetPresParam Win16SetPresParam          
#define WinQueryPresParam Win16QueryPresParam      
#define WinRemovePresParam Win16RemovePresParam     
#define WinRealizePalette Win16RealizePalette
#define WinCreatePointerIndirect Win16CreatePointerIndirect
#endif /* INCL_NOXLATE_WIN16 */
/* XLATON */
