/* Soft386 native VIO/KBD/SESMGR bridge.
 *
 * Guest pointers never cross into a native DLL.  Every buffer/string/structure
 * is copied into bounded host storage first, and output is copied back only
 * after guest-range validation.  The same marshal layer accepts normal 32-bit
 * cdecl frames and the packed C/386 Pascal frames generated by the migration
 * helper lowering pass.
 */
#include "soft386_system_bridge.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#endif

#ifndef __cdecl
#define __cdecl
#endif

#define OS2_NO_ERROR                 0u
#define OS2_ERROR_INVALID_FUNCTION   1u
#define OS2_ERROR_INVALID_HANDLE     6u
#define OS2_ERROR_NOT_ENOUGH_MEMORY  8u
#define OS2_ERROR_INVALID_PARAMETER 87u
#define BRIDGE_MAX_STRING          4096u
#define BRIDGE_MAX_BUFFER      0x01000000u
#define SES_TEXT_MAX               260u
#define SES_WIRE_SIZE              528u

/* Packed Pascal frame widths are ordered exactly as they appear at ESP+4:
 * rightmost argument first.  This table is intentionally kept in sync with
 * loader/os2host32.c's frozen C/386 descriptors. */
static const struct Soft386C386ApiDesc c386_apis[] = {
    /* Historical 16-bit DOSCALLS entry used by INCL_16 C/386 programs.
     * The helper is lowered to a 32-bit Soft386 hostcall, but DosSleep itself
     * remains jar-owned so it participates in virtual-thread scheduling. */
    {"DOSCALLS","DosSleep",32,1,{4,0,0,0,0,0,0}},
    {"VIOCALLS","VioScrollUp",7,7,{2,4,2,2,2,2,2}},
    {"VIOCALLS","VioGetCurPos",9,3,{2,4,4,0,0,0,0}},
    {"VIOCALLS","VioWrtCharStr",13,5,{2,2,2,2,4,0,0}},
    {"VIOCALLS","VioSetCurPos",15,3,{2,2,2,0,0,0,0}},
    {"VIOCALLS","VioWrtTTY",19,3,{2,2,4,0,0,0,0}},
    {"VIOCALLS","VioGetMode",21,2,{2,4,0,0,0,0,0}},
    {"VIOCALLS","VioReadCellStr",24,5,{2,2,2,4,4,0,0}},
    {"VIOCALLS","VioWrtNAttr",26,5,{2,2,2,2,4,0,0}},
    {"VIOCALLS","VioGetCurType",27,2,{2,4,0,0,0,0,0}},
    {"VIOCALLS","VioSetCurType",32,2,{2,4,0,0,0,0,0}},
    {"VIOCALLS","VioWrtCharStrAtt",48,6,{2,4,2,2,2,4,0}},
    {"VIOCALLS","VioWrtNCell",52,5,{2,2,2,2,4,0,0}},
    {"KBDCALLS","KbdCharIn",4,3,{2,2,4,0,0,0,0}},
    {"KBDCALLS","KbdStringIn",9,4,{2,2,4,4,0,0,0}},
    {"KBDCALLS","KbdGetStatus",10,2,{2,4,0,0,0,0,0}},
    {"KBDCALLS","KbdSetStatus",11,2,{2,4,0,0,0,0,0}},
    {"KBDCALLS","KbdFlushBuffer",13,1,{2,0,0,0,0,0,0}},
    {"KBDCALLS","KbdPeek",22,2,{2,4,0,0,0,0,0}}
};

static int eqi(const char *a, const char *b)
{
    unsigned char ca, cb;
    if (!a || !b) return 0;
    for (;;) {
        ca=(unsigned char)*a++; cb=(unsigned char)*b++;
        if (ca>='a'&&ca<='z') ca=(unsigned char)(ca-'a'+'A');
        if (cb>='a'&&cb<='z') cb=(unsigned char)(cb-'a'+'A');
        if (ca!=cb) return 0;
        if (!ca) return 1;
    }
}

uint32_t soft386_c386_desc_count(void)
{
    return (uint32_t)(sizeof(c386_apis)/sizeof(c386_apis[0]));
}
int soft386_c386_desc_index(const char *module, uint32_t ordinal)
{
    uint32_t i;
    for(i=0;i<soft386_c386_desc_count();++i)
        if(eqi(module,c386_apis[i].module)&&ordinal==c386_apis[i].ordinal)
            return (int)i;
    return -1;
}
const struct Soft386C386ApiDesc *soft386_c386_desc_by_id(uint32_t id)
{
    if(id==0 || id>soft386_c386_desc_count()) return NULL;
    return &c386_apis[id-1u];
}

#ifdef _WIN32
struct WinModule { HMODULE h; };
static void *win_get_proc(void *opaque,uint32_t ordinal)
{
    struct WinModule *m=(struct WinModule*)opaque; FARPROC p;
    if(!m||!m->h||ordinal>65535u)return NULL;
    p=GetProcAddress(m->h,(LPCSTR)(uintptr_t)(uint16_t)ordinal);
    return (void*)(uintptr_t)p;
}
static void win_close(void *opaque)
{
    struct WinModule *m=(struct WinModule*)opaque;
    if(!m)return; if(m->h)FreeLibrary(m->h); free(m);
}
#endif

static void module_set(struct Soft386NativeModule *m,const char *label,
                       void *opaque,void *(*get_proc)(void*,uint32_t),
                       void (*close_fn)(void*),int trace)
{
    memset(m,0,sizeof(*m));m->label=label;m->opaque=opaque;m->get_proc=get_proc;
    m->close=close_fn;m->trace=trace;m->loaded=get_proc!=NULL;
}

static int module_open(struct Soft386NativeModule *m,const char *label,
                       const char *path,const char *fallback,int required,int trace)
{
    module_set(m,label,NULL,NULL,NULL,trace);
#ifdef _WIN32
    {
        struct WinModule *wm; HMODULE h; const char *name=(path&&path[0])?path:fallback;
        h=LoadLibraryA(name);
        if(!h){
            if(required)fprintf(stderr,"soft386: cannot load native %s bridge %s (Win32 error %lu)\n",label,name,(unsigned long)GetLastError());
            else if(trace)fprintf(stderr,"soft386: native %s bridge not loaded: %s\n",label,name);
            return 0;
        }
        wm=(struct WinModule*)calloc(1,sizeof(*wm)); if(!wm){FreeLibrary(h);return 0;}
        wm->h=h;module_set(m,label,wm,win_get_proc,win_close,trace);
        if(trace)fprintf(stderr,"soft386: native %s bridge loaded: %s\n",label,name);
        return 1;
    }
#else
    (void)path;(void)fallback;
    if(required)fprintf(stderr,"soft386: native %s bridge is available only on Win32\n",label);
    return 0;
#endif
}

int soft386_system_bridge_open_mask(struct Soft386SystemBridge *b,uint32_t mask,
                               const char *vio_path,int vio_required,
                               const char *kbd_path,int kbd_required,
                               const char *ses_path,int ses_required,int trace)
{
    int ok=1;
    if(!b) return 0;
    memset(b,0,sizeof(*b));
    b->trace=trace;
    if((mask&SOFT386_SYS_VIO)!=0u && !module_open(&b->vio,"VIOCALLS",vio_path,"VIOCALLS.dll",vio_required,trace)&&vio_required)ok=0;
    if((mask&SOFT386_SYS_KBD)!=0u && !module_open(&b->kbd,"KBDCALLS",kbd_path,"KBDCALLS.dll",kbd_required,trace)&&kbd_required)ok=0;
    if((mask&SOFT386_SYS_SES)!=0u && !module_open(&b->ses,"SESMGR",ses_path,"SESMGR.dll",ses_required,trace)&&ses_required)ok=0;
    return ok;
}
int soft386_system_bridge_open(struct Soft386SystemBridge *b,
                               const char *vio_path,int vio_required,
                               const char *kbd_path,int kbd_required,
                               const char *ses_path,int ses_required,int trace)
{
    return soft386_system_bridge_open_mask(b,SOFT386_SYS_ALL,
        vio_path,vio_required,kbd_path,kbd_required,ses_path,ses_required,trace);
}
void soft386_system_bridge_close(struct Soft386SystemBridge *b)
{
    struct Soft386NativeModule *m[3];int i;if(!b)return;m[0]=&b->vio;m[1]=&b->kbd;m[2]=&b->ses;
    for(i=0;i<3;i++){if(m[i]->close&&m[i]->opaque)m[i]->close(m[i]->opaque);memset(m[i],0,sizeof(*m[i]));}
    b->trace=0;
}
int soft386_system_bridge_set_provider(struct Soft386SystemBridge *b,const char *module,
                                       void *opaque,void *(*get_proc)(void*,uint32_t),
                                       void (*close_fn)(void*),int trace)
{
    struct Soft386NativeModule *m;if(!b)return 0;
    if(eqi(module,"VIOCALLS"))m=&b->vio;else if(eqi(module,"KBDCALLS"))m=&b->kbd;
    else if(eqi(module,"SESMGR"))m=&b->ses;else return 0;
    module_set(m,module,opaque,get_proc,close_fn,trace);return 1;
}

static struct Soft386NativeModule *get_module(struct Soft386SystemBridge *b,const char *module)
{
    if(!b) return NULL;
    if(eqi(module,"VIOCALLS")) return &b->vio;
    if(eqi(module,"KBDCALLS")) return &b->kbd;
    if(eqi(module,"SESMGR")) return &b->ses;
    return NULL;
}
static void *proc(struct Soft386NativeModule *m,uint32_t ord)
{return (m&&m->loaded&&m->get_proc)?m->get_proc(m->opaque,ord):NULL;}
static void trace_call(struct Soft386NativeModule *m,uint32_t ord,const char *name)
{if(m&&m->trace)fprintf(stderr,"soft386: native %s.%u %s [marshalled]\n",m->label?m->label:"?",ord,name);}
static uint32_t missing(struct Soft386NativeModule *m,uint32_t ord)
{if(m&&m->trace)fprintf(stderr,"soft386: native %s.%u export missing\n",m->label?m->label:"?",ord);return OS2_ERROR_INVALID_FUNCTION;}
static int need(const struct Soft386GuestMemoryOps *m,uint32_t p,uint32_t cb,int wr)
{return (!p&&cb)?0:m->valid(m->opaque,p,cb,wr);}
static uint16_t ru16(const struct Soft386GuestMemoryOps *m,uint32_t p)
{unsigned char b[2];if(!m->read(m->opaque,p,b,2))return 0;return (uint16_t)(b[0]|((uint16_t)b[1]<<8));}
static uint32_t ru32(const struct Soft386GuestMemoryOps *m,uint32_t p)
{return m->read_u32(m->opaque,p);}
static int wu16(const struct Soft386GuestMemoryOps *m,uint32_t p,uint16_t v)
{unsigned char b[2];b[0]=(unsigned char)v;b[1]=(unsigned char)(v>>8);return m->write(m->opaque,p,b,2);}
static int get_cstr(const struct Soft386GuestMemoryOps *m,uint32_t p,char *s,uint32_t cap)
{return p&&s&&cap&&m->read_cstr(m->opaque,p,s,cap);}
static void *temp_alloc(uint32_t cb){if(cb>BRIDGE_MAX_BUFFER)return NULL;if(!cb)cb=1;return calloc(1,cb);}
#define PCAST(type,p) ((type)(uintptr_t)(p))

static uint32_t vio_dispatch(struct Soft386NativeModule *mod,const struct Soft386GuestMemoryOps *m,uint32_t ord,const uint32_t *a)
{
    void *vp=proc(mod,ord),*buf;uint32_t rc;uint16_t w1,w2;char *text;
    if(!vp)return missing(mod,ord);
    switch(ord){
    case 7:{typedef uint16_t(__cdecl*Fn)(uint16_t,uint16_t,uint16_t,uint16_t,uint16_t,const unsigned char*,uint16_t);unsigned char cell[2];trace_call(mod,ord,"VioScrollUp");if(!need(m,a[5],2,0)||!m->read(m->opaque,a[5],cell,2))return OS2_ERROR_INVALID_PARAMETER;return PCAST(Fn,vp)((uint16_t)a[0],(uint16_t)a[1],(uint16_t)a[2],(uint16_t)a[3],(uint16_t)a[4],cell,(uint16_t)a[6]);}
    case 9:{typedef uint16_t(__cdecl*Fn)(uint16_t*,uint16_t*,uint16_t);trace_call(mod,ord,"VioGetCurPos");if(!need(m,a[0],2,1)||!need(m,a[1],2,1))return OS2_ERROR_INVALID_PARAMETER;w1=w2=0;rc=PCAST(Fn,vp)(&w1,&w2,(uint16_t)a[2]);if(!rc&&(!wu16(m,a[0],w1)||!wu16(m,a[1],w2)))return OS2_ERROR_INVALID_PARAMETER;return rc;}
    case 13:{typedef uint16_t(__cdecl*Fn)(const char*,uint16_t,uint16_t,uint16_t,uint16_t);trace_call(mod,ord,"VioWrtCharStr");if(a[1]&&!need(m,a[0],a[1],0))return OS2_ERROR_INVALID_PARAMETER;text=(char*)temp_alloc(a[1]);if(!text)return OS2_ERROR_NOT_ENOUGH_MEMORY;if(a[1]&&!m->read(m->opaque,a[0],text,a[1])){free(text);return OS2_ERROR_INVALID_PARAMETER;}rc=PCAST(Fn,vp)(text,(uint16_t)a[1],(uint16_t)a[2],(uint16_t)a[3],(uint16_t)a[4]);free(text);return rc;}
    case 15:{typedef uint16_t(__cdecl*Fn)(uint16_t,uint16_t,uint16_t);trace_call(mod,ord,"VioSetCurPos");return PCAST(Fn,vp)((uint16_t)a[0],(uint16_t)a[1],(uint16_t)a[2]);}
    case 19:{typedef uint16_t(__cdecl*Fn)(const char*,uint16_t,uint16_t);trace_call(mod,ord,"VioWrtTTY");if(a[1]&&!need(m,a[0],a[1],0))return OS2_ERROR_INVALID_PARAMETER;text=(char*)temp_alloc(a[1]);if(!text)return OS2_ERROR_NOT_ENOUGH_MEMORY;if(a[1]&&!m->read(m->opaque,a[0],text,a[1])){free(text);return OS2_ERROR_INVALID_PARAMETER;}rc=PCAST(Fn,vp)(text,(uint16_t)a[1],(uint16_t)a[2]);free(text);return rc;}
    case 21:{typedef uint16_t(__cdecl*Fn)(void*,uint16_t);uint16_t cb;trace_call(mod,ord,"VioGetMode");if(!need(m,a[0],2,0))return OS2_ERROR_INVALID_PARAMETER;cb=ru16(m,a[0]);if(cb<8||cb>256||!need(m,a[0],cb,1))return OS2_ERROR_INVALID_PARAMETER;buf=calloc(1,256);if(!buf)return OS2_ERROR_NOT_ENOUGH_MEMORY;if(!m->read(m->opaque,a[0],buf,cb)){free(buf);return OS2_ERROR_INVALID_PARAMETER;}rc=PCAST(Fn,vp)(buf,(uint16_t)a[1]);if(!rc&&!m->write(m->opaque,a[0],buf,cb))rc=OS2_ERROR_INVALID_PARAMETER;free(buf);return rc;}
    case 24:{typedef uint16_t(__cdecl*Fn)(unsigned char*,uint16_t*,uint16_t,uint16_t,uint16_t);uint16_t cb;trace_call(mod,ord,"VioReadCellStr");if(!need(m,a[1],2,1))return OS2_ERROR_INVALID_PARAMETER;cb=ru16(m,a[1]);if(cb&&!need(m,a[0],cb,1))return OS2_ERROR_INVALID_PARAMETER;buf=temp_alloc(cb);if(!buf)return OS2_ERROR_NOT_ENOUGH_MEMORY;rc=PCAST(Fn,vp)((unsigned char*)buf,&cb,(uint16_t)a[2],(uint16_t)a[3],(uint16_t)a[4]);if((!rc&&cb&&!m->write(m->opaque,a[0],buf,cb))||!wu16(m,a[1],cb))rc=OS2_ERROR_INVALID_PARAMETER;free(buf);return rc;}
    case 26:{typedef uint16_t(__cdecl*Fn)(const unsigned char*,uint16_t,uint16_t,uint16_t,uint16_t);unsigned char attr;trace_call(mod,ord,"VioWrtNAttr");if(!need(m,a[0],1,0)||!m->read(m->opaque,a[0],&attr,1))return OS2_ERROR_INVALID_PARAMETER;return PCAST(Fn,vp)(&attr,(uint16_t)a[1],(uint16_t)a[2],(uint16_t)a[3],(uint16_t)a[4]);}
    case 27:case 32:{typedef uint16_t(__cdecl*Fn)(void*,uint16_t);unsigned char ci[8];trace_call(mod,ord,ord==27?"VioGetCurType":"VioSetCurType");if(!need(m,a[0],8,ord==27))return OS2_ERROR_INVALID_PARAMETER;memset(ci,0,sizeof(ci));if(ord==32&&!m->read(m->opaque,a[0],ci,8))return OS2_ERROR_INVALID_PARAMETER;rc=PCAST(Fn,vp)(ci,(uint16_t)a[1]);if(ord==27&&!rc&&!m->write(m->opaque,a[0],ci,8))rc=OS2_ERROR_INVALID_PARAMETER;return rc;}
    case 48:{typedef uint16_t(__cdecl*Fn)(const char*,uint16_t,uint16_t,uint16_t,const unsigned char*,uint16_t);unsigned char attr;trace_call(mod,ord,"VioWrtCharStrAtt");if(a[1]&&!need(m,a[0],a[1],0))return OS2_ERROR_INVALID_PARAMETER;if(!need(m,a[4],1,0)||!m->read(m->opaque,a[4],&attr,1))return OS2_ERROR_INVALID_PARAMETER;text=(char*)temp_alloc(a[1]);if(!text)return OS2_ERROR_NOT_ENOUGH_MEMORY;if(a[1]&&!m->read(m->opaque,a[0],text,a[1])){free(text);return OS2_ERROR_INVALID_PARAMETER;}rc=PCAST(Fn,vp)(text,(uint16_t)a[1],(uint16_t)a[2],(uint16_t)a[3],&attr,(uint16_t)a[5]);free(text);return rc;}
    case 52:{typedef uint16_t(__cdecl*Fn)(const unsigned char*,uint16_t,uint16_t,uint16_t,uint16_t);unsigned char cell[2];trace_call(mod,ord,"VioWrtNCell");if(!need(m,a[0],2,0)||!m->read(m->opaque,a[0],cell,2))return OS2_ERROR_INVALID_PARAMETER;return PCAST(Fn,vp)(cell,(uint16_t)a[1],(uint16_t)a[2],(uint16_t)a[3],(uint16_t)a[4]);}
    default:return OS2_ERROR_INVALID_FUNCTION;
    }
}

static uint32_t kbd_dispatch(struct Soft386NativeModule *mod,const struct Soft386GuestMemoryOps *m,uint32_t ord,const uint32_t *a)
{
    void *vp=proc(mod,ord),*buf;uint32_t rc;unsigned char ki[10],info[10],lenbuf[4];uint16_t cap,used;
    if(!vp)return missing(mod,ord);
    switch(ord){
    case 4:{typedef uint16_t(__cdecl*Fn)(void*,uint16_t,uint16_t);trace_call(mod,ord,"KbdCharIn");if(!need(m,a[0],10,1))return OS2_ERROR_INVALID_PARAMETER;memset(ki,0,sizeof(ki));rc=PCAST(Fn,vp)(ki,(uint16_t)a[1],(uint16_t)a[2]);if(!rc&&!m->write(m->opaque,a[0],ki,10))rc=OS2_ERROR_INVALID_PARAMETER;return rc;}
    case 9:{typedef uint16_t(__cdecl*Fn)(char*,void*,uint16_t,uint16_t);trace_call(mod,ord,"KbdStringIn");if(!need(m,a[1],4,1)||!m->read(m->opaque,a[1],lenbuf,4))return OS2_ERROR_INVALID_PARAMETER;cap=(uint16_t)(lenbuf[0]|((uint16_t)lenbuf[1]<<8));if(cap&&!need(m,a[0],cap,1))return OS2_ERROR_INVALID_PARAMETER;buf=temp_alloc(cap);if(!buf)return OS2_ERROR_NOT_ENOUGH_MEMORY;rc=PCAST(Fn,vp)((char*)buf,lenbuf,(uint16_t)a[2],(uint16_t)a[3]);used=(uint16_t)(lenbuf[2]|((uint16_t)lenbuf[3]<<8));if(used>cap)used=cap;if((!rc&&used&&!m->write(m->opaque,a[0],buf,used))||!m->write(m->opaque,a[1],lenbuf,4))rc=OS2_ERROR_INVALID_PARAMETER;free(buf);return rc;}
    case 10:case 11:{typedef uint16_t(__cdecl*Fn)(void*,uint16_t);trace_call(mod,ord,ord==10?"KbdGetStatus":"KbdSetStatus");if(!need(m,a[0],10,ord==10))return OS2_ERROR_INVALID_PARAMETER;memset(info,0,sizeof(info));if(ord==11&&!m->read(m->opaque,a[0],info,10))return OS2_ERROR_INVALID_PARAMETER;rc=PCAST(Fn,vp)(info,(uint16_t)a[1]);if(ord==10&&!rc&&!m->write(m->opaque,a[0],info,10))rc=OS2_ERROR_INVALID_PARAMETER;return rc;}
    case 13:{typedef uint16_t(__cdecl*Fn)(uint16_t);trace_call(mod,ord,"KbdFlushBuffer");return PCAST(Fn,vp)((uint16_t)a[0]);}
    case 22:{typedef uint16_t(__cdecl*Fn)(void*,uint16_t);trace_call(mod,ord,"KbdPeek");if(!need(m,a[0],10,1))return OS2_ERROR_INVALID_PARAMETER;memset(ki,0,sizeof(ki));rc=PCAST(Fn,vp)(ki,(uint16_t)a[1]);if(!rc&&!m->write(m->opaque,a[0],ki,10))rc=OS2_ERROR_INVALID_PARAMETER;return rc;}
    default:return OS2_ERROR_INVALID_FUNCTION;
    }
}

#pragma pack(push,2)
struct StartDataHost {
    uint16_t Length,Related,FgBg,TraceOpt;
    char *PgmTitle,*PgmName; unsigned char *PgmInputs,*TermQ,*Environment;
    uint16_t InheritOpt,SessionType; char *IconFile; uint32_t PgmHandle;
    uint16_t PgmControl,InitXPos,InitYPos,InitXSize,InitYSize,Reserved;
    char *ObjectBuffer; uint32_t ObjectBuffLen;
};
#pragma pack(pop)

static char *dup_guest_cstr(const struct Soft386GuestMemoryOps *m,uint32_t p)
{char tmp[BRIDGE_MAX_STRING],*r;if(!p)return NULL;if(!get_cstr(m,p,tmp,sizeof(tmp)))return NULL;r=(char*)malloc(strlen(tmp)+1);if(r)strcpy(r,tmp);return r;}
static unsigned char *dup_multisz(const struct Soft386GuestMemoryOps *m,uint32_t p)
{unsigned char *r;uint32_t n=0;unsigned char c=0,prev=1;if(!p)return NULL;r=(unsigned char*)malloc(65536u);if(!r)return NULL;while(n<65536u){if(!m->read(m->opaque,p+n,&c,1)){free(r);return NULL;}r[n++]=c;if(c==0&&prev==0)return r;prev=c;}free(r);return NULL;}
static uint16_t b16(const unsigned char *p){return (uint16_t)(p[0]|((uint16_t)p[1]<<8));}
static uint32_t b32(const unsigned char *p){return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}

static uint32_t ses_dispatch(struct Soft386NativeModule *mod,const struct Soft386GuestMemoryOps *m,uint32_t ord,const uint32_t *a)
{
    void *vp=proc(mod,ord);uint32_t rc;if(!vp)return missing(mod,ord);
    if(ord==5){typedef uint32_t(__cdecl*Fn)(uint32_t,char*);char s[BRIDGE_MAX_STRING];trace_call(mod,ord,"DosSmSetTitle");if(!get_cstr(m,a[1],s,sizeof(s)))return OS2_ERROR_INVALID_PARAMETER;return PCAST(Fn,vp)(a[0],s);}
    if(ord==8){typedef uint32_t(__cdecl*Fn)(uint32_t,uint32_t);trace_call(mod,ord,"DosStopSession");return PCAST(Fn,vp)(a[0],a[1]);}
    if(ord==1000){typedef uint32_t(__cdecl*Fn)(void*,uint32_t,uint32_t*);void *buf;uint32_t count=0,bytes;trace_call(mod,ord,"O2HostQuerySessions");if(!need(m,a[2],4,1)||a[1]>4096u)return OS2_ERROR_INVALID_PARAMETER;bytes=a[1]*SES_WIRE_SIZE;if(bytes&&!need(m,a[0],bytes,1))return OS2_ERROR_INVALID_PARAMETER;buf=temp_alloc(bytes);if(!buf)return OS2_ERROR_NOT_ENOUGH_MEMORY;rc=PCAST(Fn,vp)(buf,a[1],&count);if((!rc&&bytes&&!m->write(m->opaque,a[0],buf,bytes))||!m->write(m->opaque,a[2],&count,4))rc=OS2_ERROR_INVALID_PARAMETER;free(buf);return rc;}
    if(ord==17){
        typedef uint32_t(__cdecl*Fn)(struct StartDataHost*,uint32_t*,uint32_t*);
        unsigned char w[60];struct StartDataHost h;uint32_t sid=0,pid=0,ga_obj=0,objlen=0;char *title=NULL,*name=NULL,*inputs=NULL,*termq=NULL,*icon=NULL;unsigned char *env=NULL;char *obj=NULL;
        trace_call(mod,ord,"DosStartSession");if(!need(m,a[0],8,0)||!need(m,a[1],4,1)||!need(m,a[2],4,1))return OS2_ERROR_INVALID_PARAMETER;memset(w,0,sizeof(w));if(!m->read(m->opaque,a[0],w,8))return OS2_ERROR_INVALID_PARAMETER;if(b16(w)>60u||b16(w)<8u||!need(m,a[0],b16(w),0)||!m->read(m->opaque,a[0],w,b16(w)))return OS2_ERROR_INVALID_PARAMETER;memset(&h,0,sizeof(h));
        h.Length=b16(w);h.Related=b16(w+2);h.FgBg=b16(w+4);h.TraceOpt=b16(w+6);
#define GP(off) b32(w+(off))
        if(h.Length>=12){title=dup_guest_cstr(m,GP(8));if(GP(8)&&!title)goto bad;h.PgmTitle=title;}
        if(h.Length>=16){name=dup_guest_cstr(m,GP(12));if(GP(12)&&!name)goto bad;h.PgmName=name;}
        if(h.Length>=20){inputs=dup_guest_cstr(m,GP(16));if(GP(16)&&!inputs)goto bad;h.PgmInputs=(unsigned char*)inputs;}
        if(h.Length>=24){termq=dup_guest_cstr(m,GP(20));if(GP(20)&&!termq)goto bad;h.TermQ=(unsigned char*)termq;}
        if(h.Length>=28){env=dup_multisz(m,GP(24));if(GP(24)&&!env)goto bad;h.Environment=env;}
        if(h.Length>=30) h.InheritOpt=b16(w+28);
        if(h.Length>=32) h.SessionType=b16(w+30);
        if(h.Length>=36){icon=dup_guest_cstr(m,GP(32));if(GP(32)&&!icon)goto bad;h.IconFile=icon;}
        if(h.Length>=40) h.PgmHandle=b32(w+36);
        if(h.Length>=42) h.PgmControl=b16(w+40);
        if(h.Length>=50){h.InitXPos=b16(w+42);h.InitYPos=b16(w+44);h.InitXSize=b16(w+46);h.InitYSize=b16(w+48);}if(h.Length>=52)h.Reserved=b16(w+50);
        if(h.Length>=60){ga_obj=GP(52);objlen=b32(w+56);if(objlen>65536u||(objlen&& !need(m,ga_obj,objlen,1)))goto bad;obj=(char*)temp_alloc(objlen);if(!obj)goto oom;h.ObjectBuffer=obj;h.ObjectBuffLen=objlen;}
        rc=PCAST(Fn,vp)(&h,&sid,&pid);if(!m->write(m->opaque,a[1],&sid,4)||!m->write(m->opaque,a[2],&pid,4))rc=OS2_ERROR_INVALID_PARAMETER;if(obj&&objlen&&!m->write(m->opaque,ga_obj,obj,objlen))rc=OS2_ERROR_INVALID_PARAMETER;
        free(title);free(name);free(inputs);free(termq);free(icon);free(env);free(obj);return rc;
    oom: rc=OS2_ERROR_NOT_ENOUGH_MEMORY;goto out;
    bad: rc=OS2_ERROR_INVALID_PARAMETER;
    out: free(title);free(name);free(inputs);free(termq);free(icon);free(env);free(obj);return rc;
#undef GP
    }
    return OS2_ERROR_INVALID_FUNCTION;
}

static unsigned flat_nargs(const char *module,uint32_t ord)
{
    if(eqi(module,"VIOCALLS")){
        switch(ord){case 7:return 7;case 9:return 3;case 13:return 5;case 15:return 3;case 19:return 3;case 21:return 2;case 24:return 5;case 26:return 5;case 27:return 2;case 32:return 2;case 48:return 6;case 52:return 5;default:return 0;}}
    if(eqi(module,"KBDCALLS")){switch(ord){case 4:return 3;case 9:return 4;case 10:case 11:case 22:return 2;case 13:return 1;default:return 0;}}
    if(eqi(module,"SESMGR")){switch(ord){case 5:case 8:return 2;case 17:case 1000:return 3;default:return 0;}}
    return 0;
}

uint32_t soft386_system_bridge_dispatch32(struct Soft386SystemBridge *b,const struct Soft386GuestMemoryOps *m,const char *module,uint32_t ord,uint32_t esp,int *handled)
{
    struct Soft386NativeModule *mod=get_module(b,module);uint32_t a[8]={0};unsigned n,i;
    n=flat_nargs(module,ord);if(handled)*handled=n!=0;if(!n)return OS2_ERROR_INVALID_FUNCTION;
    if(!mod||!mod->loaded) return OS2_ERROR_INVALID_FUNCTION;
    if(!m||!m->valid||!m->read||!m->write||!m->read_cstr||!m->read_u32) return OS2_ERROR_INVALID_PARAMETER;
    if(!m->valid(m->opaque,esp+4,n*4,0)) return OS2_ERROR_INVALID_PARAMETER;
    for(i=0;i<n;i++) a[i]=ru32(m,esp+4+4*i);
    if(eqi(module,"VIOCALLS")) return vio_dispatch(mod,m,ord,a);
    if(eqi(module,"KBDCALLS")) return kbd_dispatch(mod,m,ord,a);
    return ses_dispatch(mod,m,ord,a);
}

uint32_t soft386_system_bridge_dispatch_c386(struct Soft386SystemBridge *b,const struct Soft386GuestMemoryOps *m,uint32_t id,uint32_t esp,int *handled)
{
    const struct Soft386C386ApiDesc *d=soft386_c386_desc_by_id(id);struct Soft386NativeModule *mod;uint32_t packed[7]={0},a[7]={0},at=esp+4;unsigned i;
    if(handled) *handled=d!=NULL;
    if(!d) return OS2_ERROR_INVALID_FUNCTION;
    mod=get_module(b,d->module);
    if(!mod||!mod->loaded) return OS2_ERROR_INVALID_FUNCTION;
    for(i=0;i<d->count;i++){if(!m->valid(m->opaque,at,d->width[i],0))return OS2_ERROR_INVALID_PARAMETER;packed[i]=d->width[i]==2?ru16(m,at):ru32(m,at);at+=d->width[i];}
    for(i=0;i<d->count;i++)a[i]=packed[d->count-1u-i];
    if(eqi(d->module,"VIOCALLS")) return vio_dispatch(mod,m,d->ordinal,a);
    return kbd_dispatch(mod,m,d->ordinal,a);
}
