/* Do not edit this file manually.
   This file is autogenerated by windmc.  */

//
//  The values are 32 bit layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      C    - is the Customer code flag
//
//      R    - is a reserved bit
//
//      Code - is the facility's status code
//
//      Sev  - is the severity code
//
//           Success - 00
#define STATUS_SEVERITY_SUCCESS 0x0
//           Informational - 01
#define STATUS_SEVERITY_INFORMATIONAL 0x1
//           Warning - 02
#define STATUS_SEVERITY_WARNING 0x2
//           Error - 03
#define STATUS_SEVERITY_ERROR 0x3
//
//      Facility - is the facility code
//
//           System - 0000
#define FACILITY_SYSTEM 0x0
//           Application - 0fff
//

// Romanian translation by 2011-2019 ?tefan Fulea (stefan.fulea@mail.com)
// Romanian translation by 2023-2024 Andrei Miloiu (miloiuandrei@gmail.com)
// Russian translation by Kudratov Olimjon (olim98@bk.ru)
// Spanish translation by Ismael Ferreras Morezuelas <2014-11-07>
// Turkish translation by 2015 Erdem Ersoy (eersoy93) (erdemersoy [at] erdemersoy [dot] net)
// Simplified Chinese translation by Henry Tang Ih 2016 (henrytang2@hotmail.com)
// Traditional Chinese translation by Henry Tang Ih 2016 (henrytang2@hotmail.com)
// Polish translation Updated by pithwz - Piotr Hetnarowicz (piotrhwz@gmail.com) (April, 2020)
//
// MessageId: MSG_ACCOUNTS_SYNTAX
//
#define MSG_ACCOUNTS_SYNTAX (DWORD) 0x2710

//
// MessageId: MSG_ACCOUNTS_HELP
//
#define MSG_ACCOUNTS_HELP (DWORD) 0x2711

//
// MessageId: MSG_COMPUTER_SYNTAX
//
#define MSG_COMPUTER_SYNTAX (DWORD) 0x2712

//
// MessageId: MSG_COMPUTER_HELP
//
#define MSG_COMPUTER_HELP (DWORD) 0x2713

//
// MessageId: MSG_CONFIG_SYNTAX
//
#define MSG_CONFIG_SYNTAX (DWORD) 0x2714

//
// MessageId: MSG_CONFIG_HELP
//
#define MSG_CONFIG_HELP (DWORD) 0x2715

//
// MessageId: MSG_CONFIG_SERVER_SYNTAX
//
#define MSG_CONFIG_SERVER_SYNTAX (DWORD) 0x2716

//
// MessageId: MSG_CONFIG_SERVER_HELP
//
#define MSG_CONFIG_SERVER_HELP (DWORD) 0x2717

//
// MessageId: MSG_CONTINUE_SYNTAX
//
#define MSG_CONTINUE_SYNTAX (DWORD) 0x2718

//
// MessageId: MSG_CONTINUE_HELP
//
#define MSG_CONTINUE_HELP (DWORD) 0x2719

//
// MessageId: MSG_FILE_SYNTAX
//
#define MSG_FILE_SYNTAX (DWORD) 0x271a

//
// MessageId: MSG_FILE_HELP
//
#define MSG_FILE_HELP (DWORD) 0x271b

//
// MessageId: MSG_GROUP_SYNTAX
//
#define MSG_GROUP_SYNTAX (DWORD) 0x271c

//
// MessageId: MSG_GROUP_HELP
//
#define MSG_GROUP_HELP (DWORD) 0x271d

//
// MessageId: MSG_HELP_SYNTAX
//
#define MSG_HELP_SYNTAX (DWORD) 0x271e

//
// MessageId: MSG_HELP_HELP
//
#define MSG_HELP_HELP (DWORD) 0x271f

//
// MessageId: MSG_HELPMSG_SYNTAX
//
#define MSG_HELPMSG_SYNTAX (DWORD) 0x2720

//
// MessageId: MSG_HELPMSG_HELP
//
#define MSG_HELPMSG_HELP (DWORD) 0x2721

//
// MessageId: MSG_LOCALGROUP_SYNTAX
//
#define MSG_LOCALGROUP_SYNTAX (DWORD) 0x2722

//
// MessageId: MSG_LOCALGROUP_HELP
//
#define MSG_LOCALGROUP_HELP (DWORD) 0x2723

//
// MessageId: MSG_PAUSE_SYNTAX
//
#define MSG_PAUSE_SYNTAX (DWORD) 0x2724

//
// MessageId: MSG_PAUSE_HELP
//
#define MSG_PAUSE_HELP (DWORD) 0x2725

//
// MessageId: MSG_SESSION_SYNTAX
//
#define MSG_SESSION_SYNTAX (DWORD) 0x2726

//
// MessageId: MSG_SESSION_HELP
//
#define MSG_SESSION_HELP (DWORD) 0x2727

//
// MessageId: MSG_SHARE_SYNTAX
//
#define MSG_SHARE_SYNTAX (DWORD) 0x2728

//
// MessageId: MSG_SHARE_HELP
//
#define MSG_SHARE_HELP (DWORD) 0x2729

//
// MessageId: MSG_START_SYNTAX
//
#define MSG_START_SYNTAX (DWORD) 0x272a

//
// MessageId: MSG_START_HELP
//
#define MSG_START_HELP (DWORD) 0x272b

//
// MessageId: MSG_STATISTICS_SYNTAX
//
#define MSG_STATISTICS_SYNTAX (DWORD) 0x272c

//
// MessageId: MSG_STATISTICS_HELP
//
#define MSG_STATISTICS_HELP (DWORD) 0x272d

//
// MessageId: MSG_STOP_SYNTAX
//
#define MSG_STOP_SYNTAX (DWORD) 0x272e

//
// MessageId: MSG_STOP_HELP
//
#define MSG_STOP_HELP (DWORD) 0x272f

//
// MessageId: MSG_TIME_SYNTAX
//
#define MSG_TIME_SYNTAX (DWORD) 0x2730

//
// MessageId: MSG_TIME_HELP
//
#define MSG_TIME_HELP (DWORD) 0x2731

//
// MessageId: MSG_USE_SYNTAX
//
#define MSG_USE_SYNTAX (DWORD) 0x2732

//
// MessageId: MSG_USE_HELP
//
#define MSG_USE_HELP (DWORD) 0x2733

//
// MessageId: MSG_USER_SYNTAX
//
#define MSG_USER_SYNTAX (DWORD) 0x2734

//
// MessageId: MSG_USER_HELP
//
#define MSG_USER_HELP (DWORD) 0x2735

//
// MessageId: MSG_VIEW_SYNTAX
//
#define MSG_VIEW_SYNTAX (DWORD) 0x2736

//
// MessageId: MSG_VIEW_HELP
//
#define MSG_VIEW_HELP (DWORD) 0x2737

//
// MessageId: MSG_NET_SYNTAX
//
#define MSG_NET_SYNTAX (DWORD) 0x2738

//
// MessageId: MSG_SYNTAX_HELP
//
#define MSG_SYNTAX_HELP (DWORD) 0x2739

