/*** Autogenerated by WIDL <undefined version> from msctf_undoc.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __msctf_undoc_h__
#define __msctf_undoc_h__

/* Forward declarations */

#ifndef __ITfRangeAnchor_FWD_DEFINED__
#define __ITfRangeAnchor_FWD_DEFINED__
typedef interface ITfRangeAnchor ITfRangeAnchor;
#ifdef __cplusplus
interface ITfRangeAnchor;
#endif /* __cplusplus */
#endif

#ifndef __ITfDisplayAttributeCollectionMgr_FWD_DEFINED__
#define __ITfDisplayAttributeCollectionMgr_FWD_DEFINED__
typedef interface ITfDisplayAttributeCollectionMgr ITfDisplayAttributeCollectionMgr;
#ifdef __cplusplus
interface ITfDisplayAttributeCollectionMgr;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <msctf.h>
#include <inputscope.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * ITfRangeAnchor interface
 */
#ifndef __ITfRangeAnchor_INTERFACE_DEFINED__
#define __ITfRangeAnchor_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfRangeAnchor, 0x8b99712b, 0x5815, 0x4bcc, 0xb9,0xa9, 0x53,0xdb,0x1c,0x8d,0x67,0x55);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("8b99712b-5815-4bcc-b9a9-53db1c8d6755")
ITfRangeAnchor : public ITfRange
{
    virtual HRESULT STDMETHODCALLTYPE GetExtent(
        IAnchor **ppStart,
        IAnchor **ppEnd) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetExtent(
        IAnchor *pAnchorStart,
        IAnchor *pAnchorEnd) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfRangeAnchor, 0x8b99712b, 0x5815, 0x4bcc, 0xb9,0xa9, 0x53,0xdb,0x1c,0x8d,0x67,0x55)
#endif
#else
typedef struct ITfRangeAnchorVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfRangeAnchor *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfRangeAnchor *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfRangeAnchor *This);

    /*** ITfRange methods ***/
    HRESULT (STDMETHODCALLTYPE *GetText)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        DWORD dwFlags,
        WCHAR *pchText,
        ULONG cchMax,
        ULONG *pcch);

    HRESULT (STDMETHODCALLTYPE *SetText)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        DWORD dwFlags,
        const WCHAR *pchText,
        LONG cch);

    HRESULT (STDMETHODCALLTYPE *GetFormattedText)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        IDataObject **ppDataObject);

    HRESULT (STDMETHODCALLTYPE *GetEmbedded)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        REFGUID rguidService,
        REFIID riid,
        IUnknown **ppunk);

    HRESULT (STDMETHODCALLTYPE *InsertEmbedded)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        DWORD dwFlags,
        IDataObject *pDataObject);

    HRESULT (STDMETHODCALLTYPE *ShiftStart)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        LONG cchReq,
        LONG *pcch,
        const TF_HALTCOND *pHalt);

    HRESULT (STDMETHODCALLTYPE *ShiftEnd)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        LONG cchReq,
        LONG *pcch,
        const TF_HALTCOND *pHalt);

    HRESULT (STDMETHODCALLTYPE *ShiftStartToRange)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        ITfRange *pRange,
        TfAnchor aPos);

    HRESULT (STDMETHODCALLTYPE *ShiftEndToRange)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        ITfRange *pRange,
        TfAnchor aPos);

    HRESULT (STDMETHODCALLTYPE *ShiftStartRegion)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        TfShiftDir dir,
        BOOL *pfNoRegion);

    HRESULT (STDMETHODCALLTYPE *ShiftEndRegion)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        TfShiftDir dir,
        BOOL *pfNoRegion);

    HRESULT (STDMETHODCALLTYPE *IsEmpty)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        BOOL *pfEmpty);

    HRESULT (STDMETHODCALLTYPE *Collapse)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        TfAnchor aPos);

    HRESULT (STDMETHODCALLTYPE *IsEqualStart)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        ITfRange *pWith,
        TfAnchor aPos,
        BOOL *pfEqual);

    HRESULT (STDMETHODCALLTYPE *IsEqualEnd)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        ITfRange *pWith,
        TfAnchor aPos,
        BOOL *pfEqual);

    HRESULT (STDMETHODCALLTYPE *CompareStart)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        ITfRange *pWith,
        TfAnchor aPos,
        LONG *plResult);

    HRESULT (STDMETHODCALLTYPE *CompareEnd)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        ITfRange *pWith,
        TfAnchor aPos,
        LONG *plResult);

    HRESULT (STDMETHODCALLTYPE *AdjustForInsert)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        ULONG cchInsert,
        BOOL *pfInsertOk);

    HRESULT (STDMETHODCALLTYPE *GetGravity)(
        ITfRangeAnchor *This,
        TfGravity *pgStart,
        TfGravity *pgEnd);

    HRESULT (STDMETHODCALLTYPE *SetGravity)(
        ITfRangeAnchor *This,
        TfEditCookie ec,
        TfGravity gStart,
        TfGravity gEnd);

    HRESULT (STDMETHODCALLTYPE *Clone)(
        ITfRangeAnchor *This,
        ITfRange **ppClone);

    HRESULT (STDMETHODCALLTYPE *GetContext)(
        ITfRangeAnchor *This,
        ITfContext **ppContext);

    /*** ITfRangeAnchor methods ***/
    HRESULT (STDMETHODCALLTYPE *GetExtent)(
        ITfRangeAnchor *This,
        IAnchor **ppStart,
        IAnchor **ppEnd);

    HRESULT (STDMETHODCALLTYPE *SetExtent)(
        ITfRangeAnchor *This,
        IAnchor *pAnchorStart,
        IAnchor *pAnchorEnd);

    END_INTERFACE
} ITfRangeAnchorVtbl;

interface ITfRangeAnchor {
    CONST_VTBL ITfRangeAnchorVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfRangeAnchor_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfRangeAnchor_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfRangeAnchor_Release(This) (This)->lpVtbl->Release(This)
/*** ITfRange methods ***/
#define ITfRangeAnchor_GetText(This,ec,dwFlags,pchText,cchMax,pcch) (This)->lpVtbl->GetText(This,ec,dwFlags,pchText,cchMax,pcch)
#define ITfRangeAnchor_SetText(This,ec,dwFlags,pchText,cch) (This)->lpVtbl->SetText(This,ec,dwFlags,pchText,cch)
#define ITfRangeAnchor_GetFormattedText(This,ec,ppDataObject) (This)->lpVtbl->GetFormattedText(This,ec,ppDataObject)
#define ITfRangeAnchor_GetEmbedded(This,ec,rguidService,riid,ppunk) (This)->lpVtbl->GetEmbedded(This,ec,rguidService,riid,ppunk)
#define ITfRangeAnchor_InsertEmbedded(This,ec,dwFlags,pDataObject) (This)->lpVtbl->InsertEmbedded(This,ec,dwFlags,pDataObject)
#define ITfRangeAnchor_ShiftStart(This,ec,cchReq,pcch,pHalt) (This)->lpVtbl->ShiftStart(This,ec,cchReq,pcch,pHalt)
#define ITfRangeAnchor_ShiftEnd(This,ec,cchReq,pcch,pHalt) (This)->lpVtbl->ShiftEnd(This,ec,cchReq,pcch,pHalt)
#define ITfRangeAnchor_ShiftStartToRange(This,ec,pRange,aPos) (This)->lpVtbl->ShiftStartToRange(This,ec,pRange,aPos)
#define ITfRangeAnchor_ShiftEndToRange(This,ec,pRange,aPos) (This)->lpVtbl->ShiftEndToRange(This,ec,pRange,aPos)
#define ITfRangeAnchor_ShiftStartRegion(This,ec,dir,pfNoRegion) (This)->lpVtbl->ShiftStartRegion(This,ec,dir,pfNoRegion)
#define ITfRangeAnchor_ShiftEndRegion(This,ec,dir,pfNoRegion) (This)->lpVtbl->ShiftEndRegion(This,ec,dir,pfNoRegion)
#define ITfRangeAnchor_IsEmpty(This,ec,pfEmpty) (This)->lpVtbl->IsEmpty(This,ec,pfEmpty)
#define ITfRangeAnchor_Collapse(This,ec,aPos) (This)->lpVtbl->Collapse(This,ec,aPos)
#define ITfRangeAnchor_IsEqualStart(This,ec,pWith,aPos,pfEqual) (This)->lpVtbl->IsEqualStart(This,ec,pWith,aPos,pfEqual)
#define ITfRangeAnchor_IsEqualEnd(This,ec,pWith,aPos,pfEqual) (This)->lpVtbl->IsEqualEnd(This,ec,pWith,aPos,pfEqual)
#define ITfRangeAnchor_CompareStart(This,ec,pWith,aPos,plResult) (This)->lpVtbl->CompareStart(This,ec,pWith,aPos,plResult)
#define ITfRangeAnchor_CompareEnd(This,ec,pWith,aPos,plResult) (This)->lpVtbl->CompareEnd(This,ec,pWith,aPos,plResult)
#define ITfRangeAnchor_AdjustForInsert(This,ec,cchInsert,pfInsertOk) (This)->lpVtbl->AdjustForInsert(This,ec,cchInsert,pfInsertOk)
#define ITfRangeAnchor_GetGravity(This,pgStart,pgEnd) (This)->lpVtbl->GetGravity(This,pgStart,pgEnd)
#define ITfRangeAnchor_SetGravity(This,ec,gStart,gEnd) (This)->lpVtbl->SetGravity(This,ec,gStart,gEnd)
#define ITfRangeAnchor_Clone(This,ppClone) (This)->lpVtbl->Clone(This,ppClone)
#define ITfRangeAnchor_GetContext(This,ppContext) (This)->lpVtbl->GetContext(This,ppContext)
/*** ITfRangeAnchor methods ***/
#define ITfRangeAnchor_GetExtent(This,ppStart,ppEnd) (This)->lpVtbl->GetExtent(This,ppStart,ppEnd)
#define ITfRangeAnchor_SetExtent(This,pAnchorStart,pAnchorEnd) (This)->lpVtbl->SetExtent(This,pAnchorStart,pAnchorEnd)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfRangeAnchor_QueryInterface(ITfRangeAnchor* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfRangeAnchor_AddRef(ITfRangeAnchor* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfRangeAnchor_Release(ITfRangeAnchor* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfRange methods ***/
static inline HRESULT ITfRangeAnchor_GetText(ITfRangeAnchor* This,TfEditCookie ec,DWORD dwFlags,WCHAR *pchText,ULONG cchMax,ULONG *pcch) {
    return This->lpVtbl->GetText(This,ec,dwFlags,pchText,cchMax,pcch);
}
static inline HRESULT ITfRangeAnchor_SetText(ITfRangeAnchor* This,TfEditCookie ec,DWORD dwFlags,const WCHAR *pchText,LONG cch) {
    return This->lpVtbl->SetText(This,ec,dwFlags,pchText,cch);
}
static inline HRESULT ITfRangeAnchor_GetFormattedText(ITfRangeAnchor* This,TfEditCookie ec,IDataObject **ppDataObject) {
    return This->lpVtbl->GetFormattedText(This,ec,ppDataObject);
}
static inline HRESULT ITfRangeAnchor_GetEmbedded(ITfRangeAnchor* This,TfEditCookie ec,REFGUID rguidService,REFIID riid,IUnknown **ppunk) {
    return This->lpVtbl->GetEmbedded(This,ec,rguidService,riid,ppunk);
}
static inline HRESULT ITfRangeAnchor_InsertEmbedded(ITfRangeAnchor* This,TfEditCookie ec,DWORD dwFlags,IDataObject *pDataObject) {
    return This->lpVtbl->InsertEmbedded(This,ec,dwFlags,pDataObject);
}
static inline HRESULT ITfRangeAnchor_ShiftStart(ITfRangeAnchor* This,TfEditCookie ec,LONG cchReq,LONG *pcch,const TF_HALTCOND *pHalt) {
    return This->lpVtbl->ShiftStart(This,ec,cchReq,pcch,pHalt);
}
static inline HRESULT ITfRangeAnchor_ShiftEnd(ITfRangeAnchor* This,TfEditCookie ec,LONG cchReq,LONG *pcch,const TF_HALTCOND *pHalt) {
    return This->lpVtbl->ShiftEnd(This,ec,cchReq,pcch,pHalt);
}
static inline HRESULT ITfRangeAnchor_ShiftStartToRange(ITfRangeAnchor* This,TfEditCookie ec,ITfRange *pRange,TfAnchor aPos) {
    return This->lpVtbl->ShiftStartToRange(This,ec,pRange,aPos);
}
static inline HRESULT ITfRangeAnchor_ShiftEndToRange(ITfRangeAnchor* This,TfEditCookie ec,ITfRange *pRange,TfAnchor aPos) {
    return This->lpVtbl->ShiftEndToRange(This,ec,pRange,aPos);
}
static inline HRESULT ITfRangeAnchor_ShiftStartRegion(ITfRangeAnchor* This,TfEditCookie ec,TfShiftDir dir,BOOL *pfNoRegion) {
    return This->lpVtbl->ShiftStartRegion(This,ec,dir,pfNoRegion);
}
static inline HRESULT ITfRangeAnchor_ShiftEndRegion(ITfRangeAnchor* This,TfEditCookie ec,TfShiftDir dir,BOOL *pfNoRegion) {
    return This->lpVtbl->ShiftEndRegion(This,ec,dir,pfNoRegion);
}
static inline HRESULT ITfRangeAnchor_IsEmpty(ITfRangeAnchor* This,TfEditCookie ec,BOOL *pfEmpty) {
    return This->lpVtbl->IsEmpty(This,ec,pfEmpty);
}
static inline HRESULT ITfRangeAnchor_Collapse(ITfRangeAnchor* This,TfEditCookie ec,TfAnchor aPos) {
    return This->lpVtbl->Collapse(This,ec,aPos);
}
static inline HRESULT ITfRangeAnchor_IsEqualStart(ITfRangeAnchor* This,TfEditCookie ec,ITfRange *pWith,TfAnchor aPos,BOOL *pfEqual) {
    return This->lpVtbl->IsEqualStart(This,ec,pWith,aPos,pfEqual);
}
static inline HRESULT ITfRangeAnchor_IsEqualEnd(ITfRangeAnchor* This,TfEditCookie ec,ITfRange *pWith,TfAnchor aPos,BOOL *pfEqual) {
    return This->lpVtbl->IsEqualEnd(This,ec,pWith,aPos,pfEqual);
}
static inline HRESULT ITfRangeAnchor_CompareStart(ITfRangeAnchor* This,TfEditCookie ec,ITfRange *pWith,TfAnchor aPos,LONG *plResult) {
    return This->lpVtbl->CompareStart(This,ec,pWith,aPos,plResult);
}
static inline HRESULT ITfRangeAnchor_CompareEnd(ITfRangeAnchor* This,TfEditCookie ec,ITfRange *pWith,TfAnchor aPos,LONG *plResult) {
    return This->lpVtbl->CompareEnd(This,ec,pWith,aPos,plResult);
}
static inline HRESULT ITfRangeAnchor_AdjustForInsert(ITfRangeAnchor* This,TfEditCookie ec,ULONG cchInsert,BOOL *pfInsertOk) {
    return This->lpVtbl->AdjustForInsert(This,ec,cchInsert,pfInsertOk);
}
static inline HRESULT ITfRangeAnchor_GetGravity(ITfRangeAnchor* This,TfGravity *pgStart,TfGravity *pgEnd) {
    return This->lpVtbl->GetGravity(This,pgStart,pgEnd);
}
static inline HRESULT ITfRangeAnchor_SetGravity(ITfRangeAnchor* This,TfEditCookie ec,TfGravity gStart,TfGravity gEnd) {
    return This->lpVtbl->SetGravity(This,ec,gStart,gEnd);
}
static inline HRESULT ITfRangeAnchor_Clone(ITfRangeAnchor* This,ITfRange **ppClone) {
    return This->lpVtbl->Clone(This,ppClone);
}
static inline HRESULT ITfRangeAnchor_GetContext(ITfRangeAnchor* This,ITfContext **ppContext) {
    return This->lpVtbl->GetContext(This,ppContext);
}
/*** ITfRangeAnchor methods ***/
static inline HRESULT ITfRangeAnchor_GetExtent(ITfRangeAnchor* This,IAnchor **ppStart,IAnchor **ppEnd) {
    return This->lpVtbl->GetExtent(This,ppStart,ppEnd);
}
static inline HRESULT ITfRangeAnchor_SetExtent(ITfRangeAnchor* This,IAnchor *pAnchorStart,IAnchor *pAnchorEnd) {
    return This->lpVtbl->SetExtent(This,pAnchorStart,pAnchorEnd);
}
#endif
#endif

#endif


#endif  /* __ITfRangeAnchor_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ITfDisplayAttributeCollectionMgr interface
 */
#ifndef __ITfDisplayAttributeCollectionMgr_INTERFACE_DEFINED__
#define __ITfDisplayAttributeCollectionMgr_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITfDisplayAttributeCollectionMgr, 0x4e3d2d48, 0x3c17, 0x457d, 0x84,0xa1, 0xf2,0x09,0x47,0x6d,0xe8,0x97);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("4e3d2d48-3c17-457d-84a1-f209476de897")
ITfDisplayAttributeCollectionMgr : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE UnknownMethod(
        DWORD unused) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITfDisplayAttributeCollectionMgr, 0x4e3d2d48, 0x3c17, 0x457d, 0x84,0xa1, 0xf2,0x09,0x47,0x6d,0xe8,0x97)
#endif
#else
typedef struct ITfDisplayAttributeCollectionMgrVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITfDisplayAttributeCollectionMgr *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITfDisplayAttributeCollectionMgr *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITfDisplayAttributeCollectionMgr *This);

    /*** ITfDisplayAttributeCollectionMgr methods ***/
    HRESULT (STDMETHODCALLTYPE *UnknownMethod)(
        ITfDisplayAttributeCollectionMgr *This,
        DWORD unused);

    END_INTERFACE
} ITfDisplayAttributeCollectionMgrVtbl;

interface ITfDisplayAttributeCollectionMgr {
    CONST_VTBL ITfDisplayAttributeCollectionMgrVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITfDisplayAttributeCollectionMgr_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITfDisplayAttributeCollectionMgr_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITfDisplayAttributeCollectionMgr_Release(This) (This)->lpVtbl->Release(This)
/*** ITfDisplayAttributeCollectionMgr methods ***/
#define ITfDisplayAttributeCollectionMgr_UnknownMethod(This,unused) (This)->lpVtbl->UnknownMethod(This,unused)
#else
/*** IUnknown methods ***/
static inline HRESULT ITfDisplayAttributeCollectionMgr_QueryInterface(ITfDisplayAttributeCollectionMgr* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG ITfDisplayAttributeCollectionMgr_AddRef(ITfDisplayAttributeCollectionMgr* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG ITfDisplayAttributeCollectionMgr_Release(ITfDisplayAttributeCollectionMgr* This) {
    return This->lpVtbl->Release(This);
}
/*** ITfDisplayAttributeCollectionMgr methods ***/
static inline HRESULT ITfDisplayAttributeCollectionMgr_UnknownMethod(ITfDisplayAttributeCollectionMgr* This,DWORD unused) {
    return This->lpVtbl->UnknownMethod(This,unused);
}
#endif
#endif

#endif


#endif  /* __ITfDisplayAttributeCollectionMgr_INTERFACE_DEFINED__ */

BOOL WINAPI TF_InitSystem(VOID);
BOOL WINAPI TF_UninitSystem(VOID);
HRESULT WINAPI TF_GetGlobalCompartment(_Out_ ITfCompartmentMgr **ppCompMgr);
HRESULT WINAPI TF_PostAllThreadMsg(_In_opt_ WPARAM wParam, _In_ DWORD dwFlags);
HANDLE WINAPI TF_CreateCicLoadMutex(_Out_ LPBOOL pfWinLogon);
HRESULT WINAPI TF_InvalidAssemblyListCache(VOID);
HRESULT WINAPI TF_InvalidAssemblyListCacheIfExist(VOID);
HICON WINAPI TF_GetLangIcon(_In_ LANGID LangID, _Out_writes_(cchText) PWSTR pszText, _In_ INT cchText);
VOID WINAPI TF_InitMlngInfo(VOID);
INT WINAPI TF_MlngInfoCount(VOID);
INT WINAPI TF_GetMlngIconIndex(_In_ INT iKL);
HICON WINAPI TF_InatExtractIcon(_In_ INT iKL);
HRESULT WINAPI TF_RunInputCPL(VOID);
LONG WINAPI TF_CheckThreadInputIdle(_In_ DWORD dwThreadId, _In_ DWORD dwMilliseconds);
BOOL WINAPI TF_IsInMarshaling(_In_ DWORD dwThreadId);
// This is intentionally misspelled to match the original name:
BOOL WINAPI TF_IsFullScreenWindowAcitvated(VOID);
HRESULT WINAPI TF_CUASAppFix(_In_ LPCSTR pszName);
HRESULT WINAPI TF_ClearLangBarAddIns(_In_ REFGUID rguid);
HRESULT WINAPI TF_GetInputScope(_In_opt_ HWND hWnd, _Out_ ITfInputScope **ppInputScope);
BOOL WINAPI TF_DllDetachInOther(VOID);
BOOL WINAPI
TF_GetMlngHKL(
    _In_ INT iKL,
    _Out_opt_ HKL *phKL,
    _Out_writes_opt_(cchText) LPWSTR pszText,
    _In_ INT cchText);
BOOL WINAPI
TF_GetThreadFlags(
    _In_ DWORD dwThreadId,
    _Out_ LPDWORD pdwFlags1,
    _Out_ LPDWORD pdwFlags2,
    _Out_ LPDWORD pdwFlags3);
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __msctf_undoc_h__ */
