#!/usr/bin/env python3
"""Generate the built-in SBCS case tables used by common/nls/os2_nls.c.

The byte-to-Unicode mappings come from Python's standard cp437/cp850 codecs.
Case conversion uses Python/Unicode single-character upper/lower mappings; if a
mapping expands to multiple Unicode characters or cannot be represented back
in the same code page, the original byte is retained.  The generated file is
checked into the tree so runtime/build hosts do not need Python codecs.
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "common" / "nls" / "os2_nls_tables.inc"


def case_table(encoding: str, upper: bool) -> list[int]:
    result: list[int] = []
    for value in range(256):
        ch = bytes([value]).decode(encoding)
        mapped = ch.upper() if upper else ch.lower()
        out = value
        if len(mapped) == 1:
            try:
                encoded = mapped.encode(encoding)
            except UnicodeEncodeError:
                encoded = b""
            if len(encoded) == 1:
                out = encoded[0]
        result.append(out)
    return result


def emit_array(name: str, values: list[int]) -> str:
    lines = [f"static const unsigned char {name}[256] = {{"]
    for start in range(0, 256, 16):
        chunk = values[start : start + 16]
        lines.append("    " + ", ".join(f"0x{x:02x}" for x in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def rendered() -> str:
    parts = [
        "/* Generated by tools/gen_nls_tables.py; do not edit by hand. */",
        "/* Source mappings: Python standard cp437/cp850 codecs plus Unicode",
        " * single-character upper/lower mappings. Expanding/unrepresentable",
        " * case mappings retain the original byte. */",
        "",
    ]
    for enc in ("cp437", "cp850"):
        suffix = enc[2:]
        parts.append(emit_array(f"os2_cp{suffix}_upper", case_table(enc, True)))
        parts.append("")
        parts.append(emit_array(f"os2_cp{suffix}_lower", case_table(enc, False)))
        parts.append("")
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = rendered()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="ascii") != text:
            print(f"FAIL: {OUT.relative_to(ROOT)} is stale")
            return 1
        print("PASS: built-in CP437/CP850 case tables are reproducible")
        return 0
    OUT.write_text(text, encoding="ascii")
    print(OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
