
...Your science officer has detected a nebula in this sector suitable for
system formation.  After you register your claim with The Imperial Bureau of
Expansionist Affairs, a heavily-armed battlecruiser, the Vengeance, arrives
with your torpedo.  After verification of both your identity and your bank
account, the torpedo is installed in your ship's torpedo launcher.  Then,
following a complimentary dinner with the dreadnaught's Captain, you give the
order to arm and launch the Genesis device.

...as the Genesis Torpedo leaves the torpedo bay of your ship, it begins to
glow brilliantly as it begins to accelerate it's mass to the critical point.
You immediately warp out of range of the Genesis envelope, and four minutes
later the nebula is transformed into a thriving planetary system with such a
fantastic display of pyrotechnical special effects that it could never be
depicted in a low budget simulation like this!

...After a large, drunken orgy of the typical Klingon type, the Vengeance
warps out for new worlds to rape and pillage, leaving you to to do the same
to your new world...

