...as your fighters are deployed within the Sol system, they are immediately
annihilated by what at first appears to be a VERY powerful phaser array that
has been mounted on the Federation's Nogura Space Dock. However, both your
Science Officer and your Weapons officers inform you that not only does the
Space Dock lack the power to generate a phaser barrage of such magnitude,
but that they have detected the source of the attack and it is closing on
an intercept course with the ship at extreme warp speed...

                   >SMASH<CRUNCH>REND<POW!>BOOOM!!<

...suddenly, something hits your ship, the camera tilts, and your crew falls
out of their chairs like a bunch of idiots. Since this is only a simulation,
you stay in your chair, even when the port side of the bridge splits open
with a hole just big enough for a man to step through. Which, of course, is
what happens, as a man dressed in red and blue with a flowing cape boards the
ship and tells you to get the hell away from Earth!. He then closes the gap
in the hull, welds it shut with what appears to be phasers imbedded in his
eyes, and then pushes your ship out of this stellar system.

...later, after the damage control officer has informed you of your losses
(10% of your fighters, and a cargo hold), the science officer informs you
that Imperial Intelligence has identified the mysterious caped invader as
a Mr. Kent, who resides in a city named Metropolis on Earth, and is known
for his rather...physical methods of repelling invaders. You shrug your
shoulders in disgruntlement and return to deciding your next port of call...

