Your trusted & loyal Chief Engineer, L'Hurd, informs you that he can build a
mine out of equipment already onboard your ship.  To build a standard mine,
he will need two cargo holds(empty), and 5 K3-A fighters for propulsion,
navigation, and as energy cells for the detonation.  Your blood lust gets the
better of you, and you agree.  He sets to work, and in a remarkably short
period of time, he reports back to you that he has accomplished his task, and
that moored next to you in deep space is a fearsome, self-propelled ship
killer, capable of awesome destructive force.  The Science Officer, Ficus,
interjects to tell you that the mine's navigation & propulsion systems are only
good enough to catch one-out-of-ten merchant ships, though.  You ponder this as
you give the order to arm and release the mine...
